NUCLEO-G0B1RE Examples: NUCLEO-G0B1RE/FreeRTOS_Queues/Src/main.c File Reference
main.c File Reference
#include "main.h"
#include "cmsis_os.h"
Macros
#define blckqSTACK_SIZE configMINIMAL_STACK_SIZE
Functions
void SystemClock_Config (void)
System Clock Configuration.
void MessageQueueProducer (void *argument)
Function implementing the MessageQueuePro thread.
void MessageQueueConsumer (void *argument)
Function implementing the MessageQueueCon thread.
int main (void)
The application entry point.
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef *htim)
Period elapsed callback in non blocking mode.
void Error_Handler (void)
This function is executed in case of error occurrence.
Variables
osThreadId_t MessageQueueProHandle
const osThreadAttr_t MessageQueuePro_attributes
osThreadId_t MessageQueueConHandle
const osThreadAttr_t MessageQueueCon_attributes
osMessageQueueId_t osQueueHandle
const osMessageQueueAttr_t osQueue_attributes
uint32_t osQueueMsg
uint32_t ProducerValue = 0
uint32_t ConsumerValue = 0
__IO uint32_t ProducerErrors = 0
__IO uint32_t ConsumerErrors = 0
Macro Definition Documentation
blckqSTACK_SIZE
#define blckqSTACK_SIZE configMINIMAL_STACK_SIZE
Definition at line 41 of file main.c.
Function Documentation
Error_Handler()
void Error_Handler (void)
This function is executed in case of error occurrence.
Return values
None
Definition at line 319 of file main.c.
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  /* USER CODE END Error_Handler_Debug */
}
Referenced by main(), MX_TIM1_Init(), and SystemClock_Config().
HAL_TIM_PeriodElapsedCallback()
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef * htim)
Period elapsed callback in non blocking mode.
Note
This function is called when TIM6 interrupt took place, inside HAL_TIM_IRQHandler(). It makes a direct call to HAL_IncTick() to increment a global variable "uwTick" used as application time base.
Parameters
htim : TIM handle
Return values
None
Definition at line 302 of file main.c.
{
  /* USER CODE BEGIN Callback 0 */
  /* USER CODE END Callback 0 */
  if (htim->Instance == TIM6) {
    HAL_IncTick();
  }
  /* USER CODE BEGIN Callback 1 */
  /* USER CODE END Callback 1 */
}
main()
int main (void)
The application entry point.
Return values
int
Definition at line 88 of file main.c.
{
  /* USER CODE BEGIN 1 */
  /* USER CODE END 1 */
  /* MCU Configuration--------------------------------------------------------*/
  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();
  /* USER CODE BEGIN Init */
  /* USER CODE END Init */
  /* Configure the system clock */
  SystemClock_Config();
  /* USER CODE BEGIN SysInit */
  /* Initialize LED */
  BSP_LED_Init(LED4);
  /* USER CODE END SysInit */
  /* Initialize all configured peripherals */
  /* USER CODE BEGIN 2 */
  /* USER CODE END 2 */
  /* Init scheduler */
  osKernelInitialize();
  /* USER CODE BEGIN RTOS_MUTEX */
  /* USER CODE END RTOS_MUTEX */
  /* USER CODE BEGIN RTOS_SEMAPHORES */
  /* USER CODE END RTOS_SEMAPHORES */
  /* USER CODE BEGIN RTOS_TIMERS */
  /* USER CODE END RTOS_TIMERS */
  /* Create the queue(s) */
  /* creation of osQueue */
  osQueueHandle = osMessageQueueNew (1, sizeof(uint16_t), &osQueue_attributes);
  /* USER CODE BEGIN RTOS_QUEUES */
  /* USER CODE END RTOS_QUEUES */
  /* Create the thread(s) */
  /* creation of MessageQueuePro */
  MessageQueueProHandle = osThreadNew(MessageQueueProducer, NULL, &MessageQueuePro_attributes);
  /* creation of MessageQueueCon */
  MessageQueueConHandle = osThreadNew(MessageQueueConsumer, NULL, &MessageQueueCon_attributes);
  /* USER CODE BEGIN RTOS_THREADS */
  /* USER CODE END RTOS_THREADS */
  /* USER CODE BEGIN RTOS_EVENTS */
  /* add events, ... */
  /* USER CODE END RTOS_EVENTS */
  /* Start scheduler */
  osKernelStart();
  /* We should never get here as control is now taken by the scheduler */
  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
    /* USER CODE END WHILE */
    /* USER CODE BEGIN 3 */
  }
  /* USER CODE END 3 */
}
References MessageQueueCon_attributes, MessageQueueConHandle, MessageQueueConsumer(), MessageQueuePro_attributes, MessageQueueProducer(), MessageQueueProHandle, osKernelInitialize(), osKernelStart(), osMessageQueueNew(), osQueue_attributes, osQueueHandle, osThreadNew(), and SystemClock_Config().
MessageQueueConsumer()
void MessageQueueConsumer (void * argument)
Function implementing the MessageQueueCon thread.
Parameters
argument Not used
Return values
None
Definition at line 261 of file main.c.
{
  /* USER CODE BEGIN MessageQueueConsumer */
  osStatus_t status;
  for (;;)
  {
    /* Get the message from the queue */
    status = osMessageQueueGet(osQueueHandle, &osQueueMsg, NULL, 100);
    if (status == osOK)
    {
      if (osQueueMsg != ConsumerValue)
      {
        /* Catch-up */
        ConsumerValue = osQueueMsg;
        ++ConsumerErrors;
        /* Switch On continuously LED4 to indicate error */
        BSP_LED_On(LED4);
      }
      else
      {
        /* Increment the value we expect to remove from the queue next time
        round */
        ++ConsumerValue;
      }
    }
  }
  /* USER CODE END MessageQueueConsumer */
}
References ConsumerErrors, ConsumerValue, osMessageQueueGet(), osOK, osQueueHandle, and osQueueMsg.
Referenced by main().
MessageQueueProducer()
void MessageQueueProducer (void * argument)
Function implementing the MessageQueuePro thread.
Parameters
argument Not used
Return values
None
Definition at line 227 of file main.c.
{
  /* USER CODE BEGIN 5 */
  /* Infinite loop */
  for (;;)
  {
    if (osMessageQueuePut(osQueueHandle, &ProducerValue, 100, 0) != osOK)
    {
      ++ProducerErrors;
      /* Switch On continuously LED4 to indicate error */
      BSP_LED_On(LED4);
    }
    else
    {
      /* Increment the variable we are going to post next time round.  The
      consumer will expect the numbers to follow in numerical order */
      ++ProducerValue;
      if( (ProducerErrors == 0) && (ConsumerErrors == 0) )
        BSP_LED_Toggle(LED4);
      osDelay(1000);
    }
  }
  /* USER CODE END 5 */
}
References ConsumerErrors, osDelay(), osMessageQueuePut(), osOK, osQueueHandle, ProducerErrors, and ProducerValue.
Referenced by main().
SystemClock_Config()
void SystemClock_Config (void)
System Clock Configuration.
Return values
None
Configure the main internal regulator output voltage
Initializes the RCC Oscillators according to the specified parameters in the RCC_OscInitTypeDef structure.
Initializes the CPU, AHB and APB buses clocks
Definition at line 174 of file main.c.
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
  HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1);
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSIDiv = RCC_HSI_DIV1;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLM = RCC_PLLM_DIV1;
  RCC_OscInitStruct.PLL.PLLN = 8;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
  RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
  RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
  {
    Error_Handler();
  }
}
References Error_Handler().
Referenced by main().
Variable Documentation
ConsumerErrors
__IO uint32_t ConsumerErrors = 0
Definition at line 67 of file main.c.
Referenced by MessageQueueConsumer(), and MessageQueueProducer().
ConsumerValue
uint32_t ConsumerValue = 0
Definition at line 66 of file main.c.
Referenced by MessageQueueConsumer().
MessageQueueCon_attributes
const osThreadAttr_t MessageQueueCon_attributes
Initial value:
= {
  .name = "MessageQueueCon",
  .priority = (osPriority_t) osPriorityLow,
  .stack_size = 128 * 4
}
Definition at line 54 of file main.c.
{
  .name = "MessageQueueCon",
  .priority = (osPriority_t) osPriorityLow,
  .stack_size = 128 * 4
};
Referenced by main().
MessageQueueConHandle
osThreadId_t MessageQueueConHandle
Definition at line 53 of file main.c.
Referenced by main().
MessageQueuePro_attributes
const osThreadAttr_t MessageQueuePro_attributes
Initial value:
= {
  .name = "MessageQueuePro",
  .priority = (osPriority_t) osPriorityNormal,
  .stack_size = 128 * 4
}
Definition at line 47 of file main.c.
{
  .name = "MessageQueuePro",
  .priority = (osPriority_t) osPriorityNormal,
  .stack_size = 128 * 4
};
Referenced by main().
MessageQueueProHandle
osThreadId_t MessageQueueProHandle
Definition at line 46 of file main.c.
Referenced by main().
osQueue_attributes
const osMessageQueueAttr_t osQueue_attributes
Initial value:
= {
  .name = "osQueue"
}
Definition at line 61 of file main.c.
{
  .name = "osQueue"
};
Referenced by main().
osQueueHandle
osMessageQueueId_t osQueueHandle
Definition at line 60 of file main.c.
Referenced by main(), MessageQueueConsumer(), and MessageQueueProducer().
osQueueMsg
uint32_t osQueueMsg
Definition at line 65 of file main.c.
Referenced by MessageQueueConsumer().
ProducerErrors
__IO uint32_t ProducerErrors = 0
Definition at line 67 of file main.c.
Referenced by MessageQueueProducer().
ProducerValue
uint32_t ProducerValue = 0
Definition at line 66 of file main.c.
Referenced by MessageQueueProducer().