NUCLEO-G0B1RE Examples: NUCLEO-G0B1RE/FreeRTOS_Queues/Middlewares/Third_Party/FreeRTOS/Source/include/portable.h File Reference
portable.h File Reference
#include "deprecated_definitions.h"
#include "portmacro.h"
#include "mpu_wrappers.h"
Data Structures
struct HeapRegion
struct xHeapStats
Macros
#define portNUM_CONFIGURABLE_REGIONS 1
#define portHAS_STACK_OVERFLOW_CHECKING 0
#define portARCH_NAME NULL
Typedefs
typedef struct HeapRegion HeapRegion_t
typedef struct xHeapStats HeapStats_t
Functions
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
void vPortDefineHeapRegions (const HeapRegion_t *const pxHeapRegions)
void vPortGetHeapStats (HeapStats_t *pxHeapStats)
void * pvPortMalloc (size_t xSize)
void vPortFree (void *pv)
void vPortInitialiseBlocks (void)
size_t xPortGetFreeHeapSize (void)
size_t xPortGetMinimumEverFreeHeapSize (void)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
Macro Definition Documentation
portARCH_NAME
#define portARCH_NAME NULL
Definition at line 92 of file portable.h.
portHAS_STACK_OVERFLOW_CHECKING
#define portHAS_STACK_OVERFLOW_CHECKING 0
Definition at line 88 of file portable.h.
portNUM_CONFIGURABLE_REGIONS
#define portNUM_CONFIGURABLE_REGIONS 1
Definition at line 84 of file portable.h.
Typedef Documentation
HeapRegion_t
typedef struct HeapRegion HeapRegion_t
HeapStats_t
typedef struct xHeapStats HeapStats_t
Function Documentation
pvPortMalloc()
void * pvPortMalloc (size_t xSize)
Definition at line 115 of file heap_4.c.
{
BlockLink_t *pxBlock, *pxPreviousBlock, *pxNewBlockLink;
void *pvReturn = NULL;
  vTaskSuspendAll();
  {
    /* If this is the first call to malloc then the heap will require
    initialisation to setup the list of free blocks. */
    if( pxEnd == NULL )
    {
      prvHeapInit();
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
    /* Check the requested block size is not so large that the top bit is
    set.  The top bit of the block size member of the BlockLink_t structure
    is used to determine who owns the block - the application or the
    kernel, so it must be free. */
    if( ( xWantedSize & xBlockAllocatedBit ) == 0 )
    {
      /* The wanted size is increased so it can contain a BlockLink_t
      structure in addition to the requested amount of bytes. */
      if( xWantedSize > 0 )
      {
        xWantedSize += xHeapStructSize;
        /* Ensure that blocks are always aligned to the required number
        of bytes. */
        if( ( xWantedSize & portBYTE_ALIGNMENT_MASK ) != 0x00 )
        {
          /* Byte alignment required. */
          xWantedSize += ( portBYTE_ALIGNMENT - ( xWantedSize & portBYTE_ALIGNMENT_MASK ) );
          configASSERT( ( xWantedSize & portBYTE_ALIGNMENT_MASK ) == 0 );
        }
        else
        {
          mtCOVERAGE_TEST_MARKER();
        }
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
      if( ( xWantedSize > 0 ) && ( xWantedSize <= xFreeBytesRemaining ) )
      {
        /* Traverse the list from the start (lowest address) block until
        one of adequate size is found. */
        pxPreviousBlock = &xStart;
        pxBlock = xStart.pxNextFreeBlock;
        while( ( pxBlock->xBlockSize < xWantedSize ) && ( pxBlock->pxNextFreeBlock != NULL ) )
        {
          pxPreviousBlock = pxBlock;
          pxBlock = pxBlock->pxNextFreeBlock;
        }
        /* If the end marker was reached then a block of adequate size
        was not found. */
        if( pxBlock != pxEnd )
        {
          /* Return the memory space pointed to - jumping over the
          BlockLink_t structure at its start. */
          pvReturn = ( void * ) ( ( ( uint8_t * ) pxPreviousBlock->pxNextFreeBlock ) + xHeapStructSize );
          /* This block is being returned for use so must be taken out
          of the list of free blocks. */
          pxPreviousBlock->pxNextFreeBlock = pxBlock->pxNextFreeBlock;
          /* If the block is larger than required it can be split into
          two. */
          if( ( pxBlock->xBlockSize - xWantedSize ) > heapMINIMUM_BLOCK_SIZE )
          {
            /* This block is to be split into two.  Create a new
            block following the number of bytes requested. The void
            cast is used to prevent byte alignment warnings from the
            compiler. */
            pxNewBlockLink = ( void * ) ( ( ( uint8_t * ) pxBlock ) + xWantedSize );
            configASSERT( ( ( ( size_t ) pxNewBlockLink ) & portBYTE_ALIGNMENT_MASK ) == 0 );
            /* Calculate the sizes of two blocks split from the
            single block. */
            pxNewBlockLink->xBlockSize = pxBlock->xBlockSize - xWantedSize;
            pxBlock->xBlockSize = xWantedSize;
            /* Insert the new block into the list of free blocks. */
            prvInsertBlockIntoFreeList( pxNewBlockLink );
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
          xFreeBytesRemaining -= pxBlock->xBlockSize;
          if( xFreeBytesRemaining < xMinimumEverFreeBytesRemaining )
          {
            xMinimumEverFreeBytesRemaining = xFreeBytesRemaining;
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
          /* The block is being returned - it is allocated and owned
          by the application and has no "next" block. */
          pxBlock->xBlockSize |= xBlockAllocatedBit;
          pxBlock->pxNextFreeBlock = NULL;
          xNumberOfSuccessfulAllocations++;
        }
        else
        {
          mtCOVERAGE_TEST_MARKER();
        }
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
    traceMALLOC( pvReturn, xWantedSize );
  }
  ( void ) xTaskResumeAll();
  #if( configUSE_MALLOC_FAILED_HOOK == 1 )
  {
    if( pvReturn == NULL )
    {
      extern void vApplicationMallocFailedHook( void );
      vApplicationMallocFailedHook();
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
  }
  #endif
  configASSERT( ( ( ( size_t ) pvReturn ) & ( size_t ) portBYTE_ALIGNMENT_MASK ) == 0 );
  return pvReturn;
}
References configASSERT, heapMINIMUM_BLOCK_SIZE, mtCOVERAGE_TEST_MARKER, portBYTE_ALIGNMENT, prvHeapInit(), prvInsertBlockIntoFreeList(), pxEnd, A_BLOCK_LINK::pxNextFreeBlock, traceMALLOC, vApplicationMallocFailedHook(), vTaskSuspendAll(), xBlockAllocatedBit, A_BLOCK_LINK::xBlockSize, xFreeBytesRemaining, xHeapStructSize, xMinimumEverFreeBytesRemaining, xNumberOfSuccessfulAllocations, xStart, and xTaskResumeAll().
Referenced by osThreadEnumerate().
pxPortInitialiseStack()
StackType_t * pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
vPortDefineHeapRegions()
void vPortDefineHeapRegions (const HeapRegion_t *const pxHeapRegions)
Referenced by osKernelInitialize().
vPortEndScheduler()
void vPortEndScheduler (void)
Definition at line 244 of file port.c.
{
  /* Not implemented in ports where there is nothing to return to.
  Artificially force an assert. */
  configASSERT( uxCriticalNesting == 1000UL );
}
References configASSERT.
Referenced by vTaskEndScheduler().
vPortFree()
void vPortFree (void * pv)
Definition at line 266 of file heap_4.c.
{
uint8_t *puc = (uint8_t *) pv;
BlockLink_t *pxLink;
  if( pv != NULL )
  {
    /* The memory being freed will have an BlockLink_t structure immediately
    before it. */
    puc -= xHeapStructSize;
    /* This casting is to keep the compiler from issuing warnings. */
    pxLink = ( void * ) puc;
    /* Check the block is actually allocated. */
    configASSERT( ( pxLink->xBlockSize & xBlockAllocatedBit ) != 0 );
    configASSERT( pxLink->pxNextFreeBlock == NULL );
    if( ( pxLink->xBlockSize & xBlockAllocatedBit ) != 0 )
    {
      if( pxLink->pxNextFreeBlock == NULL )
      {
        /* The block is being returned to the heap - it is no longer
        allocated. */
        pxLink->xBlockSize &= ~xBlockAllocatedBit;
        vTaskSuspendAll();
        {
          /* Add this block to the list of free blocks. */
          xFreeBytesRemaining += pxLink->xBlockSize;
          traceFREE( pv, pxLink->xBlockSize );
          prvInsertBlockIntoFreeList( ( ( BlockLink_t * ) pxLink ) );
          xNumberOfSuccessfulFrees++;
        }
        ( void ) xTaskResumeAll();
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
  }
}
References configASSERT, mtCOVERAGE_TEST_MARKER, prvInsertBlockIntoFreeList(), A_BLOCK_LINK::pxNextFreeBlock, traceFREE, vTaskSuspendAll(), xBlockAllocatedBit, A_BLOCK_LINK::xBlockSize, xFreeBytesRemaining, xHeapStructSize, xNumberOfSuccessfulFrees, and xTaskResumeAll().
Referenced by osThreadEnumerate(), vEventGroupDelete(), vQueueDelete(), and vStreamBufferDelete().
vPortGetHeapStats()
void vPortGetHeapStats (HeapStats_t * pxHeapStats)
Definition at line 442 of file heap_4.c.
{
BlockLink_t *pxBlock;
size_t xBlocks = 0, xMaxSize = 0, xMinSize = portMAX_DELAY; /* portMAX_DELAY used as a portable way of getting the maximum value. */
  vTaskSuspendAll();
  {
    pxBlock = xStart.pxNextFreeBlock;
    /* pxBlock will be NULL if the heap has not been initialised.  The heap
    is initialised automatically when the first allocation is made. */
    if( pxBlock != NULL )
    {
      do
      {
        /* Increment the number of blocks and record the largest block seen
        so far. */
        xBlocks++;
        if( pxBlock->xBlockSize > xMaxSize )
        {
          xMaxSize = pxBlock->xBlockSize;
        }
        if( pxBlock->xBlockSize < xMinSize )
        {
          xMinSize = pxBlock->xBlockSize;
        }
        /* Move to the next block in the chain until the last block is
        reached. */
        pxBlock = pxBlock->pxNextFreeBlock;
      } while( pxBlock != pxEnd );
    }
  }
  xTaskResumeAll();
  pxHeapStats->xSizeOfLargestFreeBlockInBytes = xMaxSize;
  pxHeapStats->xSizeOfSmallestFreeBlockInBytes = xMinSize;
  pxHeapStats->xNumberOfFreeBlocks = xBlocks;
  taskENTER_CRITICAL();
  {
    pxHeapStats->xAvailableHeapSpaceInBytes = xFreeBytesRemaining;
    pxHeapStats->xNumberOfSuccessfulAllocations = xNumberOfSuccessfulAllocations;
    pxHeapStats->xNumberOfSuccessfulFrees = xNumberOfSuccessfulFrees;
    pxHeapStats->xMinimumEverFreeBytesRemaining = xMinimumEverFreeBytesRemaining;
  }
  taskEXIT_CRITICAL();
}
References portMAX_DELAY, pxEnd, A_BLOCK_LINK::pxNextFreeBlock, taskENTER_CRITICAL, taskEXIT_CRITICAL, vTaskSuspendAll(), xHeapStats::xAvailableHeapSpaceInBytes, A_BLOCK_LINK::xBlockSize, xFreeBytesRemaining, xHeapStats::xMinimumEverFreeBytesRemaining, xMinimumEverFreeBytesRemaining, xHeapStats::xNumberOfFreeBlocks, xHeapStats::xNumberOfSuccessfulAllocations, xNumberOfSuccessfulAllocations, xHeapStats::xNumberOfSuccessfulFrees, xNumberOfSuccessfulFrees, xHeapStats::xSizeOfLargestFreeBlockInBytes, xHeapStats::xSizeOfSmallestFreeBlockInBytes, xStart, and xTaskResumeAll().
vPortInitialiseBlocks()
void vPortInitialiseBlocks (void)
Definition at line 327 of file heap_4.c.
{
  /* This just exists to keep the linker quiet. */
}
xPortGetFreeHeapSize()
size_t xPortGetFreeHeapSize (void)
Definition at line 315 of file heap_4.c.
{
  return xFreeBytesRemaining;
}
References xFreeBytesRemaining.
xPortGetMinimumEverFreeHeapSize()
size_t xPortGetMinimumEverFreeHeapSize (void)
Definition at line 321 of file heap_4.c.
{
  return xMinimumEverFreeBytesRemaining;
}
References xMinimumEverFreeBytesRemaining.
xPortStartScheduler()
BaseType_t xPortStartScheduler (void)
Definition at line 214 of file port.c.
{
  /* Make PendSV, CallSV and SysTick the same priority as the kernel. */
  portNVIC_SYSPRI2_REG |= portNVIC_PENDSV_PRI;
  portNVIC_SYSPRI2_REG |= portNVIC_SYSTICK_PRI;
  /* Start the timer that generates the tick ISR.  Interrupts are disabled
  here already. */
  vPortSetupTimerInterrupt();
  /* Initialise the critical nesting count ready for the first task. */
  uxCriticalNesting = 0;
  /* Start the first task. */
  vPortStartFirstTask();
  /* Should never get here as the tasks will now be executing!  Call the task
  exit error function to prevent compiler warnings about a static function
  not being called in the case that the application writer overrides this
  functionality by defining configTASK_RETURN_ADDRESS.  Call
  vTaskSwitchContext() so link time optimisation does not remove the
  symbol. */
  vTaskSwitchContext();
  prvTaskExitError();
  /* Should not get here! */
  return 0;
}
References portNVIC_PENDSV_PRI, portNVIC_SYSPRI2_REG, portNVIC_SYSTICK_PRI, prvTaskExitError(), vPortSetupTimerInterrupt(), vPortStartFirstTask(), and vTaskSwitchContext().
Referenced by vTaskStartScheduler().