NUCLEO-G0B1RE Examples: NUCLEO-G0B1RE/FreeRTOS_Queues/Middlewares/Third_Party/FreeRTOS/Source/queue.c File Reference
queue.c File Reference
#include <stdlib.h>
#include <string.h>
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
Data Structures
struct QueuePointers
struct SemaphoreData
struct QueueDefinition
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define queueUNLOCKED ((int8_t) -1)
#define queueLOCKED_UNMODIFIED ((int8_t) 0)
#define uxQueueType pcHead
#define queueQUEUE_IS_MUTEX NULL
#define queueSEMAPHORE_QUEUE_ITEM_LENGTH ((UBaseType_t) 0)
#define queueMUTEX_GIVE_BLOCK_TIME ((TickType_t) 0U)
#define queueYIELD_IF_USING_PREEMPTION()
#define prvLockQueue(pxQueue)
Typedefs
typedef struct QueuePointers QueuePointers_t
typedef struct SemaphoreData SemaphoreData_t
typedef struct QueueDefinition xQUEUE
typedef xQUEUE Queue_t
Functions
static void prvUnlockQueue (Queue_t *const pxQueue) PRIVILEGED_FUNCTION
static BaseType_t prvIsQueueEmpty (const Queue_t *pxQueue) PRIVILEGED_FUNCTION
static BaseType_t prvIsQueueFull (const Queue_t *pxQueue) PRIVILEGED_FUNCTION
static BaseType_t prvCopyDataToQueue (Queue_t *const pxQueue, const void *pvItemToQueue, const BaseType_t xPosition) PRIVILEGED_FUNCTION
static void prvCopyDataFromQueue (Queue_t *const pxQueue, void *const pvBuffer) PRIVILEGED_FUNCTION
static void prvInitialiseNewQueue (const UBaseType_t uxQueueLength, const UBaseType_t uxItemSize, uint8_t *pucQueueStorage, const uint8_t ucQueueType, Queue_t *pxNewQueue) PRIVILEGED_FUNCTION
BaseType_t xQueueGenericReset (QueueHandle_t xQueue, BaseType_t xNewQueue)
BaseType_t xQueueGenericSend (QueueHandle_t xQueue, const void *const pvItemToQueue, TickType_t xTicksToWait, const BaseType_t xCopyPosition)
BaseType_t xQueueGenericSendFromISR (QueueHandle_t xQueue, const void *const pvItemToQueue, BaseType_t *const pxHigherPriorityTaskWoken, const BaseType_t xCopyPosition)
BaseType_t xQueueGiveFromISR (QueueHandle_t xQueue, BaseType_t *const pxHigherPriorityTaskWoken)
BaseType_t xQueueReceive (QueueHandle_t xQueue, void *const pvBuffer, TickType_t xTicksToWait)
BaseType_t xQueueSemaphoreTake (QueueHandle_t xQueue, TickType_t xTicksToWait)
BaseType_t xQueuePeek (QueueHandle_t xQueue, void *const pvBuffer, TickType_t xTicksToWait)
BaseType_t xQueueReceiveFromISR (QueueHandle_t xQueue, void *const pvBuffer, BaseType_t *const pxHigherPriorityTaskWoken)
BaseType_t xQueuePeekFromISR (QueueHandle_t xQueue, void *const pvBuffer)
UBaseType_t uxQueueMessagesWaiting (const QueueHandle_t xQueue)
UBaseType_t uxQueueSpacesAvailable (const QueueHandle_t xQueue)
UBaseType_t uxQueueMessagesWaitingFromISR (const QueueHandle_t xQueue)
void vQueueDelete (QueueHandle_t xQueue)
BaseType_t xQueueIsQueueEmptyFromISR (const QueueHandle_t xQueue)
BaseType_t xQueueIsQueueFullFromISR (const QueueHandle_t xQueue)
Macro Definition Documentation
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 34 of file queue.c.
prvLockQueue
#define prvLockQueue (pxQueue)
Value:
  taskENTER_CRITICAL();                 \
  {                           \
    if( ( pxQueue )->cRxLock == queueUNLOCKED )     \
    {                         \
      ( pxQueue )->cRxLock = queueLOCKED_UNMODIFIED;  \
    }                         \
    if( ( pxQueue )->cTxLock == queueUNLOCKED )     \
    {                         \
      ( pxQueue )->cTxLock = queueLOCKED_UNMODIFIED;  \
    }                         \
  }                           \
  taskEXIT_CRITICAL()
Definition at line 240 of file queue.c.
#define prvLockQueue(pxQueue)               \
  taskENTER_CRITICAL();                 \
  {                           \
    if( ( pxQueue )->cRxLock == queueUNLOCKED )     \
    {                         \
      ( pxQueue )->cRxLock = queueLOCKED_UNMODIFIED;  \
    }                         \
    if( ( pxQueue )->cTxLock == queueUNLOCKED )     \
    {                         \
      ( pxQueue )->cTxLock = queueLOCKED_UNMODIFIED;  \
    }                         \
  }                           \
  taskEXIT_CRITICAL()
Referenced by xQueueGenericSend(), xQueuePeek(), xQueueReceive(), and xQueueSemaphoreTake().
queueLOCKED_UNMODIFIED
#define queueLOCKED_UNMODIFIED ((int8_t) 0)
Definition at line 53 of file queue.c.
Referenced by prvUnlockQueue().
queueMUTEX_GIVE_BLOCK_TIME
#define queueMUTEX_GIVE_BLOCK_TIME ((TickType_t) 0U)
Definition at line 82 of file queue.c.
queueQUEUE_IS_MUTEX
#define queueQUEUE_IS_MUTEX NULL
Definition at line 65 of file queue.c.
Referenced by prvCopyDataToQueue(), xQueueGiveFromISR(), and xQueueSemaphoreTake().
queueSEMAPHORE_QUEUE_ITEM_LENGTH
#define queueSEMAPHORE_QUEUE_ITEM_LENGTH ((UBaseType_t) 0)
Definition at line 81 of file queue.c.
queueUNLOCKED
#define queueUNLOCKED ((int8_t) -1)
Definition at line 52 of file queue.c.
Referenced by prvUnlockQueue(), xQueueGenericReset(), xQueueGenericSendFromISR(), xQueueGiveFromISR(), and xQueueReceiveFromISR().
queueYIELD_IF_USING_PREEMPTION
#define queueYIELD_IF_USING_PREEMPTION ()
Definition at line 87 of file queue.c.
Referenced by xQueueGenericReset(), xQueueGenericSend(), xQueuePeek(), xQueueReceive(), and xQueueSemaphoreTake().
uxQueueType
#define uxQueueType pcHead
Definition at line 64 of file queue.c.
Typedef Documentation
Queue_t
typedef xQUEUE Queue_t
Definition at line 135 of file queue.c.
QueuePointers_t
typedef struct QueuePointers QueuePointers_t
SemaphoreData_t
typedef struct SemaphoreData SemaphoreData_t
xQUEUE
typedef struct QueueDefinition xQUEUE
Function Documentation
prvCopyDataFromQueue()
static void prvCopyDataFromQueue (Queue_t *const pxQueue, void *const pvBuffer) static
Definition at line 2153 of file queue.c.
{
  if( pxQueue->uxItemSize != ( UBaseType_t ) 0 )
  {
    pxQueue->u.xQueue.pcReadFrom += pxQueue->uxItemSize; /*lint !e9016 Pointer arithmetic on char types ok, especially in this use case where it is the clearest way of conveying intent. */
    if( pxQueue->u.xQueue.pcReadFrom >= pxQueue->u.xQueue.pcTail ) /*lint !e946 MISRA exception justified as use of the relational operator is the cleanest solutions. */
    {
      pxQueue->u.xQueue.pcReadFrom = pxQueue->pcHead;
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
    ( void ) memcpy( ( void * ) pvBuffer, ( void * ) pxQueue->u.xQueue.pcReadFrom, ( size_t ) pxQueue->uxItemSize ); /*lint !e961 !e418 !e9087 MISRA exception as the casts are only redundant for some ports.  Also previous logic ensures a null pointer can only be passed to memcpy() when the count is 0.  Cast to void required by function signature and safe as no alignment requirement and copy length specified in bytes. */
  }
}
References mtCOVERAGE_TEST_MARKER, QueueDefinition::pcHead, QueuePointers::pcReadFrom, QueuePointers::pcTail, QueueDefinition::u, QueueDefinition::uxItemSize, and QueueDefinition::xQueue.
Referenced by xQueuePeek(), xQueuePeekFromISR(), xQueueReceive(), and xQueueReceiveFromISR().
prvCopyDataToQueue()
static BaseType_t prvCopyDataToQueue (Queue_t *const pxQueue, const void * pvItemToQueue, const BaseType_t xPosition) static
Definition at line 2074 of file queue.c.
{
BaseType_t xReturn = pdFALSE;
UBaseType_t uxMessagesWaiting;
  /* This function is called from a critical section. */
  uxMessagesWaiting = pxQueue->uxMessagesWaiting;
  if( pxQueue->uxItemSize == ( UBaseType_t ) 0 )
  {
    #if ( configUSE_MUTEXES == 1 )
    {
      if( pxQueue->uxQueueType == queueQUEUE_IS_MUTEX )
      {
        /* The mutex is no longer being held. */
        xReturn = xTaskPriorityDisinherit( pxQueue->u.xSemaphore.xMutexHolder );
        pxQueue->u.xSemaphore.xMutexHolder = NULL;
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
    #endif /* configUSE_MUTEXES */
  }
  else if( xPosition == queueSEND_TO_BACK )
  {
    ( void ) memcpy( ( void * ) pxQueue->pcWriteTo, pvItemToQueue, ( size_t ) pxQueue->uxItemSize ); /*lint !e961 !e418 !e9087 MISRA exception as the casts are only redundant for some ports, plus previous logic ensures a null pointer can only be passed to memcpy() if the copy size is 0.  Cast to void required by function signature and safe as no alignment requirement and copy length specified in bytes. */
    pxQueue->pcWriteTo += pxQueue->uxItemSize; /*lint !e9016 Pointer arithmetic on char types ok, especially in this use case where it is the clearest way of conveying intent. */
    if( pxQueue->pcWriteTo >= pxQueue->u.xQueue.pcTail ) /*lint !e946 MISRA exception justified as comparison of pointers is the cleanest solution. */
    {
      pxQueue->pcWriteTo = pxQueue->pcHead;
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
  }
  else
  {
    ( void ) memcpy( ( void * ) pxQueue->u.xQueue.pcReadFrom, pvItemToQueue, ( size_t ) pxQueue->uxItemSize ); /*lint !e961 !e9087 !e418 MISRA exception as the casts are only redundant for some ports.  Cast to void required by function signature and safe as no alignment requirement and copy length specified in bytes.  Assert checks null pointer only used when length is 0. */
    pxQueue->u.xQueue.pcReadFrom -= pxQueue->uxItemSize;
    if( pxQueue->u.xQueue.pcReadFrom < pxQueue->pcHead ) /*lint !e946 MISRA exception justified as comparison of pointers is the cleanest solution. */
    {
      pxQueue->u.xQueue.pcReadFrom = ( pxQueue->u.xQueue.pcTail - pxQueue->uxItemSize );
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
    if( xPosition == queueOVERWRITE )
    {
      if( uxMessagesWaiting > ( UBaseType_t ) 0 )
      {
        /* An item is not being added but overwritten, so subtract
        one from the recorded number of items in the queue so when
        one is added again below the number of recorded items remains
        correct. */
        --uxMessagesWaiting;
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
  }
  pxQueue->uxMessagesWaiting = uxMessagesWaiting + ( UBaseType_t ) 1;
  return xReturn;
}
References mtCOVERAGE_TEST_MARKER, QueueDefinition::pcHead, QueuePointers::pcReadFrom, QueuePointers::pcTail, QueueDefinition::pcWriteTo, pdFALSE, queueOVERWRITE, queueQUEUE_IS_MUTEX, queueSEND_TO_BACK, QueueDefinition::u, QueueDefinition::uxItemSize, QueueDefinition::uxMessagesWaiting, SemaphoreData::xMutexHolder, QueueDefinition::xQueue, QueueDefinition::xSemaphore, and xTaskPriorityDisinherit().
Referenced by xQueueGenericSend(), and xQueueGenericSendFromISR().
prvInitialiseNewQueue()
static void prvInitialiseNewQueue (const UBaseType_t uxQueueLength, const UBaseType_t uxItemSize, uint8_t * pucQueueStorage, const uint8_t ucQueueType, Queue_t * pxNewQueue) static
Definition at line 422 of file queue.c.
{
  /* Remove compiler warnings about unused parameters should
  configUSE_TRACE_FACILITY not be set to 1. */
  ( void ) ucQueueType;
  if( uxItemSize == ( UBaseType_t ) 0 )
  {
    /* No RAM was allocated for the queue storage area, but PC head cannot
    be set to NULL because NULL is used as a key to say the queue is used as
    a mutex.  Therefore just set pcHead to point to the queue as a benign
    value that is known to be within the memory map. */
    pxNewQueue->pcHead = ( int8_t * ) pxNewQueue;
  }
  else
  {
    /* Set the head to the start of the queue storage area. */
    pxNewQueue->pcHead = ( int8_t * ) pucQueueStorage;
  }
  /* Initialise the queue members as described where the queue type is
  defined. */
  pxNewQueue->uxLength = uxQueueLength;
  pxNewQueue->uxItemSize = uxItemSize;
  ( void ) xQueueGenericReset( pxNewQueue, pdTRUE );
  #if ( configUSE_TRACE_FACILITY == 1 )
  {
    pxNewQueue->ucQueueType = ucQueueType;
  }
  #endif /* configUSE_TRACE_FACILITY */
  #if( configUSE_QUEUE_SETS == 1 )
  {
    pxNewQueue->pxQueueSetContainer = NULL;
  }
  #endif /* configUSE_QUEUE_SETS */
  traceQUEUE_CREATE( pxNewQueue );
}
References QueueDefinition::pcHead, pdTRUE, traceQUEUE_CREATE, QueueDefinition::uxItemSize, QueueDefinition::uxLength, and xQueueGenericReset().
prvIsQueueEmpty()
static BaseType_t prvIsQueueEmpty (const Queue_t * pxQueue) static
Definition at line 2291 of file queue.c.
{
BaseType_t xReturn;
  taskENTER_CRITICAL();
  {
    if( pxQueue->uxMessagesWaiting == ( UBaseType_t )  0 )
    {
      xReturn = pdTRUE;
    }
    else
    {
      xReturn = pdFALSE;
    }
  }
  taskEXIT_CRITICAL();
  return xReturn;
}
References pdFALSE, pdTRUE, taskENTER_CRITICAL, taskEXIT_CRITICAL, and QueueDefinition::uxMessagesWaiting.
Referenced by xQueuePeek(), xQueueReceive(), and xQueueSemaphoreTake().
prvIsQueueFull()
static BaseType_t prvIsQueueFull (const Queue_t * pxQueue) static
Definition at line 2331 of file queue.c.
{
BaseType_t xReturn;
  taskENTER_CRITICAL();
  {
    if( pxQueue->uxMessagesWaiting == pxQueue->uxLength )
    {
      xReturn = pdTRUE;
    }
    else
    {
      xReturn = pdFALSE;
    }
  }
  taskEXIT_CRITICAL();
  return xReturn;
}
References pdFALSE, pdTRUE, taskENTER_CRITICAL, taskEXIT_CRITICAL, QueueDefinition::uxLength, and QueueDefinition::uxMessagesWaiting.
Referenced by xQueueGenericSend().
prvUnlockQueue()
static void prvUnlockQueue (Queue_t *const pxQueue) static
Definition at line 2171 of file queue.c.
{
  /* THIS FUNCTION MUST BE CALLED WITH THE SCHEDULER SUSPENDED. */
  /* The lock counts contains the number of extra data items placed or
  removed from the queue while the queue was locked.  When a queue is
  locked items can be added or removed, but the event lists cannot be
  updated. */
  taskENTER_CRITICAL();
  {
    int8_t cTxLock = pxQueue->cTxLock;
    /* See if data was added to the queue while it was locked. */
    while( cTxLock > queueLOCKED_UNMODIFIED )
    {
      /* Data was posted while the queue was locked.  Are any tasks
      blocked waiting for data to become available? */
      #if ( configUSE_QUEUE_SETS == 1 )
      {
        if( pxQueue->pxQueueSetContainer != NULL )
        {
          if( prvNotifyQueueSetContainer( pxQueue ) != pdFALSE )
          {
            /* The queue is a member of a queue set, and posting to
            the queue set caused a higher priority task to unblock.
            A context switch is required. */
            vTaskMissedYield();
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
        }
        else
        {
          /* Tasks that are removed from the event list will get
          added to the pending ready list as the scheduler is still
          suspended. */
          if( listLIST_IS_EMPTY( &( pxQueue->xTasksWaitingToReceive ) ) == pdFALSE )
          {
            if( xTaskRemoveFromEventList( &( pxQueue->xTasksWaitingToReceive ) ) != pdFALSE )
            {
              /* The task waiting has a higher priority so record that a
              context switch is required. */
              vTaskMissedYield();
            }
            else
            {
              mtCOVERAGE_TEST_MARKER();
            }
          }
          else
          {
            break;
          }
        }
      }
      #else /* configUSE_QUEUE_SETS */
      {
        /* Tasks that are removed from the event list will get added to
        the pending ready list as the scheduler is still suspended. */
        if( listLIST_IS_EMPTY( &( pxQueue->xTasksWaitingToReceive ) ) == pdFALSE )
        {
          if( xTaskRemoveFromEventList( &( pxQueue->xTasksWaitingToReceive ) ) != pdFALSE )
          {
            /* The task waiting has a higher priority so record that
            a context switch is required. */
            vTaskMissedYield();
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
        }
        else
        {
          break;
        }
      }
      #endif /* configUSE_QUEUE_SETS */
      --cTxLock;
    }
    pxQueue->cTxLock = queueUNLOCKED;
  }
  taskEXIT_CRITICAL();
  /* Do the same for the Rx lock. */
  taskENTER_CRITICAL();
  {
    int8_t cRxLock = pxQueue->cRxLock;
    while( cRxLock > queueLOCKED_UNMODIFIED )
    {
      if( listLIST_IS_EMPTY( &( pxQueue->xTasksWaitingToSend ) ) == pdFALSE )
      {
        if( xTaskRemoveFromEventList( &( pxQueue->xTasksWaitingToSend ) ) != pdFALSE )
        {
          vTaskMissedYield();
        }
        else
        {
          mtCOVERAGE_TEST_MARKER();
        }
        --cRxLock;
      }
      else
      {
        break;
      }
    }
    pxQueue->cRxLock = queueUNLOCKED;
  }
  taskEXIT_CRITICAL();
}
References QueueDefinition::cRxLock, QueueDefinition::cTxLock, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, queueLOCKED_UNMODIFIED, queueUNLOCKED, taskENTER_CRITICAL, taskEXIT_CRITICAL, vTaskMissedYield(), xTaskRemoveFromEventList(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTasksWaitingToSend.
Referenced by xQueueGenericSend(), xQueuePeek(), xQueueReceive(), and xQueueSemaphoreTake().
uxQueueMessagesWaiting()
UBaseType_t uxQueueMessagesWaiting (const QueueHandle_t xQueue)
Definition at line 1930 of file queue.c.
{
UBaseType_t uxReturn;
  configASSERT( xQueue );
  taskENTER_CRITICAL();
  {
    uxReturn = ( ( Queue_t * ) xQueue )->uxMessagesWaiting;
  }
  taskEXIT_CRITICAL();
  return uxReturn;
} /*lint !e818 Pointer cannot be declared const as xQueue is a typedef not pointer. */
References configASSERT, taskENTER_CRITICAL, and taskEXIT_CRITICAL.
Referenced by osMessageQueueGetCount().
uxQueueMessagesWaitingFromISR()
UBaseType_t uxQueueMessagesWaitingFromISR (const QueueHandle_t xQueue)
Definition at line 1963 of file queue.c.
{
UBaseType_t uxReturn;
Queue_t * const pxQueue = xQueue;
  configASSERT( pxQueue );
  uxReturn = pxQueue->uxMessagesWaiting;
  return uxReturn;
} /*lint !e818 Pointer cannot be declared const as xQueue is a typedef not pointer. */
References configASSERT, and QueueDefinition::uxMessagesWaiting.
Referenced by osMessageQueueGetCount(), and osSemaphoreGetCount().
uxQueueSpacesAvailable()
UBaseType_t uxQueueSpacesAvailable (const QueueHandle_t xQueue)
Definition at line 1946 of file queue.c.
{
UBaseType_t uxReturn;
Queue_t * const pxQueue = xQueue;
  configASSERT( pxQueue );
  taskENTER_CRITICAL();
  {
    uxReturn = pxQueue->uxLength - pxQueue->uxMessagesWaiting;
  }
  taskEXIT_CRITICAL();
  return uxReturn;
} /*lint !e818 Pointer cannot be declared const as xQueue is a typedef not pointer. */
References configASSERT, taskENTER_CRITICAL, taskEXIT_CRITICAL, QueueDefinition::uxLength, and QueueDefinition::uxMessagesWaiting.
Referenced by osMessageQueueGetSpace().
vQueueDelete()
void vQueueDelete (QueueHandle_t xQueue)
Definition at line 1975 of file queue.c.
{
Queue_t * const pxQueue = xQueue;
  configASSERT( pxQueue );
  traceQUEUE_DELETE( pxQueue );
  #if ( configQUEUE_REGISTRY_SIZE > 0 )
  {
    vQueueUnregisterQueue( pxQueue );
  }
  #endif
  #if( ( configSUPPORT_DYNAMIC_ALLOCATION == 1 ) && ( configSUPPORT_STATIC_ALLOCATION == 0 ) )
  {
    /* The queue can only have been allocated dynamically - free it
    again. */
    vPortFree( pxQueue );
  }
  #elif( ( configSUPPORT_DYNAMIC_ALLOCATION == 1 ) && ( configSUPPORT_STATIC_ALLOCATION == 1 ) )
  {
    /* The queue could have been allocated statically or dynamically, so
    check before attempting to free the memory. */
    if( pxQueue->ucStaticallyAllocated == ( uint8_t ) pdFALSE )
    {
      vPortFree( pxQueue );
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
  }
  #else
  {
    /* The queue must have been statically allocated, so is not going to be
    deleted.  Avoid compiler warnings about the unused parameter. */
    ( void ) pxQueue;
  }
  #endif /* configSUPPORT_DYNAMIC_ALLOCATION */
}
References configASSERT, mtCOVERAGE_TEST_MARKER, pdFALSE, traceQUEUE_DELETE, vPortFree(), and vQueueUnregisterQueue.
Referenced by osMessageQueueDelete().
xQueueGenericReset()
BaseType_t xQueueGenericReset (QueueHandle_t xQueue, BaseType_t xNewQueue)
Definition at line 255 of file queue.c.
{
Queue_t * const pxQueue = xQueue;
  configASSERT( pxQueue );
  taskENTER_CRITICAL();
  {
    pxQueue->u.xQueue.pcTail = pxQueue->pcHead + ( pxQueue->uxLength * pxQueue->uxItemSize ); /*lint !e9016 Pointer arithmetic allowed on char types, especially when it assists conveying intent. */
    pxQueue->uxMessagesWaiting = ( UBaseType_t ) 0U;
    pxQueue->pcWriteTo = pxQueue->pcHead;
    pxQueue->u.xQueue.pcReadFrom = pxQueue->pcHead + ( ( pxQueue->uxLength - 1U ) * pxQueue->uxItemSize ); /*lint !e9016 Pointer arithmetic allowed on char types, especially when it assists conveying intent. */
    pxQueue->cRxLock = queueUNLOCKED;
    pxQueue->cTxLock = queueUNLOCKED;
    if( xNewQueue == pdFALSE )
    {
      /* If there are tasks blocked waiting to read from the queue, then
      the tasks will remain blocked as after this function exits the queue
      will still be empty.  If there are tasks blocked waiting to write to
      the queue, then one should be unblocked as after this function exits
      it will be possible to write to it. */
      if( listLIST_IS_EMPTY( &( pxQueue->xTasksWaitingToSend ) ) == pdFALSE )
      {
        if( xTaskRemoveFromEventList( &( pxQueue->xTasksWaitingToSend ) ) != pdFALSE )
        {
          queueYIELD_IF_USING_PREEMPTION();
        }
        else
        {
          mtCOVERAGE_TEST_MARKER();
        }
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
    else
    {
      /* Ensure the event queues start in the correct state. */
      vListInitialise( &( pxQueue->xTasksWaitingToSend ) );
      vListInitialise( &( pxQueue->xTasksWaitingToReceive ) );
    }
  }
  taskEXIT_CRITICAL();
  /* A value is returned for calling semantic consistency with previous
  versions. */
  return pdPASS;
}
References configASSERT, QueueDefinition::cRxLock, QueueDefinition::cTxLock, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, QueueDefinition::pcHead, QueuePointers::pcReadFrom, QueuePointers::pcTail, QueueDefinition::pcWriteTo, pdFALSE, pdPASS, queueUNLOCKED, queueYIELD_IF_USING_PREEMPTION, taskENTER_CRITICAL, taskEXIT_CRITICAL, QueueDefinition::u, QueueDefinition::uxItemSize, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, vListInitialise(), QueueDefinition::xQueue, xTaskRemoveFromEventList(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTasksWaitingToSend.
Referenced by prvInitialiseNewQueue().
xQueueGenericSend()
BaseType_t xQueueGenericSend (QueueHandle_t xQueue, const void *const pvItemToQueue, TickType_t xTicksToWait, const BaseType_t xCopyPosition)
Definition at line 740 of file queue.c.
{
BaseType_t xEntryTimeSet = pdFALSE, xYieldRequired;
TimeOut_t xTimeOut;
Queue_t * const pxQueue = xQueue;
  configASSERT( pxQueue );
  configASSERT( !( ( pvItemToQueue == NULL ) && ( pxQueue->uxItemSize != ( UBaseType_t ) 0U ) ) );
  configASSERT( !( ( xCopyPosition == queueOVERWRITE ) && ( pxQueue->uxLength != 1 ) ) );
  #if ( ( INCLUDE_xTaskGetSchedulerState == 1 ) || ( configUSE_TIMERS == 1 ) )
  {
    configASSERT( !( ( xTaskGetSchedulerState() == taskSCHEDULER_SUSPENDED ) && ( xTicksToWait != 0 ) ) );
  }
  #endif
  /*lint -save -e904 This function relaxes the coding standard somewhat to
  allow return statements within the function itself.  This is done in the
  interest of execution time efficiency. */
  for( ;; )
  {
    taskENTER_CRITICAL();
    {
      /* Is there room on the queue now?  The running task must be the
      highest priority task wanting to access the queue.  If the head item
      in the queue is to be overwritten then it does not matter if the
      queue is full. */
      if( ( pxQueue->uxMessagesWaiting < pxQueue->uxLength ) || ( xCopyPosition == queueOVERWRITE ) )
      {
        traceQUEUE_SEND( pxQueue );
        #if ( configUSE_QUEUE_SETS == 1 )
        {
        const UBaseType_t uxPreviousMessagesWaiting = pxQueue->uxMessagesWaiting;
          xYieldRequired = prvCopyDataToQueue( pxQueue, pvItemToQueue, xCopyPosition );
          if( pxQueue->pxQueueSetContainer != NULL )
          {
            if( ( xCopyPosition == queueOVERWRITE ) && ( uxPreviousMessagesWaiting != ( UBaseType_t ) 0 ) )
            {
              /* Do not notify the queue set as an existing item
              was overwritten in the queue so the number of items
              in the queue has not changed. */
              mtCOVERAGE_TEST_MARKER();
            }
            else if( prvNotifyQueueSetContainer( pxQueue ) != pdFALSE )
            {
              /* The queue is a member of a queue set, and posting
              to the queue set caused a higher priority task to
              unblock. A context switch is required. */
              queueYIELD_IF_USING_PREEMPTION();
            }
            else
            {
              mtCOVERAGE_TEST_MARKER();
            }
          }
          else
          {
            /* If there was a task waiting for data to arrive on the
            queue then unblock it now. */
            if( listLIST_IS_EMPTY( &( pxQueue->xTasksWaitingToReceive ) ) == pdFALSE )
            {
              if( xTaskRemoveFromEventList( &( pxQueue->xTasksWaitingToReceive ) ) != pdFALSE )
              {
                /* The unblocked task has a priority higher than
                our own so yield immediately.  Yes it is ok to
                do this from within the critical section - the
                kernel takes care of that. */
                queueYIELD_IF_USING_PREEMPTION();
              }
              else
              {
                mtCOVERAGE_TEST_MARKER();
              }
            }
            else if( xYieldRequired != pdFALSE )
            {
              /* This path is a special case that will only get
              executed if the task was holding multiple mutexes
              and the mutexes were given back in an order that is
              different to that in which they were taken. */
              queueYIELD_IF_USING_PREEMPTION();
            }
            else
            {
              mtCOVERAGE_TEST_MARKER();
            }
          }
        }
        #else /* configUSE_QUEUE_SETS */
        {
          xYieldRequired = prvCopyDataToQueue( pxQueue, pvItemToQueue, xCopyPosition );
          /* If there was a task waiting for data to arrive on the
          queue then unblock it now. */
          if( listLIST_IS_EMPTY( &( pxQueue->xTasksWaitingToReceive ) ) == pdFALSE )
          {
            if( xTaskRemoveFromEventList( &( pxQueue->xTasksWaitingToReceive ) ) != pdFALSE )
            {
              /* The unblocked task has a priority higher than
              our own so yield immediately.  Yes it is ok to do
              this from within the critical section - the kernel
              takes care of that. */
              queueYIELD_IF_USING_PREEMPTION();
            }
            else
            {
              mtCOVERAGE_TEST_MARKER();
            }
          }
          else if( xYieldRequired != pdFALSE )
          {
            /* This path is a special case that will only get
            executed if the task was holding multiple mutexes and
            the mutexes were given back in an order that is
            different to that in which they were taken. */
            queueYIELD_IF_USING_PREEMPTION();
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
        }
        #endif /* configUSE_QUEUE_SETS */
        taskEXIT_CRITICAL();
        return pdPASS;
      }
      else
      {
        if( xTicksToWait == ( TickType_t ) 0 )
        {
          /* The queue was full and no block time is specified (or
          the block time has expired) so leave now. */
          taskEXIT_CRITICAL();
          /* Return to the original privilege level before exiting
          the function. */
          traceQUEUE_SEND_FAILED( pxQueue );
          return errQUEUE_FULL;
        }
        else if( xEntryTimeSet == pdFALSE )
        {
          /* The queue was full and a block time was specified so
          configure the timeout structure. */
          vTaskInternalSetTimeOutState( &xTimeOut );
          xEntryTimeSet = pdTRUE;
        }
        else
        {
          /* Entry time was already set. */
          mtCOVERAGE_TEST_MARKER();
        }
      }
    }
    taskEXIT_CRITICAL();
    /* Interrupts and other tasks can send to and receive from the queue
    now the critical section has been exited. */
    vTaskSuspendAll();
    prvLockQueue( pxQueue );
    /* Update the timeout state to see if it has expired yet. */
    if( xTaskCheckForTimeOut( &xTimeOut, &xTicksToWait ) == pdFALSE )
    {
      if( prvIsQueueFull( pxQueue ) != pdFALSE )
      {
        traceBLOCKING_ON_QUEUE_SEND( pxQueue );
        vTaskPlaceOnEventList( &( pxQueue->xTasksWaitingToSend ), xTicksToWait );
        /* Unlocking the queue means queue events can effect the
        event list.  It is possible that interrupts occurring now
        remove this task from the event list again - but as the
        scheduler is suspended the task will go onto the pending
        ready last instead of the actual ready list. */
        prvUnlockQueue( pxQueue );
        /* Resuming the scheduler will move tasks from the pending
        ready list into the ready list - so it is feasible that this
        task is already in a ready list before it yields - in which
        case the yield will not cause a context switch unless there
        is also a higher priority task in the pending ready list. */
        if( xTaskResumeAll() == pdFALSE )
        {
          portYIELD_WITHIN_API();
        }
      }
      else
      {
        /* Try again. */
        prvUnlockQueue( pxQueue );
        ( void ) xTaskResumeAll();
      }
    }
    else
    {
      /* The timeout has expired. */
      prvUnlockQueue( pxQueue );
      ( void ) xTaskResumeAll();
      traceQUEUE_SEND_FAILED( pxQueue );
      return errQUEUE_FULL;
    }
  } /*lint -restore */
}
References configASSERT, errQUEUE_FULL, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdPASS, pdTRUE, portYIELD_WITHIN_API, prvCopyDataToQueue(), prvIsQueueFull(), prvLockQueue, prvUnlockQueue(), queueOVERWRITE, queueYIELD_IF_USING_PREEMPTION, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSCHEDULER_SUSPENDED, traceBLOCKING_ON_QUEUE_SEND, traceQUEUE_SEND, traceQUEUE_SEND_FAILED, QueueDefinition::uxItemSize, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, vTaskInternalSetTimeOutState(), vTaskPlaceOnEventList(), vTaskSuspendAll(), xTaskCheckForTimeOut(), xTaskGetSchedulerState(), xTaskRemoveFromEventList(), xTaskResumeAll(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTasksWaitingToSend.
xQueueGenericSendFromISR()
BaseType_t xQueueGenericSendFromISR (QueueHandle_t xQueue, const void *const pvItemToQueue, BaseType_t *const pxHigherPriorityTaskWoken, const BaseType_t xCopyPosition)
Definition at line 950 of file queue.c.
{
BaseType_t xReturn;
UBaseType_t uxSavedInterruptStatus;
Queue_t * const pxQueue = xQueue;
  configASSERT( pxQueue );
  configASSERT( !( ( pvItemToQueue == NULL ) && ( pxQueue->uxItemSize != ( UBaseType_t ) 0U ) ) );
  configASSERT( !( ( xCopyPosition == queueOVERWRITE ) && ( pxQueue->uxLength != 1 ) ) );
  /* RTOS ports that support interrupt nesting have the concept of a maximum
  system call (or maximum API call) interrupt priority.  Interrupts that are
  above the maximum system call priority are kept permanently enabled, even
  when the RTOS kernel is in a critical section, but cannot make any calls to
  FreeRTOS API functions.  If configASSERT() is defined in FreeRTOSConfig.h
  then portASSERT_IF_INTERRUPT_PRIORITY_INVALID() will result in an assertion
  failure if a FreeRTOS API function is called from an interrupt that has been
  assigned a priority above the configured maximum system call priority.
  Only FreeRTOS functions that end in FromISR can be called from interrupts
  that have been assigned a priority at or (logically) below the maximum
  system call interrupt priority.  FreeRTOS maintains a separate interrupt
  safe API to ensure interrupt entry is as fast and as simple as possible.
  More information (albeit Cortex-M specific) is provided on the following
  link: http://www.freertos.org/RTOS-Cortex-M3-M4.html */
  portASSERT_IF_INTERRUPT_PRIORITY_INVALID();
  /* Similar to xQueueGenericSend, except without blocking if there is no room
  in the queue.  Also don't directly wake a task that was blocked on a queue
  read, instead return a flag to say whether a context switch is required or
  not (i.e. has a task with a higher priority than us been woken by this
  post). */
  uxSavedInterruptStatus = portSET_INTERRUPT_MASK_FROM_ISR();
  {
    if( ( pxQueue->uxMessagesWaiting < pxQueue->uxLength ) || ( xCopyPosition == queueOVERWRITE ) )
    {
      const int8_t cTxLock = pxQueue->cTxLock;
      const UBaseType_t uxPreviousMessagesWaiting = pxQueue->uxMessagesWaiting;
      traceQUEUE_SEND_FROM_ISR( pxQueue );
      /* Semaphores use xQueueGiveFromISR(), so pxQueue will not be a
      semaphore or mutex.  That means prvCopyDataToQueue() cannot result
      in a task disinheriting a priority and prvCopyDataToQueue() can be
      called here even though the disinherit function does not check if
      the scheduler is suspended before accessing the ready lists. */
      ( void ) prvCopyDataToQueue( pxQueue, pvItemToQueue, xCopyPosition );
      /* The event list is not altered if the queue is locked.  This will
      be done when the queue is unlocked later. */
      if( cTxLock == queueUNLOCKED )
      {
        #if ( configUSE_QUEUE_SETS == 1 )
        {
          if( pxQueue->pxQueueSetContainer != NULL )
          {
            if( ( xCopyPosition == queueOVERWRITE ) && ( uxPreviousMessagesWaiting != ( UBaseType_t ) 0 ) )
            {
              /* Do not notify the queue set as an existing item
              was overwritten in the queue so the number of items
              in the queue has not changed. */
              mtCOVERAGE_TEST_MARKER();
            }
            else if( prvNotifyQueueSetContainer( pxQueue ) != pdFALSE )
            {
              /* The queue is a member of a queue set, and posting
              to the queue set caused a higher priority task to
              unblock.  A context switch is required. */
              if( pxHigherPriorityTaskWoken != NULL )
              {
                *pxHigherPriorityTaskWoken = pdTRUE;
              }
              else
              {
                mtCOVERAGE_TEST_MARKER();
              }
            }
            else
            {
              mtCOVERAGE_TEST_MARKER();
            }
          }
          else
          {
            if( listLIST_IS_EMPTY( &( pxQueue->xTasksWaitingToReceive ) ) == pdFALSE )
            {
              if( xTaskRemoveFromEventList( &( pxQueue->xTasksWaitingToReceive ) ) != pdFALSE )
              {
                /* The task waiting has a higher priority so
                record that a context switch is required. */
                if( pxHigherPriorityTaskWoken != NULL )
                {
                  *pxHigherPriorityTaskWoken = pdTRUE;
                }
                else
                {
                  mtCOVERAGE_TEST_MARKER();
                }
              }
              else
              {
                mtCOVERAGE_TEST_MARKER();
              }
            }
            else
            {
              mtCOVERAGE_TEST_MARKER();
            }
          }
        }
        #else /* configUSE_QUEUE_SETS */
        {
          if( listLIST_IS_EMPTY( &( pxQueue->xTasksWaitingToReceive ) ) == pdFALSE )
          {
            if( xTaskRemoveFromEventList( &( pxQueue->xTasksWaitingToReceive ) ) != pdFALSE )
            {
              /* The task waiting has a higher priority so record that a
              context switch is required. */
              if( pxHigherPriorityTaskWoken != NULL )
              {
                *pxHigherPriorityTaskWoken = pdTRUE;
              }
              else
              {
                mtCOVERAGE_TEST_MARKER();
              }
            }
            else
            {
              mtCOVERAGE_TEST_MARKER();
            }
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
          /* Not used in this path. */
          ( void ) uxPreviousMessagesWaiting;
        }
        #endif /* configUSE_QUEUE_SETS */
      }
      else
      {
        /* Increment the lock count so the task that unlocks the queue
        knows that data was posted while it was locked. */
        pxQueue->cTxLock = ( int8_t ) ( cTxLock + 1 );
      }
      xReturn = pdPASS;
    }
    else
    {
      traceQUEUE_SEND_FROM_ISR_FAILED( pxQueue );
      xReturn = errQUEUE_FULL;
    }
  }
  portCLEAR_INTERRUPT_MASK_FROM_ISR( uxSavedInterruptStatus );
  return xReturn;
}
References configASSERT, QueueDefinition::cTxLock, errQUEUE_FULL, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdPASS, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvCopyDataToQueue(), queueOVERWRITE, queueUNLOCKED, traceQUEUE_SEND_FROM_ISR, traceQUEUE_SEND_FROM_ISR_FAILED, QueueDefinition::uxItemSize, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, xTaskRemoveFromEventList(), and QueueDefinition::xTasksWaitingToReceive.
xQueueGiveFromISR()
BaseType_t xQueueGiveFromISR (QueueHandle_t xQueue, BaseType_t *const pxHigherPriorityTaskWoken)
Definition at line 1112 of file queue.c.
{
BaseType_t xReturn;
UBaseType_t uxSavedInterruptStatus;
Queue_t * const pxQueue = xQueue;
  /* Similar to xQueueGenericSendFromISR() but used with semaphores where the
  item size is 0.  Don't directly wake a task that was blocked on a queue
  read, instead return a flag to say whether a context switch is required or
  not (i.e. has a task with a higher priority than us been woken by this
  post). */
  configASSERT( pxQueue );
  /* xQueueGenericSendFromISR() should be used instead of xQueueGiveFromISR()
  if the item size is not 0. */
  configASSERT( pxQueue->uxItemSize == 0 );
  /* Normally a mutex would not be given from an interrupt, especially if
  there is a mutex holder, as priority inheritance makes no sense for an
  interrupts, only tasks. */
  configASSERT( !( ( pxQueue->uxQueueType == queueQUEUE_IS_MUTEX ) && ( pxQueue->u.xSemaphore.xMutexHolder != NULL ) ) );
  /* RTOS ports that support interrupt nesting have the concept of a maximum
  system call (or maximum API call) interrupt priority.  Interrupts that are
  above the maximum system call priority are kept permanently enabled, even
  when the RTOS kernel is in a critical section, but cannot make any calls to
  FreeRTOS API functions.  If configASSERT() is defined in FreeRTOSConfig.h
  then portASSERT_IF_INTERRUPT_PRIORITY_INVALID() will result in an assertion
  failure if a FreeRTOS API function is called from an interrupt that has been
  assigned a priority above the configured maximum system call priority.
  Only FreeRTOS functions that end in FromISR can be called from interrupts
  that have been assigned a priority at or (logically) below the maximum
  system call interrupt priority.  FreeRTOS maintains a separate interrupt
  safe API to ensure interrupt entry is as fast and as simple as possible.
  More information (albeit Cortex-M specific) is provided on the following
  link: http://www.freertos.org/RTOS-Cortex-M3-M4.html */
  portASSERT_IF_INTERRUPT_PRIORITY_INVALID();
  uxSavedInterruptStatus = portSET_INTERRUPT_MASK_FROM_ISR();
  {
    const UBaseType_t uxMessagesWaiting = pxQueue->uxMessagesWaiting;
    /* When the queue is used to implement a semaphore no data is ever
    moved through the queue but it is still valid to see if the queue 'has
    space'. */
    if( uxMessagesWaiting < pxQueue->uxLength )
    {
      const int8_t cTxLock = pxQueue->cTxLock;
      traceQUEUE_SEND_FROM_ISR( pxQueue );
      /* A task can only have an inherited priority if it is a mutex
      holder - and if there is a mutex holder then the mutex cannot be
      given from an ISR.  As this is the ISR version of the function it
      can be assumed there is no mutex holder and no need to determine if
      priority disinheritance is needed.  Simply increase the count of
      messages (semaphores) available. */
      pxQueue->uxMessagesWaiting = uxMessagesWaiting + ( UBaseType_t ) 1;
      /* The event list is not altered if the queue is locked.  This will
      be done when the queue is unlocked later. */
      if( cTxLock == queueUNLOCKED )
      {
        #if ( configUSE_QUEUE_SETS == 1 )
        {
          if( pxQueue->pxQueueSetContainer != NULL )
          {
            if( prvNotifyQueueSetContainer( pxQueue ) != pdFALSE )
            {
              /* The semaphore is a member of a queue set, and
              posting to the queue set caused a higher priority
              task to unblock.  A context switch is required. */
              if( pxHigherPriorityTaskWoken != NULL )
              {
                *pxHigherPriorityTaskWoken = pdTRUE;
              }
              else
              {
                mtCOVERAGE_TEST_MARKER();
              }
            }
            else
            {
              mtCOVERAGE_TEST_MARKER();
            }
          }
          else
          {
            if( listLIST_IS_EMPTY( &( pxQueue->xTasksWaitingToReceive ) ) == pdFALSE )
            {
              if( xTaskRemoveFromEventList( &( pxQueue->xTasksWaitingToReceive ) ) != pdFALSE )
              {
                /* The task waiting has a higher priority so
                record that a context switch is required. */
                if( pxHigherPriorityTaskWoken != NULL )
                {
                  *pxHigherPriorityTaskWoken = pdTRUE;
                }
                else
                {
                  mtCOVERAGE_TEST_MARKER();
                }
              }
              else
              {
                mtCOVERAGE_TEST_MARKER();
              }
            }
            else
            {
              mtCOVERAGE_TEST_MARKER();
            }
          }
        }
        #else /* configUSE_QUEUE_SETS */
        {
          if( listLIST_IS_EMPTY( &( pxQueue->xTasksWaitingToReceive ) ) == pdFALSE )
          {
            if( xTaskRemoveFromEventList( &( pxQueue->xTasksWaitingToReceive ) ) != pdFALSE )
            {
              /* The task waiting has a higher priority so record that a
              context switch is required. */
              if( pxHigherPriorityTaskWoken != NULL )
              {
                *pxHigherPriorityTaskWoken = pdTRUE;
              }
              else
              {
                mtCOVERAGE_TEST_MARKER();
              }
            }
            else
            {
              mtCOVERAGE_TEST_MARKER();
            }
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
        }
        #endif /* configUSE_QUEUE_SETS */
      }
      else
      {
        /* Increment the lock count so the task that unlocks the queue
        knows that data was posted while it was locked. */
        pxQueue->cTxLock = ( int8_t ) ( cTxLock + 1 );
      }
      xReturn = pdPASS;
    }
    else
    {
      traceQUEUE_SEND_FROM_ISR_FAILED( pxQueue );
      xReturn = errQUEUE_FULL;
    }
  }
  portCLEAR_INTERRUPT_MASK_FROM_ISR( uxSavedInterruptStatus );
  return xReturn;
}
References configASSERT, QueueDefinition::cTxLock, errQUEUE_FULL, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdPASS, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, queueQUEUE_IS_MUTEX, queueUNLOCKED, traceQUEUE_SEND_FROM_ISR, traceQUEUE_SEND_FROM_ISR_FAILED, QueueDefinition::u, QueueDefinition::uxItemSize, QueueDefinition::uxMessagesWaiting, SemaphoreData::xMutexHolder, QueueDefinition::xSemaphore, xTaskRemoveFromEventList(), and QueueDefinition::xTasksWaitingToReceive.
xQueueIsQueueEmptyFromISR()
BaseType_t xQueueIsQueueEmptyFromISR (const QueueHandle_t xQueue)
Definition at line 2312 of file queue.c.
{
BaseType_t xReturn;
Queue_t * const pxQueue = xQueue;
  configASSERT( pxQueue );
  if( pxQueue->uxMessagesWaiting == ( UBaseType_t ) 0 )
  {
    xReturn = pdTRUE;
  }
  else
  {
    xReturn = pdFALSE;
  }
  return xReturn;
} /*lint !e818 xQueue could not be pointer to const because it is a typedef. */
References configASSERT, pdFALSE, pdTRUE, and QueueDefinition::uxMessagesWaiting.
xQueueIsQueueFullFromISR()
BaseType_t xQueueIsQueueFullFromISR (const QueueHandle_t xQueue)
Definition at line 2352 of file queue.c.
{
BaseType_t xReturn;
Queue_t * const pxQueue = xQueue;
  configASSERT( pxQueue );
  if( pxQueue->uxMessagesWaiting == pxQueue->uxLength )
  {
    xReturn = pdTRUE;
  }
  else
  {
    xReturn = pdFALSE;
  }
  return xReturn;
} /*lint !e818 xQueue could not be pointer to const because it is a typedef. */
References configASSERT, pdFALSE, pdTRUE, QueueDefinition::uxLength, and QueueDefinition::uxMessagesWaiting.
xQueuePeek()
BaseType_t xQueuePeek (QueueHandle_t xQueue, void *const pvBuffer, TickType_t xTicksToWait)
Definition at line 1636 of file queue.c.
{
BaseType_t xEntryTimeSet = pdFALSE;
TimeOut_t xTimeOut;
int8_t *pcOriginalReadPosition;
Queue_t * const pxQueue = xQueue;
  /* Check the pointer is not NULL. */
  configASSERT( ( pxQueue ) );
  /* The buffer into which data is received can only be NULL if the data size
  is zero (so no data is copied into the buffer. */
  configASSERT( !( ( ( pvBuffer ) == NULL ) && ( ( pxQueue )->uxItemSize != ( UBaseType_t ) 0U ) ) );
  /* Cannot block if the scheduler is suspended. */
  #if ( ( INCLUDE_xTaskGetSchedulerState == 1 ) || ( configUSE_TIMERS == 1 ) )
  {
    configASSERT( !( ( xTaskGetSchedulerState() == taskSCHEDULER_SUSPENDED ) && ( xTicksToWait != 0 ) ) );
  }
  #endif
  /*lint -save -e904  This function relaxes the coding standard somewhat to
  allow return statements within the function itself.  This is done in the
  interest of execution time efficiency. */
  for( ;; )
  {
    taskENTER_CRITICAL();
    {
      const UBaseType_t uxMessagesWaiting = pxQueue->uxMessagesWaiting;
      /* Is there data in the queue now?  To be running the calling task
      must be the highest priority task wanting to access the queue. */
      if( uxMessagesWaiting > ( UBaseType_t ) 0 )
      {
        /* Remember the read position so it can be reset after the data
        is read from the queue as this function is only peeking the
        data, not removing it. */
        pcOriginalReadPosition = pxQueue->u.xQueue.pcReadFrom;
        prvCopyDataFromQueue( pxQueue, pvBuffer );
        traceQUEUE_PEEK( pxQueue );
        /* The data is not being removed, so reset the read pointer. */
        pxQueue->u.xQueue.pcReadFrom = pcOriginalReadPosition;
        /* The data is being left in the queue, so see if there are
        any other tasks waiting for the data. */
        if( listLIST_IS_EMPTY( &( pxQueue->xTasksWaitingToReceive ) ) == pdFALSE )
        {
          if( xTaskRemoveFromEventList( &( pxQueue->xTasksWaitingToReceive ) ) != pdFALSE )
          {
            /* The task waiting has a higher priority than this task. */
            queueYIELD_IF_USING_PREEMPTION();
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
        }
        else
        {
          mtCOVERAGE_TEST_MARKER();
        }
        taskEXIT_CRITICAL();
        return pdPASS;
      }
      else
      {
        if( xTicksToWait == ( TickType_t ) 0 )
        {
          /* The queue was empty and no block time is specified (or
          the block time has expired) so leave now. */
          taskEXIT_CRITICAL();
          traceQUEUE_PEEK_FAILED( pxQueue );
          return errQUEUE_EMPTY;
        }
        else if( xEntryTimeSet == pdFALSE )
        {
          /* The queue was empty and a block time was specified so
          configure the timeout structure ready to enter the blocked
          state. */
          vTaskInternalSetTimeOutState( &xTimeOut );
          xEntryTimeSet = pdTRUE;
        }
        else
        {
          /* Entry time was already set. */
          mtCOVERAGE_TEST_MARKER();
        }
      }
    }
    taskEXIT_CRITICAL();
    /* Interrupts and other tasks can send to and receive from the queue
    now the critical section has been exited. */
    vTaskSuspendAll();
    prvLockQueue( pxQueue );
    /* Update the timeout state to see if it has expired yet. */
    if( xTaskCheckForTimeOut( &xTimeOut, &xTicksToWait ) == pdFALSE )
    {
      /* Timeout has not expired yet, check to see if there is data in the
      queue now, and if not enter the Blocked state to wait for data. */
      if( prvIsQueueEmpty( pxQueue ) != pdFALSE )
      {
        traceBLOCKING_ON_QUEUE_PEEK( pxQueue );
        vTaskPlaceOnEventList( &( pxQueue->xTasksWaitingToReceive ), xTicksToWait );
        prvUnlockQueue( pxQueue );
        if( xTaskResumeAll() == pdFALSE )
        {
          portYIELD_WITHIN_API();
        }
        else
        {
          mtCOVERAGE_TEST_MARKER();
        }
      }
      else
      {
        /* There is data in the queue now, so don't enter the blocked
        state, instead return to try and obtain the data. */
        prvUnlockQueue( pxQueue );
        ( void ) xTaskResumeAll();
      }
    }
    else
    {
      /* The timeout has expired.  If there is still no data in the queue
      exit, otherwise go back and try to read the data again. */
      prvUnlockQueue( pxQueue );
      ( void ) xTaskResumeAll();
      if( prvIsQueueEmpty( pxQueue ) != pdFALSE )
      {
        traceQUEUE_PEEK_FAILED( pxQueue );
        return errQUEUE_EMPTY;
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
  } /*lint -restore */
}
References configASSERT, errQUEUE_EMPTY, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, QueuePointers::pcReadFrom, pdFALSE, pdPASS, pdTRUE, portYIELD_WITHIN_API, prvCopyDataFromQueue(), prvIsQueueEmpty(), prvLockQueue, prvUnlockQueue(), queueYIELD_IF_USING_PREEMPTION, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSCHEDULER_SUSPENDED, traceBLOCKING_ON_QUEUE_PEEK, traceQUEUE_PEEK, traceQUEUE_PEEK_FAILED, QueueDefinition::u, QueueDefinition::uxMessagesWaiting, vTaskInternalSetTimeOutState(), vTaskPlaceOnEventList(), vTaskSuspendAll(), QueueDefinition::xQueue, xTaskCheckForTimeOut(), xTaskGetSchedulerState(), xTaskRemoveFromEventList(), xTaskResumeAll(), and QueueDefinition::xTasksWaitingToReceive.
xQueuePeekFromISR()
BaseType_t xQueuePeekFromISR (QueueHandle_t xQueue, void *const pvBuffer)
Definition at line 1876 of file queue.c.
{
BaseType_t xReturn;
UBaseType_t uxSavedInterruptStatus;
int8_t *pcOriginalReadPosition;
Queue_t * const pxQueue = xQueue;
  configASSERT( pxQueue );
  configASSERT( !( ( pvBuffer == NULL ) && ( pxQueue->uxItemSize != ( UBaseType_t ) 0U ) ) );
  configASSERT( pxQueue->uxItemSize != 0 ); /* Can't peek a semaphore. */
  /* RTOS ports that support interrupt nesting have the concept of a maximum
  system call (or maximum API call) interrupt priority.  Interrupts that are
  above the maximum system call priority are kept permanently enabled, even
  when the RTOS kernel is in a critical section, but cannot make any calls to
  FreeRTOS API functions.  If configASSERT() is defined in FreeRTOSConfig.h
  then portASSERT_IF_INTERRUPT_PRIORITY_INVALID() will result in an assertion
  failure if a FreeRTOS API function is called from an interrupt that has been
  assigned a priority above the configured maximum system call priority.
  Only FreeRTOS functions that end in FromISR can be called from interrupts
  that have been assigned a priority at or (logically) below the maximum
  system call interrupt priority.  FreeRTOS maintains a separate interrupt
  safe API to ensure interrupt entry is as fast and as simple as possible.
  More information (albeit Cortex-M specific) is provided on the following
  link: http://www.freertos.org/RTOS-Cortex-M3-M4.html */
  portASSERT_IF_INTERRUPT_PRIORITY_INVALID();
  uxSavedInterruptStatus = portSET_INTERRUPT_MASK_FROM_ISR();
  {
    /* Cannot block in an ISR, so check there is data available. */
    if( pxQueue->uxMessagesWaiting > ( UBaseType_t ) 0 )
    {
      traceQUEUE_PEEK_FROM_ISR( pxQueue );
      /* Remember the read position so it can be reset as nothing is
      actually being removed from the queue. */
      pcOriginalReadPosition = pxQueue->u.xQueue.pcReadFrom;
      prvCopyDataFromQueue( pxQueue, pvBuffer );
      pxQueue->u.xQueue.pcReadFrom = pcOriginalReadPosition;
      xReturn = pdPASS;
    }
    else
    {
      xReturn = pdFAIL;
      traceQUEUE_PEEK_FROM_ISR_FAILED( pxQueue );
    }
  }
  portCLEAR_INTERRUPT_MASK_FROM_ISR( uxSavedInterruptStatus );
  return xReturn;
}
References configASSERT, QueuePointers::pcReadFrom, pdFAIL, pdPASS, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvCopyDataFromQueue(), traceQUEUE_PEEK_FROM_ISR, traceQUEUE_PEEK_FROM_ISR_FAILED, QueueDefinition::u, QueueDefinition::uxItemSize, QueueDefinition::uxMessagesWaiting, and QueueDefinition::xQueue.
xQueueReceive()
BaseType_t xQueueReceive (QueueHandle_t xQueue, void *const pvBuffer, TickType_t xTicksToWait)
Definition at line 1277 of file queue.c.
{
BaseType_t xEntryTimeSet = pdFALSE;
TimeOut_t xTimeOut;
Queue_t * const pxQueue = xQueue;
  /* Check the pointer is not NULL. */
  configASSERT( ( pxQueue ) );
  /* The buffer into which data is received can only be NULL if the data size
  is zero (so no data is copied into the buffer. */
  configASSERT( !( ( ( pvBuffer ) == NULL ) && ( ( pxQueue )->uxItemSize != ( UBaseType_t ) 0U ) ) );
  /* Cannot block if the scheduler is suspended. */
  #if ( ( INCLUDE_xTaskGetSchedulerState == 1 ) || ( configUSE_TIMERS == 1 ) )
  {
    configASSERT( !( ( xTaskGetSchedulerState() == taskSCHEDULER_SUSPENDED ) && ( xTicksToWait != 0 ) ) );
  }
  #endif
  /*lint -save -e904  This function relaxes the coding standard somewhat to
  allow return statements within the function itself.  This is done in the
  interest of execution time efficiency. */
  for( ;; )
  {
    taskENTER_CRITICAL();
    {
      const UBaseType_t uxMessagesWaiting = pxQueue->uxMessagesWaiting;
      /* Is there data in the queue now?  To be running the calling task
      must be the highest priority task wanting to access the queue. */
      if( uxMessagesWaiting > ( UBaseType_t ) 0 )
      {
        /* Data available, remove one item. */
        prvCopyDataFromQueue( pxQueue, pvBuffer );
        traceQUEUE_RECEIVE( pxQueue );
        pxQueue->uxMessagesWaiting = uxMessagesWaiting - ( UBaseType_t ) 1;
        /* There is now space in the queue, were any tasks waiting to
        post to the queue?  If so, unblock the highest priority waiting
        task. */
        if( listLIST_IS_EMPTY( &( pxQueue->xTasksWaitingToSend ) ) == pdFALSE )
        {
          if( xTaskRemoveFromEventList( &( pxQueue->xTasksWaitingToSend ) ) != pdFALSE )
          {
            queueYIELD_IF_USING_PREEMPTION();
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
        }
        else
        {
          mtCOVERAGE_TEST_MARKER();
        }
        taskEXIT_CRITICAL();
        return pdPASS;
      }
      else
      {
        if( xTicksToWait == ( TickType_t ) 0 )
        {
          /* The queue was empty and no block time is specified (or
          the block time has expired) so leave now. */
          taskEXIT_CRITICAL();
          traceQUEUE_RECEIVE_FAILED( pxQueue );
          return errQUEUE_EMPTY;
        }
        else if( xEntryTimeSet == pdFALSE )
        {
          /* The queue was empty and a block time was specified so
          configure the timeout structure. */
          vTaskInternalSetTimeOutState( &xTimeOut );
          xEntryTimeSet = pdTRUE;
        }
        else
        {
          /* Entry time was already set. */
          mtCOVERAGE_TEST_MARKER();
        }
      }
    }
    taskEXIT_CRITICAL();
    /* Interrupts and other tasks can send to and receive from the queue
    now the critical section has been exited. */
    vTaskSuspendAll();
    prvLockQueue( pxQueue );
    /* Update the timeout state to see if it has expired yet. */
    if( xTaskCheckForTimeOut( &xTimeOut, &xTicksToWait ) == pdFALSE )
    {
      /* The timeout has not expired.  If the queue is still empty place
      the task on the list of tasks waiting to receive from the queue. */
      if( prvIsQueueEmpty( pxQueue ) != pdFALSE )
      {
        traceBLOCKING_ON_QUEUE_RECEIVE( pxQueue );
        vTaskPlaceOnEventList( &( pxQueue->xTasksWaitingToReceive ), xTicksToWait );
        prvUnlockQueue( pxQueue );
        if( xTaskResumeAll() == pdFALSE )
        {
          portYIELD_WITHIN_API();
        }
        else
        {
          mtCOVERAGE_TEST_MARKER();
        }
      }
      else
      {
        /* The queue contains data again.  Loop back to try and read the
        data. */
        prvUnlockQueue( pxQueue );
        ( void ) xTaskResumeAll();
      }
    }
    else
    {
      /* Timed out.  If there is no data in the queue exit, otherwise loop
      back and attempt to read the data. */
      prvUnlockQueue( pxQueue );
      ( void ) xTaskResumeAll();
      if( prvIsQueueEmpty( pxQueue ) != pdFALSE )
      {
        traceQUEUE_RECEIVE_FAILED( pxQueue );
        return errQUEUE_EMPTY;
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
  } /*lint -restore */
}
References configASSERT, errQUEUE_EMPTY, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdPASS, pdTRUE, portYIELD_WITHIN_API, prvCopyDataFromQueue(), prvIsQueueEmpty(), prvLockQueue, prvUnlockQueue(), queueYIELD_IF_USING_PREEMPTION, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSCHEDULER_SUSPENDED, traceBLOCKING_ON_QUEUE_RECEIVE, traceQUEUE_RECEIVE, traceQUEUE_RECEIVE_FAILED, QueueDefinition::uxMessagesWaiting, vTaskInternalSetTimeOutState(), vTaskPlaceOnEventList(), vTaskSuspendAll(), xTaskCheckForTimeOut(), xTaskGetSchedulerState(), xTaskRemoveFromEventList(), xTaskResumeAll(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTasksWaitingToSend.
Referenced by osMessageQueueGet().
xQueueReceiveFromISR()
BaseType_t xQueueReceiveFromISR (QueueHandle_t xQueue, void *const pvBuffer, BaseType_t *const pxHigherPriorityTaskWoken)
Definition at line 1785 of file queue.c.
{
BaseType_t xReturn;
UBaseType_t uxSavedInterruptStatus;
Queue_t * const pxQueue = xQueue;
  configASSERT( pxQueue );
  configASSERT( !( ( pvBuffer == NULL ) && ( pxQueue->uxItemSize != ( UBaseType_t ) 0U ) ) );
  /* RTOS ports that support interrupt nesting have the concept of a maximum
  system call (or maximum API call) interrupt priority.  Interrupts that are
  above the maximum system call priority are kept permanently enabled, even
  when the RTOS kernel is in a critical section, but cannot make any calls to
  FreeRTOS API functions.  If configASSERT() is defined in FreeRTOSConfig.h
  then portASSERT_IF_INTERRUPT_PRIORITY_INVALID() will result in an assertion
  failure if a FreeRTOS API function is called from an interrupt that has been
  assigned a priority above the configured maximum system call priority.
  Only FreeRTOS functions that end in FromISR can be called from interrupts
  that have been assigned a priority at or (logically) below the maximum
  system call interrupt priority.  FreeRTOS maintains a separate interrupt
  safe API to ensure interrupt entry is as fast and as simple as possible.
  More information (albeit Cortex-M specific) is provided on the following
  link: http://www.freertos.org/RTOS-Cortex-M3-M4.html */
  portASSERT_IF_INTERRUPT_PRIORITY_INVALID();
  uxSavedInterruptStatus = portSET_INTERRUPT_MASK_FROM_ISR();
  {
    const UBaseType_t uxMessagesWaiting = pxQueue->uxMessagesWaiting;
    /* Cannot block in an ISR, so check there is data available. */
    if( uxMessagesWaiting > ( UBaseType_t ) 0 )
    {
      const int8_t cRxLock = pxQueue->cRxLock;
      traceQUEUE_RECEIVE_FROM_ISR( pxQueue );
      prvCopyDataFromQueue( pxQueue, pvBuffer );
      pxQueue->uxMessagesWaiting = uxMessagesWaiting - ( UBaseType_t ) 1;
      /* If the queue is locked the event list will not be modified.
      Instead update the lock count so the task that unlocks the queue
      will know that an ISR has removed data while the queue was
      locked. */
      if( cRxLock == queueUNLOCKED )
      {
        if( listLIST_IS_EMPTY( &( pxQueue->xTasksWaitingToSend ) ) == pdFALSE )
        {
          if( xTaskRemoveFromEventList( &( pxQueue->xTasksWaitingToSend ) ) != pdFALSE )
          {
            /* The task waiting has a higher priority than us so
            force a context switch. */
            if( pxHigherPriorityTaskWoken != NULL )
            {
              *pxHigherPriorityTaskWoken = pdTRUE;
            }
            else
            {
              mtCOVERAGE_TEST_MARKER();
            }
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
        }
        else
        {
          mtCOVERAGE_TEST_MARKER();
        }
      }
      else
      {
        /* Increment the lock count so the task that unlocks the queue
        knows that data was removed while it was locked. */
        pxQueue->cRxLock = ( int8_t ) ( cRxLock + 1 );
      }
      xReturn = pdPASS;
    }
    else
    {
      xReturn = pdFAIL;
      traceQUEUE_RECEIVE_FROM_ISR_FAILED( pxQueue );
    }
  }
  portCLEAR_INTERRUPT_MASK_FROM_ISR( uxSavedInterruptStatus );
  return xReturn;
}
References configASSERT, QueueDefinition::cRxLock, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFAIL, pdFALSE, pdPASS, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvCopyDataFromQueue(), queueUNLOCKED, traceQUEUE_RECEIVE_FROM_ISR, traceQUEUE_RECEIVE_FROM_ISR_FAILED, QueueDefinition::uxItemSize, QueueDefinition::uxMessagesWaiting, xTaskRemoveFromEventList(), and QueueDefinition::xTasksWaitingToSend.
Referenced by osMessageQueueGet().
xQueueSemaphoreTake()
BaseType_t xQueueSemaphoreTake (QueueHandle_t xQueue, TickType_t xTicksToWait)
Definition at line 1418 of file queue.c.
{
BaseType_t xEntryTimeSet = pdFALSE;
TimeOut_t xTimeOut;
Queue_t * const pxQueue = xQueue;
#if(configUSE_MUTEXES == 1)
  BaseType_t xInheritanceOccurred = pdFALSE;
#endif
  /* Check the queue pointer is not NULL. */
  configASSERT( ( pxQueue ) );
  /* Check this really is a semaphore, in which case the item size will be
  0. */
  configASSERT( pxQueue->uxItemSize == 0 );
  /* Cannot block if the scheduler is suspended. */
  #if ( ( INCLUDE_xTaskGetSchedulerState == 1 ) || ( configUSE_TIMERS == 1 ) )
  {
    configASSERT( !( ( xTaskGetSchedulerState() == taskSCHEDULER_SUSPENDED ) && ( xTicksToWait != 0 ) ) );
  }
  #endif
  /*lint -save -e904 This function relaxes the coding standard somewhat to allow return
  statements within the function itself.  This is done in the interest
  of execution time efficiency. */
  for( ;; )
  {
    taskENTER_CRITICAL();
    {
      /* Semaphores are queues with an item size of 0, and where the
      number of messages in the queue is the semaphore's count value. */
      const UBaseType_t uxSemaphoreCount = pxQueue->uxMessagesWaiting;
      /* Is there data in the queue now?  To be running the calling task
      must be the highest priority task wanting to access the queue. */
      if( uxSemaphoreCount > ( UBaseType_t ) 0 )
      {
        traceQUEUE_RECEIVE( pxQueue );
        /* Semaphores are queues with a data size of zero and where the
        messages waiting is the semaphore's count.  Reduce the count. */
        pxQueue->uxMessagesWaiting = uxSemaphoreCount - ( UBaseType_t ) 1;
        #if ( configUSE_MUTEXES == 1 )
        {
          if( pxQueue->uxQueueType == queueQUEUE_IS_MUTEX )
          {
            /* Record the information required to implement
            priority inheritance should it become necessary. */
            pxQueue->u.xSemaphore.xMutexHolder = pvTaskIncrementMutexHeldCount();
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
        }
        #endif /* configUSE_MUTEXES */
        /* Check to see if other tasks are blocked waiting to give the
        semaphore, and if so, unblock the highest priority such task. */
        if( listLIST_IS_EMPTY( &( pxQueue->xTasksWaitingToSend ) ) == pdFALSE )
        {
          if( xTaskRemoveFromEventList( &( pxQueue->xTasksWaitingToSend ) ) != pdFALSE )
          {
            queueYIELD_IF_USING_PREEMPTION();
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
        }
        else
        {
          mtCOVERAGE_TEST_MARKER();
        }
        taskEXIT_CRITICAL();
        return pdPASS;
      }
      else
      {
        if( xTicksToWait == ( TickType_t ) 0 )
        {
          /* For inheritance to have occurred there must have been an
          initial timeout, and an adjusted timeout cannot become 0, as
          if it were 0 the function would have exited. */
          #if( configUSE_MUTEXES == 1 )
          {
            configASSERT( xInheritanceOccurred == pdFALSE );
          }
          #endif /* configUSE_MUTEXES */
          /* The semaphore count was 0 and no block time is specified
          (or the block time has expired) so exit now. */
          taskEXIT_CRITICAL();
          traceQUEUE_RECEIVE_FAILED( pxQueue );
          return errQUEUE_EMPTY;
        }
        else if( xEntryTimeSet == pdFALSE )
        {
          /* The semaphore count was 0 and a block time was specified
          so configure the timeout structure ready to block. */
          vTaskInternalSetTimeOutState( &xTimeOut );
          xEntryTimeSet = pdTRUE;
        }
        else
        {
          /* Entry time was already set. */
          mtCOVERAGE_TEST_MARKER();
        }
      }
    }
    taskEXIT_CRITICAL();
    /* Interrupts and other tasks can give to and take from the semaphore
    now the critical section has been exited. */
    vTaskSuspendAll();
    prvLockQueue( pxQueue );
    /* Update the timeout state to see if it has expired yet. */
    if( xTaskCheckForTimeOut( &xTimeOut, &xTicksToWait ) == pdFALSE )
    {
      /* A block time is specified and not expired.  If the semaphore
      count is 0 then enter the Blocked state to wait for a semaphore to
      become available.  As semaphores are implemented with queues the
      queue being empty is equivalent to the semaphore count being 0. */
      if( prvIsQueueEmpty( pxQueue ) != pdFALSE )
      {
        traceBLOCKING_ON_QUEUE_RECEIVE( pxQueue );
        #if ( configUSE_MUTEXES == 1 )
        {
          if( pxQueue->uxQueueType == queueQUEUE_IS_MUTEX )
          {
            taskENTER_CRITICAL();
            {
              xInheritanceOccurred = xTaskPriorityInherit( pxQueue->u.xSemaphore.xMutexHolder );
            }
            taskEXIT_CRITICAL();
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
        }
        #endif
        vTaskPlaceOnEventList( &( pxQueue->xTasksWaitingToReceive ), xTicksToWait );
        prvUnlockQueue( pxQueue );
        if( xTaskResumeAll() == pdFALSE )
        {
          portYIELD_WITHIN_API();
        }
        else
        {
          mtCOVERAGE_TEST_MARKER();
        }
      }
      else
      {
        /* There was no timeout and the semaphore count was not 0, so
        attempt to take the semaphore again. */
        prvUnlockQueue( pxQueue );
        ( void ) xTaskResumeAll();
      }
    }
    else
    {
      /* Timed out. */
      prvUnlockQueue( pxQueue );
      ( void ) xTaskResumeAll();
      /* If the semaphore count is 0 exit now as the timeout has
      expired.  Otherwise return to attempt to take the semaphore that is
      known to be available.  As semaphores are implemented by queues the
      queue being empty is equivalent to the semaphore count being 0. */
      if( prvIsQueueEmpty( pxQueue ) != pdFALSE )
      {
        #if ( configUSE_MUTEXES == 1 )
        {
          /* xInheritanceOccurred could only have be set if
          pxQueue->uxQueueType == queueQUEUE_IS_MUTEX so no need to
          test the mutex type again to check it is actually a mutex. */
          if( xInheritanceOccurred != pdFALSE )
          {
            taskENTER_CRITICAL();
            {
              UBaseType_t uxHighestWaitingPriority;
              /* This task blocking on the mutex caused another
              task to inherit this task's priority.  Now this task
              has timed out the priority should be disinherited
              again, but only as low as the next highest priority
              task that is waiting for the same mutex. */
              uxHighestWaitingPriority = prvGetDisinheritPriorityAfterTimeout( pxQueue );
              vTaskPriorityDisinheritAfterTimeout( pxQueue->u.xSemaphore.xMutexHolder, uxHighestWaitingPriority );
            }
            taskEXIT_CRITICAL();
          }
        }
        #endif /* configUSE_MUTEXES */
        traceQUEUE_RECEIVE_FAILED( pxQueue );
        return errQUEUE_EMPTY;
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
  } /*lint -restore */
}
References configASSERT, errQUEUE_EMPTY, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdPASS, pdTRUE, portYIELD_WITHIN_API, prvIsQueueEmpty(), prvLockQueue, prvUnlockQueue(), pvTaskIncrementMutexHeldCount(), queueQUEUE_IS_MUTEX, queueYIELD_IF_USING_PREEMPTION, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSCHEDULER_SUSPENDED, traceBLOCKING_ON_QUEUE_RECEIVE, traceQUEUE_RECEIVE, traceQUEUE_RECEIVE_FAILED, QueueDefinition::u, QueueDefinition::uxItemSize, QueueDefinition::uxMessagesWaiting, vTaskInternalSetTimeOutState(), vTaskPlaceOnEventList(), vTaskPriorityDisinheritAfterTimeout(), vTaskSuspendAll(), SemaphoreData::xMutexHolder, QueueDefinition::xSemaphore, xTaskCheckForTimeOut(), xTaskGetSchedulerState(), xTaskPriorityInherit(), xTaskRemoveFromEventList(), xTaskResumeAll(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTasksWaitingToSend.