NUCLEO-G0B1RE Examples: NUCLEO-G0B1RE/FreeRTOS_Queues/Middlewares/Third_Party/FreeRTOS/Source/include/stream_buffer.h File Reference
stream_buffer.h File Reference
Macros
#define xStreamBufferCreate(xBufferSizeBytes, xTriggerLevelBytes) xStreamBufferGenericCreate(xBufferSizeBytes, xTriggerLevelBytes, pdFALSE)
#define xStreamBufferCreateStatic(xBufferSizeBytes, xTriggerLevelBytes, pucStreamBufferStorageArea, pxStaticStreamBuffer) xStreamBufferGenericCreateStatic(xBufferSizeBytes, xTriggerLevelBytes, pdFALSE, pucStreamBufferStorageArea, pxStaticStreamBuffer)
Typedefs
typedef struct StreamBufferDef_t * StreamBufferHandle_t
Functions
size_t xStreamBufferSend (StreamBufferHandle_t xStreamBuffer, const void *pvTxData, size_t xDataLengthBytes, TickType_t xTicksToWait) PRIVILEGED_FUNCTION
size_t xStreamBufferSendFromISR (StreamBufferHandle_t xStreamBuffer, const void *pvTxData, size_t xDataLengthBytes, BaseType_t *const pxHigherPriorityTaskWoken) PRIVILEGED_FUNCTION
size_t xStreamBufferReceive (StreamBufferHandle_t xStreamBuffer, void *pvRxData, size_t xBufferLengthBytes, TickType_t xTicksToWait) PRIVILEGED_FUNCTION
size_t xStreamBufferReceiveFromISR (StreamBufferHandle_t xStreamBuffer, void *pvRxData, size_t xBufferLengthBytes, BaseType_t *const pxHigherPriorityTaskWoken) PRIVILEGED_FUNCTION
void vStreamBufferDelete (StreamBufferHandle_t xStreamBuffer) PRIVILEGED_FUNCTION
BaseType_t xStreamBufferIsFull (StreamBufferHandle_t xStreamBuffer) PRIVILEGED_FUNCTION
BaseType_t xStreamBufferIsEmpty (StreamBufferHandle_t xStreamBuffer) PRIVILEGED_FUNCTION
BaseType_t xStreamBufferReset (StreamBufferHandle_t xStreamBuffer) PRIVILEGED_FUNCTION
size_t xStreamBufferSpacesAvailable (StreamBufferHandle_t xStreamBuffer) PRIVILEGED_FUNCTION
size_t xStreamBufferBytesAvailable (StreamBufferHandle_t xStreamBuffer) PRIVILEGED_FUNCTION
BaseType_t xStreamBufferSetTriggerLevel (StreamBufferHandle_t xStreamBuffer, size_t xTriggerLevel) PRIVILEGED_FUNCTION
BaseType_t xStreamBufferSendCompletedFromISR (StreamBufferHandle_t xStreamBuffer, BaseType_t *pxHigherPriorityTaskWoken) PRIVILEGED_FUNCTION
BaseType_t xStreamBufferReceiveCompletedFromISR (StreamBufferHandle_t xStreamBuffer, BaseType_t *pxHigherPriorityTaskWoken) PRIVILEGED_FUNCTION
StreamBufferHandle_t xStreamBufferGenericCreate (size_t xBufferSizeBytes, size_t xTriggerLevelBytes, BaseType_t xIsMessageBuffer) PRIVILEGED_FUNCTION
StreamBufferHandle_t xStreamBufferGenericCreateStatic (size_t xBufferSizeBytes, size_t xTriggerLevelBytes, BaseType_t xIsMessageBuffer, uint8_t *const pucStreamBufferStorageArea, StaticStreamBuffer_t *const pxStaticStreamBuffer) PRIVILEGED_FUNCTION
size_t xStreamBufferNextMessageLengthBytes (StreamBufferHandle_t xStreamBuffer) PRIVILEGED_FUNCTION
Macro Definition Documentation
xStreamBufferCreate
#define xStreamBufferCreate (xBufferSizeBytes, xTriggerLevelBytes) xStreamBufferGenericCreate(xBufferSizeBytes, xTriggerLevelBytes, pdFALSE)
Definition at line 137 of file stream_buffer.h.
xStreamBufferCreateStatic
#define xStreamBufferCreateStatic (xBufferSizeBytes, xTriggerLevelBytes, pucStreamBufferStorageArea, pxStaticStreamBuffer) xStreamBufferGenericCreateStatic(xBufferSizeBytes, xTriggerLevelBytes, pdFALSE, pucStreamBufferStorageArea, pxStaticStreamBuffer)
Definition at line 218 of file stream_buffer.h.
Typedef Documentation
StreamBufferHandle_t
typedef struct StreamBufferDef_t* StreamBufferHandle_t
Definition at line 69 of file stream_buffer.h.
Function Documentation
vStreamBufferDelete()
void vStreamBufferDelete (StreamBufferHandle_t xStreamBuffer)
Definition at line 359 of file stream_buffer.c.
{
StreamBuffer_t * pxStreamBuffer = xStreamBuffer;
  configASSERT( pxStreamBuffer );
  traceSTREAM_BUFFER_DELETE( xStreamBuffer );
  if( ( pxStreamBuffer->ucFlags & sbFLAGS_IS_STATICALLY_ALLOCATED ) == ( uint8_t ) pdFALSE )
  {
    #if( configSUPPORT_DYNAMIC_ALLOCATION == 1 )
    {
      /* Both the structure and the buffer were allocated using a single call
      to pvPortMalloc(), hence only one call to vPortFree() is required. */
      vPortFree( ( void * ) pxStreamBuffer ); /*lint !e9087 Standard free() semantics require void *, plus pxStreamBuffer was allocated by pvPortMalloc(). */
    }
    #else
    {
      /* Should not be possible to get here, ucFlags must be corrupt.
      Force an assert. */
      configASSERT( xStreamBuffer == ( StreamBufferHandle_t ) ~0 );
    }
    #endif
  }
  else
  {
    /* The structure and buffer were not allocated dynamically and cannot be
    freed - just scrub the structure so future use will assert. */
    ( void ) memset( pxStreamBuffer, 0x00, sizeof( StreamBuffer_t ) );
  }
}
References configASSERT, pdFALSE, sbFLAGS_IS_STATICALLY_ALLOCATED, traceSTREAM_BUFFER_DELETE, StreamBufferDef_t::ucFlags, and vPortFree().
xStreamBufferBytesAvailable()
size_t xStreamBufferBytesAvailable (StreamBufferHandle_t xStreamBuffer)
Definition at line 494 of file stream_buffer.c.
{
const StreamBuffer_t * const pxStreamBuffer = xStreamBuffer;
size_t xReturn;
  configASSERT( pxStreamBuffer );
  xReturn = prvBytesInBuffer( pxStreamBuffer );
  return xReturn;
}
References configASSERT, and prvBytesInBuffer().
xStreamBufferGenericCreate()
StreamBufferHandle_t xStreamBufferGenericCreate (size_t xBufferSizeBytes, size_t xTriggerLevelBytes, BaseType_t xIsMessageBuffer)
xStreamBufferGenericCreateStatic()
StreamBufferHandle_t xStreamBufferGenericCreateStatic (size_t xBufferSizeBytes, size_t xTriggerLevelBytes, BaseType_t xIsMessageBuffer, uint8_t *const pucStreamBufferStorageArea, StaticStreamBuffer_t *const pxStaticStreamBuffer)
xStreamBufferIsEmpty()
BaseType_t xStreamBufferIsEmpty (StreamBufferHandle_t xStreamBuffer)
Definition at line 970 of file stream_buffer.c.
{
const StreamBuffer_t * const pxStreamBuffer = xStreamBuffer;
BaseType_t xReturn;
size_t xTail;
  configASSERT( pxStreamBuffer );
  /* True if no bytes are available. */
  xTail = pxStreamBuffer->xTail;
  if( pxStreamBuffer->xHead == xTail )
  {
    xReturn = pdTRUE;
  }
  else
  {
    xReturn = pdFALSE;
  }
  return xReturn;
}
References configASSERT, pdFALSE, pdTRUE, StreamBufferDef_t::xHead, and StreamBufferDef_t::xTail.
xStreamBufferIsFull()
BaseType_t xStreamBufferIsFull (StreamBufferHandle_t xStreamBuffer)
Definition at line 993 of file stream_buffer.c.
{
BaseType_t xReturn;
size_t xBytesToStoreMessageLength;
const StreamBuffer_t * const pxStreamBuffer = xStreamBuffer;
  configASSERT( pxStreamBuffer );
  /* This generic version of the receive function is used by both message
  buffers, which store discrete messages, and stream buffers, which store a
  continuous stream of bytes.  Discrete messages include an additional
  sbBYTES_TO_STORE_MESSAGE_LENGTH bytes that hold the length of the message. */
  if( ( pxStreamBuffer->ucFlags & sbFLAGS_IS_MESSAGE_BUFFER ) != ( uint8_t ) 0 )
  {
    xBytesToStoreMessageLength = sbBYTES_TO_STORE_MESSAGE_LENGTH;
  }
  else
  {
    xBytesToStoreMessageLength = 0;
  }
  /* True if the available space equals zero. */
  if( xStreamBufferSpacesAvailable( xStreamBuffer ) <= xBytesToStoreMessageLength )
  {
    xReturn = pdTRUE;
  }
  else
  {
    xReturn = pdFALSE;
  }
  return xReturn;
}
References configASSERT, pdFALSE, pdTRUE, sbBYTES_TO_STORE_MESSAGE_LENGTH, sbFLAGS_IS_MESSAGE_BUFFER, StreamBufferDef_t::ucFlags, and xStreamBufferSpacesAvailable().
xStreamBufferNextMessageLengthBytes()
size_t xStreamBufferNextMessageLengthBytes (StreamBufferHandle_t xStreamBuffer)
Definition at line 817 of file stream_buffer.c.
{
StreamBuffer_t * const pxStreamBuffer = xStreamBuffer;
size_t xReturn, xBytesAvailable, xOriginalTail;
configMESSAGE_BUFFER_LENGTH_TYPE xTempReturn;
  configASSERT( pxStreamBuffer );
  /* Ensure the stream buffer is being used as a message buffer. */
  if( ( pxStreamBuffer->ucFlags & sbFLAGS_IS_MESSAGE_BUFFER ) != ( uint8_t ) 0 )
  {
    xBytesAvailable = prvBytesInBuffer( pxStreamBuffer );
    if( xBytesAvailable > sbBYTES_TO_STORE_MESSAGE_LENGTH )
    {
      /* The number of bytes available is greater than the number of bytes
      required to hold the length of the next message, so another message
      is available.  Return its length without removing the length bytes
      from the buffer.  A copy of the tail is stored so the buffer can be
      returned to its prior state as the message is not actually being
      removed from the buffer. */
      xOriginalTail = pxStreamBuffer->xTail;
      ( void ) prvReadBytesFromBuffer( pxStreamBuffer, ( uint8_t * ) &xTempReturn, sbBYTES_TO_STORE_MESSAGE_LENGTH, xBytesAvailable );
      xReturn = ( size_t ) xTempReturn;
      pxStreamBuffer->xTail = xOriginalTail;
    }
    else
    {
      /* The minimum amount of bytes in a message buffer is
      ( sbBYTES_TO_STORE_MESSAGE_LENGTH + 1 ), so if xBytesAvailable is
      less than sbBYTES_TO_STORE_MESSAGE_LENGTH the only other valid
      value is 0. */
      configASSERT( xBytesAvailable == 0 );
      xReturn = 0;
    }
  }
  else
  {
    xReturn = 0;
  }
  return xReturn;
}
References configASSERT, configMESSAGE_BUFFER_LENGTH_TYPE, prvBytesInBuffer(), prvReadBytesFromBuffer(), sbBYTES_TO_STORE_MESSAGE_LENGTH, sbFLAGS_IS_MESSAGE_BUFFER, StreamBufferDef_t::ucFlags, and StreamBufferDef_t::xTail.
xStreamBufferReceive()
size_t xStreamBufferReceive (StreamBufferHandle_t xStreamBuffer, void * pvRxData, size_t xBufferLengthBytes, TickType_t xTicksToWait)
Definition at line 713 of file stream_buffer.c.
{
StreamBuffer_t * const pxStreamBuffer = xStreamBuffer;
size_t xReceivedLength = 0, xBytesAvailable, xBytesToStoreMessageLength;
  configASSERT( pvRxData );
  configASSERT( pxStreamBuffer );
  /* This receive function is used by both message buffers, which store
  discrete messages, and stream buffers, which store a continuous stream of
  bytes.  Discrete messages include an additional
  sbBYTES_TO_STORE_MESSAGE_LENGTH bytes that hold the length of the
  message. */
  if( ( pxStreamBuffer->ucFlags & sbFLAGS_IS_MESSAGE_BUFFER ) != ( uint8_t ) 0 )
  {
    xBytesToStoreMessageLength = sbBYTES_TO_STORE_MESSAGE_LENGTH;
  }
  else
  {
    xBytesToStoreMessageLength = 0;
  }
  if( xTicksToWait != ( TickType_t ) 0 )
  {
    /* Checking if there is data and clearing the notification state must be
    performed atomically. */
    taskENTER_CRITICAL();
    {
      xBytesAvailable = prvBytesInBuffer( pxStreamBuffer );
      /* If this function was invoked by a message buffer read then
      xBytesToStoreMessageLength holds the number of bytes used to hold
      the length of the next discrete message.  If this function was
      invoked by a stream buffer read then xBytesToStoreMessageLength will
      be 0. */
      if( xBytesAvailable <= xBytesToStoreMessageLength )
      {
        /* Clear notification state as going to wait for data. */
        ( void ) xTaskNotifyStateClear( NULL );
        /* Should only be one reader. */
        configASSERT( pxStreamBuffer->xTaskWaitingToReceive == NULL );
        pxStreamBuffer->xTaskWaitingToReceive = xTaskGetCurrentTaskHandle();
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
    taskEXIT_CRITICAL();
    if( xBytesAvailable <= xBytesToStoreMessageLength )
    {
      /* Wait for data to be available. */
      traceBLOCKING_ON_STREAM_BUFFER_RECEIVE( xStreamBuffer );
      ( void ) xTaskNotifyWait( ( uint32_t ) 0, ( uint32_t ) 0, NULL, xTicksToWait );
      pxStreamBuffer->xTaskWaitingToReceive = NULL;
      /* Recheck the data available after blocking. */
      xBytesAvailable = prvBytesInBuffer( pxStreamBuffer );
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
  }
  else
  {
    xBytesAvailable = prvBytesInBuffer( pxStreamBuffer );
  }
  /* Whether receiving a discrete message (where xBytesToStoreMessageLength
  holds the number of bytes used to store the message length) or a stream of
  bytes (where xBytesToStoreMessageLength is zero), the number of bytes
  available must be greater than xBytesToStoreMessageLength to be able to
  read bytes from the buffer. */
  if( xBytesAvailable > xBytesToStoreMessageLength )
  {
    xReceivedLength = prvReadMessageFromBuffer( pxStreamBuffer, pvRxData, xBufferLengthBytes, xBytesAvailable, xBytesToStoreMessageLength );
    /* Was a task waiting for space in the buffer? */
    if( xReceivedLength != ( size_t ) 0 )
    {
      traceSTREAM_BUFFER_RECEIVE( xStreamBuffer, xReceivedLength );
      sbRECEIVE_COMPLETED( pxStreamBuffer );
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
  }
  else
  {
    traceSTREAM_BUFFER_RECEIVE_FAILED( xStreamBuffer );
    mtCOVERAGE_TEST_MARKER();
  }
  return xReceivedLength;
}
References configASSERT, mtCOVERAGE_TEST_MARKER, prvBytesInBuffer(), prvReadMessageFromBuffer(), sbBYTES_TO_STORE_MESSAGE_LENGTH, sbFLAGS_IS_MESSAGE_BUFFER, sbRECEIVE_COMPLETED, taskENTER_CRITICAL, taskEXIT_CRITICAL, traceBLOCKING_ON_STREAM_BUFFER_RECEIVE, traceSTREAM_BUFFER_RECEIVE, traceSTREAM_BUFFER_RECEIVE_FAILED, StreamBufferDef_t::ucFlags, xTaskGetCurrentTaskHandle(), xTaskNotifyStateClear(), xTaskNotifyWait(), and StreamBufferDef_t::xTaskWaitingToReceive.
xStreamBufferReceiveCompletedFromISR()
BaseType_t xStreamBufferReceiveCompletedFromISR (StreamBufferHandle_t xStreamBuffer, BaseType_t * pxHigherPriorityTaskWoken)
Definition at line 1058 of file stream_buffer.c.
{
StreamBuffer_t * const pxStreamBuffer = xStreamBuffer;
BaseType_t xReturn;
UBaseType_t uxSavedInterruptStatus;
  configASSERT( pxStreamBuffer );
  uxSavedInterruptStatus = ( UBaseType_t ) portSET_INTERRUPT_MASK_FROM_ISR();
  {
    if( ( pxStreamBuffer )->xTaskWaitingToSend != NULL )
    {
      ( void ) xTaskNotifyFromISR( ( pxStreamBuffer )->xTaskWaitingToSend,
                     ( uint32_t ) 0,
                     eNoAction,
                     pxHigherPriorityTaskWoken );
      ( pxStreamBuffer )->xTaskWaitingToSend = NULL;
      xReturn = pdTRUE;
    }
    else
    {
      xReturn = pdFALSE;
    }
  }
  portCLEAR_INTERRUPT_MASK_FROM_ISR( uxSavedInterruptStatus );
  return xReturn;
}
References configASSERT, eNoAction, pdFALSE, pdTRUE, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, and xTaskNotifyFromISR.
xStreamBufferReceiveFromISR()
size_t xStreamBufferReceiveFromISR (StreamBufferHandle_t xStreamBuffer, void * pvRxData, size_t xBufferLengthBytes, BaseType_t *const pxHigherPriorityTaskWoken)
Definition at line 861 of file stream_buffer.c.
{
StreamBuffer_t * const pxStreamBuffer = xStreamBuffer;
size_t xReceivedLength = 0, xBytesAvailable, xBytesToStoreMessageLength;
  configASSERT( pvRxData );
  configASSERT( pxStreamBuffer );
  /* This receive function is used by both message buffers, which store
  discrete messages, and stream buffers, which store a continuous stream of
  bytes.  Discrete messages include an additional
  sbBYTES_TO_STORE_MESSAGE_LENGTH bytes that hold the length of the
  message. */
  if( ( pxStreamBuffer->ucFlags & sbFLAGS_IS_MESSAGE_BUFFER ) != ( uint8_t ) 0 )
  {
    xBytesToStoreMessageLength = sbBYTES_TO_STORE_MESSAGE_LENGTH;
  }
  else
  {
    xBytesToStoreMessageLength = 0;
  }
  xBytesAvailable = prvBytesInBuffer( pxStreamBuffer );
  /* Whether receiving a discrete message (where xBytesToStoreMessageLength
  holds the number of bytes used to store the message length) or a stream of
  bytes (where xBytesToStoreMessageLength is zero), the number of bytes
  available must be greater than xBytesToStoreMessageLength to be able to
  read bytes from the buffer. */
  if( xBytesAvailable > xBytesToStoreMessageLength )
  {
    xReceivedLength = prvReadMessageFromBuffer( pxStreamBuffer, pvRxData, xBufferLengthBytes, xBytesAvailable, xBytesToStoreMessageLength );
    /* Was a task waiting for space in the buffer? */
    if( xReceivedLength != ( size_t ) 0 )
    {
      sbRECEIVE_COMPLETED_FROM_ISR( pxStreamBuffer, pxHigherPriorityTaskWoken );
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
  }
  else
  {
    mtCOVERAGE_TEST_MARKER();
  }
  traceSTREAM_BUFFER_RECEIVE_FROM_ISR( xStreamBuffer, xReceivedLength );
  return xReceivedLength;
}
References configASSERT, mtCOVERAGE_TEST_MARKER, prvBytesInBuffer(), prvReadMessageFromBuffer(), sbBYTES_TO_STORE_MESSAGE_LENGTH, sbFLAGS_IS_MESSAGE_BUFFER, sbRECEIVE_COMPLETED_FROM_ISR, traceSTREAM_BUFFER_RECEIVE_FROM_ISR, and StreamBufferDef_t::ucFlags.
xStreamBufferReset()
BaseType_t xStreamBufferReset (StreamBufferHandle_t xStreamBuffer)
Definition at line 392 of file stream_buffer.c.
{
StreamBuffer_t * const pxStreamBuffer = xStreamBuffer;
BaseType_t xReturn = pdFAIL;
#if(configUSE_TRACE_FACILITY == 1)
  UBaseType_t uxStreamBufferNumber;
#endif
  configASSERT( pxStreamBuffer );
  #if( configUSE_TRACE_FACILITY == 1 )
  {
    /* Store the stream buffer number so it can be restored after the
    reset. */
    uxStreamBufferNumber = pxStreamBuffer->uxStreamBufferNumber;
  }
  #endif
  /* Can only reset a message buffer if there are no tasks blocked on it. */
  taskENTER_CRITICAL();
  {
    if( pxStreamBuffer->xTaskWaitingToReceive == NULL )
    {
      if( pxStreamBuffer->xTaskWaitingToSend == NULL )
      {
        prvInitialiseNewStreamBuffer( pxStreamBuffer,
                        pxStreamBuffer->pucBuffer,
                        pxStreamBuffer->xLength,
                        pxStreamBuffer->xTriggerLevelBytes,
                        pxStreamBuffer->ucFlags );
        xReturn = pdPASS;
        #if( configUSE_TRACE_FACILITY == 1 )
        {
          pxStreamBuffer->uxStreamBufferNumber = uxStreamBufferNumber;
        }
        #endif
        traceSTREAM_BUFFER_RESET( xStreamBuffer );
      }
    }
  }
  taskEXIT_CRITICAL();
  return xReturn;
}
References configASSERT, pdFAIL, pdPASS, prvInitialiseNewStreamBuffer(), StreamBufferDef_t::pucBuffer, taskENTER_CRITICAL, taskEXIT_CRITICAL, traceSTREAM_BUFFER_RESET, StreamBufferDef_t::ucFlags, StreamBufferDef_t::xLength, StreamBufferDef_t::xTaskWaitingToReceive, StreamBufferDef_t::xTaskWaitingToSend, and StreamBufferDef_t::xTriggerLevelBytes.
xStreamBufferSend()
size_t xStreamBufferSend (StreamBufferHandle_t xStreamBuffer, const void * pvTxData, size_t xDataLengthBytes, TickType_t xTicksToWait)
Definition at line 506 of file stream_buffer.c.
{
StreamBuffer_t * const pxStreamBuffer = xStreamBuffer;
size_t xReturn, xSpace = 0;
size_t xRequiredSpace = xDataLengthBytes;
TimeOut_t xTimeOut;
  configASSERT( pvTxData );
  configASSERT( pxStreamBuffer );
  /* This send function is used to write to both message buffers and stream
  buffers.  If this is a message buffer then the space needed must be
  increased by the amount of bytes needed to store the length of the
  message. */
  if( ( pxStreamBuffer->ucFlags & sbFLAGS_IS_MESSAGE_BUFFER ) != ( uint8_t ) 0 )
  {
    xRequiredSpace += sbBYTES_TO_STORE_MESSAGE_LENGTH;
    /* Overflow? */
    configASSERT( xRequiredSpace > xDataLengthBytes );
  }
  else
  {
    mtCOVERAGE_TEST_MARKER();
  }
  if( xTicksToWait != ( TickType_t ) 0 )
  {
    vTaskSetTimeOutState( &xTimeOut );
    do
    {
      /* Wait until the required number of bytes are free in the message
      buffer. */
      taskENTER_CRITICAL();
      {
        xSpace = xStreamBufferSpacesAvailable( pxStreamBuffer );
        if( xSpace < xRequiredSpace )
        {
          /* Clear notification state as going to wait for space. */
          ( void ) xTaskNotifyStateClear( NULL );
          /* Should only be one writer. */
          configASSERT( pxStreamBuffer->xTaskWaitingToSend == NULL );
          pxStreamBuffer->xTaskWaitingToSend = xTaskGetCurrentTaskHandle();
        }
        else
        {
          taskEXIT_CRITICAL();
          break;
        }
      }
      taskEXIT_CRITICAL();
      traceBLOCKING_ON_STREAM_BUFFER_SEND( xStreamBuffer );
      ( void ) xTaskNotifyWait( ( uint32_t ) 0, ( uint32_t ) 0, NULL, xTicksToWait );
      pxStreamBuffer->xTaskWaitingToSend = NULL;
    } while( xTaskCheckForTimeOut( &xTimeOut, &xTicksToWait ) == pdFALSE );
  }
  else
  {
    mtCOVERAGE_TEST_MARKER();
  }
  if( xSpace == ( size_t ) 0 )
  {
    xSpace = xStreamBufferSpacesAvailable( pxStreamBuffer );
  }
  else
  {
    mtCOVERAGE_TEST_MARKER();
  }
  xReturn = prvWriteMessageToBuffer( pxStreamBuffer, pvTxData, xDataLengthBytes, xSpace, xRequiredSpace );
  if( xReturn > ( size_t ) 0 )
  {
    traceSTREAM_BUFFER_SEND( xStreamBuffer, xReturn );
    /* Was a task waiting for the data? */
    if( prvBytesInBuffer( pxStreamBuffer ) >= pxStreamBuffer->xTriggerLevelBytes )
    {
      sbSEND_COMPLETED( pxStreamBuffer );
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
  }
  else
  {
    mtCOVERAGE_TEST_MARKER();
    traceSTREAM_BUFFER_SEND_FAILED( xStreamBuffer );
  }
  return xReturn;
}
References configASSERT, mtCOVERAGE_TEST_MARKER, pdFALSE, prvBytesInBuffer(), prvWriteMessageToBuffer(), sbBYTES_TO_STORE_MESSAGE_LENGTH, sbFLAGS_IS_MESSAGE_BUFFER, sbSEND_COMPLETED, taskENTER_CRITICAL, taskEXIT_CRITICAL, traceBLOCKING_ON_STREAM_BUFFER_SEND, traceSTREAM_BUFFER_SEND, traceSTREAM_BUFFER_SEND_FAILED, StreamBufferDef_t::ucFlags, vTaskSetTimeOutState(), xStreamBufferSpacesAvailable(), xTaskCheckForTimeOut(), xTaskGetCurrentTaskHandle(), xTaskNotifyStateClear(), xTaskNotifyWait(), StreamBufferDef_t::xTaskWaitingToSend, and StreamBufferDef_t::xTriggerLevelBytes.
xStreamBufferSendCompletedFromISR()
BaseType_t xStreamBufferSendCompletedFromISR (StreamBufferHandle_t xStreamBuffer, BaseType_t * pxHigherPriorityTaskWoken)
Definition at line 1028 of file stream_buffer.c.
{
StreamBuffer_t * const pxStreamBuffer = xStreamBuffer;
BaseType_t xReturn;
UBaseType_t uxSavedInterruptStatus;
  configASSERT( pxStreamBuffer );
  uxSavedInterruptStatus = ( UBaseType_t ) portSET_INTERRUPT_MASK_FROM_ISR();
  {
    if( ( pxStreamBuffer )->xTaskWaitingToReceive != NULL )
    {
      ( void ) xTaskNotifyFromISR( ( pxStreamBuffer )->xTaskWaitingToReceive,
                     ( uint32_t ) 0,
                     eNoAction,
                     pxHigherPriorityTaskWoken );
      ( pxStreamBuffer )->xTaskWaitingToReceive = NULL;
      xReturn = pdTRUE;
    }
    else
    {
      xReturn = pdFALSE;
    }
  }
  portCLEAR_INTERRUPT_MASK_FROM_ISR( uxSavedInterruptStatus );
  return xReturn;
}
References configASSERT, eNoAction, pdFALSE, pdTRUE, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, and xTaskNotifyFromISR.
xStreamBufferSendFromISR()
size_t xStreamBufferSendFromISR (StreamBufferHandle_t xStreamBuffer, const void * pvTxData, size_t xDataLengthBytes, BaseType_t *const pxHigherPriorityTaskWoken)
Definition at line 610 of file stream_buffer.c.
{
StreamBuffer_t * const pxStreamBuffer = xStreamBuffer;
size_t xReturn, xSpace;
size_t xRequiredSpace = xDataLengthBytes;
  configASSERT( pvTxData );
  configASSERT( pxStreamBuffer );
  /* This send function is used to write to both message buffers and stream
  buffers.  If this is a message buffer then the space needed must be
  increased by the amount of bytes needed to store the length of the
  message. */
  if( ( pxStreamBuffer->ucFlags & sbFLAGS_IS_MESSAGE_BUFFER ) != ( uint8_t ) 0 )
  {
    xRequiredSpace += sbBYTES_TO_STORE_MESSAGE_LENGTH;
  }
  else
  {
    mtCOVERAGE_TEST_MARKER();
  }
  xSpace = xStreamBufferSpacesAvailable( pxStreamBuffer );
  xReturn = prvWriteMessageToBuffer( pxStreamBuffer, pvTxData, xDataLengthBytes, xSpace, xRequiredSpace );
  if( xReturn > ( size_t ) 0 )
  {
    /* Was a task waiting for the data? */
    if( prvBytesInBuffer( pxStreamBuffer ) >= pxStreamBuffer->xTriggerLevelBytes )
    {
      sbSEND_COMPLETE_FROM_ISR( pxStreamBuffer, pxHigherPriorityTaskWoken );
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
  }
  else
  {
    mtCOVERAGE_TEST_MARKER();
  }
  traceSTREAM_BUFFER_SEND_FROM_ISR( xStreamBuffer, xReturn );
  return xReturn;
}
References configASSERT, mtCOVERAGE_TEST_MARKER, prvBytesInBuffer(), prvWriteMessageToBuffer(), sbBYTES_TO_STORE_MESSAGE_LENGTH, sbFLAGS_IS_MESSAGE_BUFFER, sbSEND_COMPLETE_FROM_ISR, traceSTREAM_BUFFER_SEND_FROM_ISR, StreamBufferDef_t::ucFlags, xStreamBufferSpacesAvailable(), and StreamBufferDef_t::xTriggerLevelBytes.
xStreamBufferSetTriggerLevel()
BaseType_t xStreamBufferSetTriggerLevel (StreamBufferHandle_t xStreamBuffer, size_t xTriggerLevel)
Definition at line 441 of file stream_buffer.c.
{
StreamBuffer_t * const pxStreamBuffer = xStreamBuffer;
BaseType_t xReturn;
  configASSERT( pxStreamBuffer );
  /* It is not valid for the trigger level to be 0. */
  if( xTriggerLevel == ( size_t ) 0 )
  {
    xTriggerLevel = ( size_t ) 1;
  }
  /* The trigger level is the number of bytes that must be in the stream
  buffer before a task that is waiting for data is unblocked. */
  if( xTriggerLevel <= pxStreamBuffer->xLength )
  {
    pxStreamBuffer->xTriggerLevelBytes = xTriggerLevel;
    xReturn = pdPASS;
  }
  else
  {
    xReturn = pdFALSE;
  }
  return xReturn;
}
References configASSERT, pdFALSE, pdPASS, and StreamBufferDef_t::xTriggerLevelBytes.
xStreamBufferSpacesAvailable()
size_t xStreamBufferSpacesAvailable (StreamBufferHandle_t xStreamBuffer)
Definition at line 470 of file stream_buffer.c.
{
const StreamBuffer_t * const pxStreamBuffer = xStreamBuffer;
size_t xSpace;
  configASSERT( pxStreamBuffer );
  xSpace = pxStreamBuffer->xLength + pxStreamBuffer->xTail;
  xSpace -= pxStreamBuffer->xHead;
  xSpace -= ( size_t ) 1;
  if( xSpace >= pxStreamBuffer->xLength )
  {
    xSpace -= pxStreamBuffer->xLength;
  }
  else
  {
    mtCOVERAGE_TEST_MARKER();
  }
  return xSpace;
}
References configASSERT, mtCOVERAGE_TEST_MARKER, StreamBufferDef_t::xHead, StreamBufferDef_t::xLength, and StreamBufferDef_t::xTail.
Referenced by xStreamBufferIsFull(), xStreamBufferSend(), and xStreamBufferSendFromISR().