NUCLEO-G0B1RE Examples: NUCLEO-G0B1RE/FreeRTOS_Queues/Middlewares/Third_Party/FreeRTOS/Source/tasks.c File Reference
tasks.c File Reference
#include <stdlib.h>
#include <string.h>
#include "FreeRTOS.h"
#include "task.h"
#include "timers.h"
#include "stack_macros.h"
Data Structures
struct tskTaskControlBlock
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define taskYIELD_IF_USING_PREEMPTION()
#define taskNOT_WAITING_NOTIFICATION ((uint8_t) 0)
#define taskWAITING_NOTIFICATION ((uint8_t) 1)
#define taskNOTIFICATION_RECEIVED ((uint8_t) 2)
#define tskSTACK_FILL_BYTE (0xa5U)
#define tskDYNAMICALLY_ALLOCATED_STACK_AND_TCB ((uint8_t) 0)
#define tskSTATICALLY_ALLOCATED_STACK_ONLY ((uint8_t) 1)
#define tskSTATICALLY_ALLOCATED_STACK_AND_TCB ((uint8_t) 2)
#define tskSET_NEW_STACKS_TO_KNOWN_VALUE 0
#define tskRUNNING_CHAR ('X')
#define tskBLOCKED_CHAR ('B')
#define tskREADY_CHAR ('R')
#define tskDELETED_CHAR ('D')
#define tskSUSPENDED_CHAR ('S')
#define configIDLE_TASK_NAME "IDLE"
#define taskRECORD_READY_PRIORITY(uxPriority)
#define taskSELECT_HIGHEST_PRIORITY_TASK()
#define taskRESET_READY_PRIORITY(uxPriority)
#define portRESET_READY_PRIORITY(uxPriority, uxTopReadyPriority)
#define taskSWITCH_DELAYED_LISTS()
#define prvAddTaskToReadyList(pxTCB)
#define prvGetTCBFromHandle(pxHandle) (((pxHandle) == NULL) ? pxCurrentTCB : (pxHandle))
#define taskEVENT_LIST_ITEM_VALUE_IN_USE 0x80000000UL
Typedefs
typedef struct tskTaskControlBlock tskTCB
typedef tskTCB TCB_t
Functions
static void prvInitialiseTaskLists (static void prvCheckTasksWaitingTermination void)
Utility task that simply returns pdTRUE if the task referenced by xTask is currently in the Suspended state, or pdFALSE if the task referenced by xTask is in any other state.
static void prvAddNewTaskToReadyList (TCB_t *pxNewTCB)
void vTaskStartScheduler (void)
void vTaskEndScheduler (void)
void vTaskSuspendAll (void)
BaseType_t xTaskResumeAll (void)
TickType_t xTaskGetTickCount (void)
TickType_t xTaskGetTickCountFromISR (void)
UBaseType_t uxTaskGetNumberOfTasks (void)
char * pcTaskGetName (TaskHandle_t xTaskToQuery)
BaseType_t xTaskCatchUpTicks (TickType_t xTicksToCatchUp)
BaseType_t xTaskIncrementTick (void)
void vTaskSwitchContext (void)
void vTaskPlaceOnEventList (List_t *const pxEventList, const TickType_t xTicksToWait)
void vTaskPlaceOnUnorderedEventList (List_t *pxEventList, const TickType_t xItemValue, const TickType_t xTicksToWait)
BaseType_t xTaskRemoveFromEventList (const List_t *const pxEventList)
void vTaskRemoveFromUnorderedEventList (ListItem_t *pxEventListItem, const TickType_t xItemValue)
void vTaskSetTimeOutState (TimeOut_t *const pxTimeOut)
void vTaskInternalSetTimeOutState (TimeOut_t *const pxTimeOut)
BaseType_t xTaskCheckForTimeOut (TimeOut_t *const pxTimeOut, TickType_t *const pxTicksToWait)
void vTaskMissedYield (void)
static portTASK_FUNCTION (prvIdleTask, pvParameters)
static void prvInitialiseTaskLists (void)
static void prvCheckTasksWaitingTermination (void)
static void prvResetNextTaskUnblockTime (void)
TickType_t uxTaskResetEventItemValue (void)
static void prvAddCurrentTaskToDelayedList (TickType_t xTicksToWait, const BaseType_t xCanBlockIndefinitely)
Variables
PRIVILEGED_DATA TCB_t *volatile pxCurrentTCB = NULL
static PRIVILEGED_DATA List_t pxReadyTasksLists [configMAX_PRIORITIES]
static PRIVILEGED_DATA List_t xDelayedTaskList1
static PRIVILEGED_DATA List_t xDelayedTaskList2
static PRIVILEGED_DATA List_t *volatile pxDelayedTaskList
static PRIVILEGED_DATA List_t *volatile pxOverflowDelayedTaskList
static PRIVILEGED_DATA List_t xPendingReadyList
static PRIVILEGED_DATA volatile UBaseType_t uxCurrentNumberOfTasks = (UBaseType_t) 0U
static PRIVILEGED_DATA volatile TickType_t xTickCount = (TickType_t) configINITIAL_TICK_COUNT
static PRIVILEGED_DATA volatile UBaseType_t uxTopReadyPriority = tskIDLE_PRIORITY
static PRIVILEGED_DATA volatile BaseType_t xSchedulerRunning = pdFALSE
static PRIVILEGED_DATA volatile TickType_t xPendedTicks = (TickType_t) 0U
static PRIVILEGED_DATA volatile BaseType_t xYieldPending = pdFALSE
static PRIVILEGED_DATA volatile BaseType_t xNumOfOverflows = (BaseType_t) 0
static PRIVILEGED_DATA UBaseType_t uxTaskNumber = (UBaseType_t) 0U
static PRIVILEGED_DATA volatile TickType_t xNextTaskUnblockTime = (TickType_t) 0U
static PRIVILEGED_DATA TaskHandle_t xIdleTaskHandle = NULL
static PRIVILEGED_DATA volatile UBaseType_t uxSchedulerSuspended = (UBaseType_t) pdFALSE
Macro Definition Documentation
configIDLE_TASK_NAME
#define configIDLE_TASK_NAME "IDLE"
Definition at line 112 of file tasks.c.
Referenced by vTaskStartScheduler().
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 35 of file tasks.c.
portRESET_READY_PRIORITY
#define portRESET_READY_PRIORITY (uxPriority, uxTopReadyPriority)
Definition at line 155 of file tasks.c.
Referenced by prvAddCurrentTaskToDelayedList().
prvAddTaskToReadyList
#define prvAddTaskToReadyList (pxTCB)
Value:
  traceMOVED_TASK_TO_READY_STATE( pxTCB );                            \
  taskRECORD_READY_PRIORITY( ( pxTCB )->uxPriority );                       \
  vListInsertEnd( &( pxReadyTasksLists[ ( pxTCB )->uxPriority ] ), &( ( pxTCB )->xStateListItem ) ); \
  tracePOST_MOVED_TASK_TO_READY_STATE( pxTCB )
Definition at line 217 of file tasks.c.
 */
#define prvAddTaskToReadyList(pxTCB)                                \
  traceMOVED_TASK_TO_READY_STATE( pxTCB );                            \
  taskRECORD_READY_PRIORITY( ( pxTCB )->uxPriority );                       \
  vListInsertEnd( &( pxReadyTasksLists[ ( pxTCB )->uxPriority ] ), &( ( pxTCB )->xStateListItem ) ); \
Referenced by prvAddNewTaskToReadyList(), vTaskRemoveFromUnorderedEventList(), xTaskIncrementTick(), xTaskRemoveFromEventList(), and xTaskResumeAll().
prvGetTCBFromHandle
#define prvGetTCBFromHandle (pxHandle) (((pxHandle) == NULL) ? pxCurrentTCB : (pxHandle))
Definition at line 230 of file tasks.c.
Referenced by pcTaskGetName().
taskEVENT_LIST_ITEM_VALUE_IN_USE
#define taskEVENT_LIST_ITEM_VALUE_IN_USE 0x80000000UL
Definition at line 243 of file tasks.c.
Referenced by vTaskPlaceOnUnorderedEventList(), and vTaskRemoveFromUnorderedEventList().
taskNOT_WAITING_NOTIFICATION
#define taskNOT_WAITING_NOTIFICATION ((uint8_t) 0)
Definition at line 68 of file tasks.c.
taskNOTIFICATION_RECEIVED
#define taskNOTIFICATION_RECEIVED ((uint8_t) 2)
Definition at line 70 of file tasks.c.
taskRECORD_READY_PRIORITY
#define taskRECORD_READY_PRIORITY (uxPriority)
Value:
  {                                                 \
    if( ( uxPriority ) > uxTopReadyPriority )                           \
    {                                               \
      uxTopReadyPriority = ( uxPriority );                            \
    }                                               \
  } /* taskRECORD_READY_PRIORITY */
Definition at line 123 of file tasks.c.
  #define taskRECORD_READY_PRIORITY( uxPriority )                           \
  {                                                 \
    if( ( uxPriority ) > uxTopReadyPriority )                           \
    {                                               \
      uxTopReadyPriority = ( uxPriority );                            \
    }                                               \
  } /* taskRECORD_READY_PRIORITY */
taskRESET_READY_PRIORITY
#define taskRESET_READY_PRIORITY (uxPriority)
Definition at line 154 of file tasks.c.
taskSELECT_HIGHEST_PRIORITY_TASK
#define taskSELECT_HIGHEST_PRIORITY_TASK ()
Value:
  {                                                 \
  UBaseType_t uxTopPriority = uxTopReadyPriority;                           \
                                                    \
    /* Find the highest priority queue that contains ready tasks. */                \
    while( listLIST_IS_EMPTY( &( pxReadyTasksLists[ uxTopPriority ] ) ) )             \
    {                                               \
      configASSERT( uxTopPriority );                                \
      --uxTopPriority;                                      \
    }                                               \
                                                    \
    /* listGET_OWNER_OF_NEXT_ENTRY indexes through the list, so the tasks of            \
    the same priority get an equal share of the processor time. */                  \
    listGET_OWNER_OF_NEXT_ENTRY( pxCurrentTCB, &( pxReadyTasksLists[ uxTopPriority ] ) );     \
    uxTopReadyPriority = uxTopPriority;                               \
  } /* taskSELECT_HIGHEST_PRIORITY_TASK */
Definition at line 133 of file tasks.c.
  #define taskSELECT_HIGHEST_PRIORITY_TASK()                              \
  {                                                 \
  UBaseType_t uxTopPriority = uxTopReadyPriority;                           \
                                                    \
    /* Find the highest priority queue that contains ready tasks. */                \
    while( listLIST_IS_EMPTY( &( pxReadyTasksLists[ uxTopPriority ] ) ) )             \
    {                                               \
      configASSERT( uxTopPriority );                                \
      --uxTopPriority;                                      \
    }                                               \
                                                    \
    /* listGET_OWNER_OF_NEXT_ENTRY indexes through the list, so the tasks of            \
    the same priority get an equal share of the processor time. */                  \
    listGET_OWNER_OF_NEXT_ENTRY( pxCurrentTCB, &( pxReadyTasksLists[ uxTopPriority ] ) );     \
    uxTopReadyPriority = uxTopPriority;                               \
Referenced by vTaskSwitchContext().
taskSWITCH_DELAYED_LISTS
#define taskSWITCH_DELAYED_LISTS ()
Value:
{                                                 \
  List_t *pxTemp;                                         \
                                                  \
  /* The delayed tasks list should be empty when the lists are switched. */           \
  configASSERT( ( listLIST_IS_EMPTY( pxDelayedTaskList ) ) );                   \
                                                  \
  pxTemp = pxDelayedTaskList;                                   \
  pxDelayedTaskList = pxOverflowDelayedTaskList;                          \
  pxOverflowDelayedTaskList = pxTemp;                               \
  xNumOfOverflows++;                                        \
  prvResetNextTaskUnblockTime();                                  \
}
Definition at line 197 of file tasks.c.
count overflows. */
#define taskSWITCH_DELAYED_LISTS()                                  \
{                                                 \
  List_t *pxTemp;                                         \
                                                  \
  /* The delayed tasks list should be empty when the lists are switched. */           \
  configASSERT( ( listLIST_IS_EMPTY( pxDelayedTaskList ) ) );                   \
                                                  \
  pxTemp = pxDelayedTaskList;                                   \
  pxDelayedTaskList = pxOverflowDelayedTaskList;                          \
  pxOverflowDelayedTaskList = pxTemp;                               \
  xNumOfOverflows++;                                        \
  prvResetNextTaskUnblockTime();                                  \
Referenced by xTaskIncrementTick().
taskWAITING_NOTIFICATION
#define taskWAITING_NOTIFICATION ((uint8_t) 1)
Definition at line 69 of file tasks.c.
taskYIELD_IF_USING_PREEMPTION
#define taskYIELD_IF_USING_PREEMPTION ()
Definition at line 62 of file tasks.c.
Referenced by prvAddNewTaskToReadyList(), and xTaskResumeAll().
tskBLOCKED_CHAR
#define tskBLOCKED_CHAR ('B')
Definition at line 96 of file tasks.c.
tskDELETED_CHAR
#define tskDELETED_CHAR ('D')
Definition at line 98 of file tasks.c.
tskDYNAMICALLY_ALLOCATED_STACK_AND_TCB
#define tskDYNAMICALLY_ALLOCATED_STACK_AND_TCB ((uint8_t) 0)
Definition at line 79 of file tasks.c.
tskREADY_CHAR
#define tskREADY_CHAR ('R')
Definition at line 97 of file tasks.c.
tskRUNNING_CHAR
#define tskRUNNING_CHAR ('X')
Definition at line 95 of file tasks.c.
tskSET_NEW_STACKS_TO_KNOWN_VALUE
#define tskSET_NEW_STACKS_TO_KNOWN_VALUE 0
Definition at line 89 of file tasks.c.
tskSTACK_FILL_BYTE
#define tskSTACK_FILL_BYTE (0xa5U)
Definition at line 76 of file tasks.c.
tskSTATICALLY_ALLOCATED_STACK_AND_TCB
#define tskSTATICALLY_ALLOCATED_STACK_AND_TCB ((uint8_t) 2)
Definition at line 81 of file tasks.c.
tskSTATICALLY_ALLOCATED_STACK_ONLY
#define tskSTATICALLY_ALLOCATED_STACK_ONLY ((uint8_t) 1)
Definition at line 80 of file tasks.c.
tskSUSPENDED_CHAR
#define tskSUSPENDED_CHAR ('S')
Definition at line 99 of file tasks.c.
Typedef Documentation
TCB_t
typedef tskTCB TCB_t
Definition at line 332 of file tasks.c.
tskTCB
typedef struct tskTaskControlBlock tskTCB
Function Documentation
pcTaskGetName()
char * pcTaskGetName (TaskHandle_t xTaskToQuery)
Definition at line 2357 of file tasks.c.
{
TCB_t *pxTCB;
  /* If null is passed in here then the name of the calling task is being
  queried. */
  pxTCB = prvGetTCBFromHandle( xTaskToQuery );
  configASSERT( pxTCB );
  return &( pxTCB->pcTaskName[ 0 ] );
References configASSERT, tskTaskControlBlock::pcTaskName, and prvGetTCBFromHandle.
Referenced by osThreadGetName().
portTASK_FUNCTION()
static portTASK_FUNCTION (prvIdleTask , pvParameters) static
THIS IS THE RTOS IDLE TASK - WHICH IS CREATED AUTOMATICALLY WHEN THE SCHEDULER IS STARTED.
Definition at line 3391 of file tasks.c.
{
  /* Stop warnings. */
  ( void ) pvParameters;
  /* In case a task that has a secure context deletes itself, in which case
  the idle task is responsible for deleting the task's secure context, if
  any. */
  portALLOCATE_SECURE_CONTEXT( configMINIMAL_SECURE_STACK_SIZE );
  for( ;; )
  {
    /* See if any tasks have deleted themselves - if so then the idle task
    is responsible for freeing the deleted task's TCB and stack. */
    prvCheckTasksWaitingTermination();
    #if ( configUSE_PREEMPTION == 0 )
    {
      /* If we are not using preemption we keep forcing a task switch to
      see if any other task has become available.  If we are using
      preemption we don't need to do this as any task becoming available
      will automatically get the processor anyway. */
      taskYIELD();
    }
    #endif /* configUSE_PREEMPTION */
    #if ( ( configUSE_PREEMPTION == 1 ) && ( configIDLE_SHOULD_YIELD == 1 ) )
    {
      /* When using preemption tasks of equal priority will be
      timesliced.  If a task that is sharing the idle priority is ready
      to run then the idle task should yield before the end of the
      timeslice.
      A critical region is not required here as we are just reading from
      the list, and an occasional incorrect value will not matter.  If
      the ready list at the idle priority contains more than one task
      then a task other than the idle task is ready to execute. */
      if( listCURRENT_LIST_LENGTH( &( pxReadyTasksLists[ tskIDLE_PRIORITY ] ) ) > ( UBaseType_t ) 1 )
      {
        taskYIELD();
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
    #endif /* ( ( configUSE_PREEMPTION == 1 ) && ( configIDLE_SHOULD_YIELD == 1 ) ) */
    #if ( configUSE_IDLE_HOOK == 1 )
    {
      extern void vApplicationIdleHook( void );
      /* Call the user defined function from within the idle task.  This
      allows the application designer to add background functionality
      without the overhead of a separate task.
      NOTE: vApplicationIdleHook() MUST NOT, UNDER ANY CIRCUMSTANCES,
      CALL A FUNCTION THAT MIGHT BLOCK. */
      vApplicationIdleHook();
    }
    #endif /* configUSE_IDLE_HOOK */
    /* This conditional compilation should use inequality to 0, not equality
    to 1.  This is to ensure portSUPPRESS_TICKS_AND_SLEEP() is called when
    user defined low power mode implementations require
    configUSE_TICKLESS_IDLE to be set to a value other than 1. */
    #if ( configUSE_TICKLESS_IDLE != 0 )
    {
    TickType_t xExpectedIdleTime;
      /* It is not desirable to suspend then resume the scheduler on
      each iteration of the idle task.  Therefore, a preliminary
      test of the expected idle time is performed without the
      scheduler suspended.  The result here is not necessarily
      valid. */
      xExpectedIdleTime = prvGetExpectedIdleTime();
      if( xExpectedIdleTime >= configEXPECTED_IDLE_TIME_BEFORE_SLEEP )
      {
        vTaskSuspendAll();
        {
          /* Now the scheduler is suspended, the expected idle
          time can be sampled again, and this time its value can
          be used. */
          configASSERT( xNextTaskUnblockTime >= xTickCount );
          xExpectedIdleTime = prvGetExpectedIdleTime();
          /* Define the following macro to set xExpectedIdleTime to 0
          if the application does not want
          portSUPPRESS_TICKS_AND_SLEEP() to be called. */
          configPRE_SUPPRESS_TICKS_AND_SLEEP_PROCESSING( xExpectedIdleTime );
          if( xExpectedIdleTime >= configEXPECTED_IDLE_TIME_BEFORE_SLEEP )
          {
            traceLOW_POWER_IDLE_BEGIN();
            portSUPPRESS_TICKS_AND_SLEEP( xExpectedIdleTime );
            traceLOW_POWER_IDLE_END();
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
        }
        ( void ) xTaskResumeAll();
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
    #endif /* configUSE_TICKLESS_IDLE */
  }
References configASSERT, configEXPECTED_IDLE_TIME_BEFORE_SLEEP, configPRE_SUPPRESS_TICKS_AND_SLEEP_PROCESSING, listCURRENT_LIST_LENGTH, mtCOVERAGE_TEST_MARKER, portALLOCATE_SECURE_CONTEXT, portSUPPRESS_TICKS_AND_SLEEP, prvCheckTasksWaitingTermination(), pxReadyTasksLists, taskYIELD, traceLOW_POWER_IDLE_BEGIN, traceLOW_POWER_IDLE_END, tskIDLE_PRIORITY, vApplicationIdleHook(), vTaskSuspendAll(), xNextTaskUnblockTime, xTaskResumeAll(), and xTickCount.
prvAddCurrentTaskToDelayedList()
static void prvAddCurrentTaskToDelayedList (TickType_t xTicksToWait, const BaseType_t xCanBlockIndefinitely) static
Definition at line 5176 of file tasks.c.
{
TickType_t xTimeToWake;
const TickType_t xConstTickCount = xTickCount;
  #if( INCLUDE_xTaskAbortDelay == 1 )
  {
    /* About to enter a delayed list, so ensure the ucDelayAborted flag is
    reset to pdFALSE so it can be detected as having been set to pdTRUE
    when the task leaves the Blocked state. */
    pxCurrentTCB->ucDelayAborted = pdFALSE;
  }
  #endif
  /* Remove the task from the ready list before adding it to the blocked list
  as the same list item is used for both lists. */
  if( uxListRemove( &( pxCurrentTCB->xStateListItem ) ) == ( UBaseType_t ) 0 )
  {
    /* The current task must be in a ready list, so there is no need to
    check, and the port reset macro can be called directly. */
    portRESET_READY_PRIORITY( pxCurrentTCB->uxPriority, uxTopReadyPriority ); /*lint !e931 pxCurrentTCB cannot change as it is the calling task.  pxCurrentTCB->uxPriority and uxTopReadyPriority cannot change as called with scheduler suspended or in a critical section. */
  }
  else
  {
    mtCOVERAGE_TEST_MARKER();
  }
  #if ( INCLUDE_vTaskSuspend == 1 )
  {
    if( ( xTicksToWait == portMAX_DELAY ) && ( xCanBlockIndefinitely != pdFALSE ) )
    {
      /* Add the task to the suspended task list instead of a delayed task
      list to ensure it is not woken by a timing event.  It will block
      indefinitely. */
      vListInsertEnd( &xSuspendedTaskList, &( pxCurrentTCB->xStateListItem ) );
    }
    else
    {
      /* Calculate the time at which the task should be woken if the event
      does not occur.  This may overflow but this doesn't matter, the
      kernel will manage it correctly. */
      xTimeToWake = xConstTickCount + xTicksToWait;
      /* The list item will be inserted in wake time order. */
      listSET_LIST_ITEM_VALUE( &( pxCurrentTCB->xStateListItem ), xTimeToWake );
      if( xTimeToWake < xConstTickCount )
      {
        /* Wake time has overflowed.  Place this item in the overflow
        list. */
        vListInsert( pxOverflowDelayedTaskList, &( pxCurrentTCB->xStateListItem ) );
      }
      else
      {
        /* The wake time has not overflowed, so the current block list
        is used. */
        vListInsert( pxDelayedTaskList, &( pxCurrentTCB->xStateListItem ) );
        /* If the task entering the blocked state was placed at the
        head of the list of blocked tasks then xNextTaskUnblockTime
        needs to be updated too. */
        if( xTimeToWake < xNextTaskUnblockTime )
        {
          xNextTaskUnblockTime = xTimeToWake;
        }
        else
        {
          mtCOVERAGE_TEST_MARKER();
        }
      }
    }
  }
  #else /* INCLUDE_vTaskSuspend */
  {
    /* Calculate the time at which the task should be woken if the event
    does not occur.  This may overflow but this doesn't matter, the kernel
    will manage it correctly. */
    xTimeToWake = xConstTickCount + xTicksToWait;
    /* The list item will be inserted in wake time order. */
    listSET_LIST_ITEM_VALUE( &( pxCurrentTCB->xStateListItem ), xTimeToWake );
    if( xTimeToWake < xConstTickCount )
    {
      /* Wake time has overflowed.  Place this item in the overflow list. */
      vListInsert( pxOverflowDelayedTaskList, &( pxCurrentTCB->xStateListItem ) );
    }
    else
    {
      /* The wake time has not overflowed, so the current block list is used. */
      vListInsert( pxDelayedTaskList, &( pxCurrentTCB->xStateListItem ) );
      /* If the task entering the blocked state was placed at the head of the
      list of blocked tasks then xNextTaskUnblockTime needs to be updated
      too. */
      if( xTimeToWake < xNextTaskUnblockTime )
      {
        xNextTaskUnblockTime = xTimeToWake;
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
    /* Avoid compiler warning when INCLUDE_vTaskSuspend is not 1. */
    ( void ) xCanBlockIndefinitely;
  }
  #endif /* INCLUDE_vTaskSuspend */
References listSET_LIST_ITEM_VALUE, mtCOVERAGE_TEST_MARKER, pdFALSE, portMAX_DELAY, portRESET_READY_PRIORITY, pxCurrentTCB, pxDelayedTaskList, pxOverflowDelayedTaskList, uxListRemove(), tskTaskControlBlock::uxPriority, uxTopReadyPriority, vListInsert(), vListInsertEnd(), xNextTaskUnblockTime, tskTaskControlBlock::xStateListItem, and xTickCount.
Referenced by vTaskPlaceOnEventList(), and vTaskPlaceOnUnorderedEventList().
prvAddNewTaskToReadyList()
static void prvAddNewTaskToReadyList (TCB_t * pxNewTCB) static
Definition at line 1076 of file tasks.c.
{
  /* Ensure interrupts don't access the task lists while the lists are being
  updated. */
  taskENTER_CRITICAL();
  {
    uxCurrentNumberOfTasks++;
    if( pxCurrentTCB == NULL )
    {
      /* There are no other tasks, or all the other tasks are in
      the suspended state - make this the current task. */
      pxCurrentTCB = pxNewTCB;
      if( uxCurrentNumberOfTasks == ( UBaseType_t ) 1 )
      {
        /* This is the first task to be created so do the preliminary
        initialisation required.  We will not recover if this call
        fails, but we will report the failure. */
        prvInitialiseTaskLists();
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
    else
    {
      /* If the scheduler is not already running, make this task the
      current task if it is the highest priority task to be created
      so far. */
      if( xSchedulerRunning == pdFALSE )
      {
        if( pxCurrentTCB->uxPriority <= pxNewTCB->uxPriority )
        {
          pxCurrentTCB = pxNewTCB;
        }
        else
        {
          mtCOVERAGE_TEST_MARKER();
        }
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
    uxTaskNumber++;
    #if ( configUSE_TRACE_FACILITY == 1 )
    {
      /* Add a counter into the TCB for tracing only. */
      pxNewTCB->uxTCBNumber = uxTaskNumber;
    }
    #endif /* configUSE_TRACE_FACILITY */
    traceTASK_CREATE( pxNewTCB );
    prvAddTaskToReadyList( pxNewTCB );
    portSETUP_TCB( pxNewTCB );
  }
  taskEXIT_CRITICAL();
  if( xSchedulerRunning != pdFALSE )
  {
    /* If the created task is of a higher priority than the current task
    then it should run now. */
    if( pxCurrentTCB->uxPriority < pxNewTCB->uxPriority )
    {
      taskYIELD_IF_USING_PREEMPTION();
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
  }
  else
  {
    mtCOVERAGE_TEST_MARKER();
  }
References mtCOVERAGE_TEST_MARKER, pdFALSE, portSETUP_TCB, prvAddTaskToReadyList, prvInitialiseTaskLists(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskYIELD_IF_USING_PREEMPTION, traceTASK_CREATE, uxCurrentNumberOfTasks, tskTaskControlBlock::uxPriority, uxTaskNumber, and xSchedulerRunning.
prvCheckTasksWaitingTermination()
static void prvCheckTasksWaitingTermination (void) static
THIS FUNCTION IS CALLED FROM THE RTOS IDLE TASK
Definition at line 3638 of file tasks.c.
{
  #if ( INCLUDE_vTaskDelete == 1 )
  {
    TCB_t *pxTCB;
    /* uxDeletedTasksWaitingCleanUp is used to prevent taskENTER_CRITICAL()
    being called too often in the idle task. */
    while( uxDeletedTasksWaitingCleanUp > ( UBaseType_t ) 0U )
    {
      taskENTER_CRITICAL();
      {
        pxTCB = listGET_OWNER_OF_HEAD_ENTRY( ( &xTasksWaitingTermination ) ); /*lint !e9079 void * is used as this macro is used with timers and co-routines too.  Alignment is known to be fine as the type of the pointer stored and retrieved is the same. */
        ( void ) uxListRemove( &( pxTCB->xStateListItem ) );
        --uxCurrentNumberOfTasks;
        --uxDeletedTasksWaitingCleanUp;
      }
      taskEXIT_CRITICAL();
      prvDeleteTCB( pxTCB );
    }
  }
  #endif /* INCLUDE_vTaskDelete */
References listGET_OWNER_OF_HEAD_ENTRY, taskENTER_CRITICAL, taskEXIT_CRITICAL, uxCurrentNumberOfTasks, uxListRemove(), and tskTaskControlBlock::xStateListItem.
Referenced by portTASK_FUNCTION().
prvInitialiseTaskLists() [1/2]
static void prvInitialiseTaskLists (static void prvCheckTasksWaitingTermination void) static
Utility task that simply returns pdTRUE if the task referenced by xTask is currently in the Suspended state, or pdFALSE if the task referenced by xTask is in any other state.
Definition at line 439 of file tasks.c.
  {
  TCB_t *pxNewTCB;
  TaskHandle_t xReturn;
    configASSERT( puxStackBuffer != NULL );
    configASSERT( pxTaskBuffer != NULL );
    #if( configASSERT_DEFINED == 1 )
    {
      /* Sanity check that the size of the structure used to declare a
      variable of type StaticTask_t equals the size of the real task
      structure. */
      volatile size_t xSize = sizeof( StaticTask_t );
      configASSERT( xSize == sizeof( TCB_t ) );
      ( void ) xSize; /* Prevent lint warning when configASSERT() is not used. */
    }
    #endif /* configASSERT_DEFINED */
    if( ( pxTaskBuffer != NULL ) && ( puxStackBuffer != NULL ) )
    {
      /* The memory used for the task's TCB and stack are passed into this
      function - use them. */
      pxNewTCB = ( TCB_t * ) pxTaskBuffer; /*lint !e740 !e9087 Unusual cast is ok as the structures are designed to have the same alignment, and the size is checked by an assert. */
      pxNewTCB->pxStack = ( StackType_t * ) puxStackBuffer;
      #if( tskSTATIC_AND_DYNAMIC_ALLOCATION_POSSIBLE != 0 ) /*lint !e731 !e9029 Macro has been consolidated for readability reasons. */
      {
        /* Tasks can be created statically or dynamically, so note this
        task was created statically in case the task is later deleted. */
        pxNewTCB->ucStaticallyAllocated = tskSTATICALLY_ALLOCATED_STACK_AND_TCB;
      }
      #endif /* tskSTATIC_AND_DYNAMIC_ALLOCATION_POSSIBLE */
      prvInitialiseNewTask( pxTaskCode, pcName, ulStackDepth, pvParameters, uxPriority, &xReturn, pxNewTCB, NULL );
      prvAddNewTaskToReadyList( pxNewTCB );
    }
    else
    {
      xReturn = NULL;
    }
    return xReturn;
  }
#endif /* SUPPORT_STATIC_ALLOCATION */
/*-----------------------------------------------------------*/
#if((portUSING_MPU_WRAPPERS == 1) && (configSUPPORT_STATIC_ALLOCATION == 1))
  BaseType_t xTaskCreateRestrictedStatic( const TaskParameters_t * const pxTaskDefinition, TaskHandle_t *pxCreatedTask )
  {
  TCB_t *pxNewTCB;
  BaseType_t xReturn = errCOULD_NOT_ALLOCATE_REQUIRED_MEMORY;
    configASSERT( pxTaskDefinition->puxStackBuffer != NULL );
    configASSERT( pxTaskDefinition->pxTaskBuffer != NULL );
    if( ( pxTaskDefinition->puxStackBuffer != NULL ) && ( pxTaskDefinition->pxTaskBuffer != NULL ) )
    {
      /* Allocate space for the TCB.  Where the memory comes from depends
      on the implementation of the port malloc function and whether or
      not static allocation is being used. */
      pxNewTCB = ( TCB_t * ) pxTaskDefinition->pxTaskBuffer;
      /* Store the stack location in the TCB. */
      pxNewTCB->pxStack = pxTaskDefinition->puxStackBuffer;
      #if( tskSTATIC_AND_DYNAMIC_ALLOCATION_POSSIBLE != 0 )
      {
        /* Tasks can be created statically or dynamically, so note this
        task was created statically in case the task is later deleted. */
        pxNewTCB->ucStaticallyAllocated = tskSTATICALLY_ALLOCATED_STACK_AND_TCB;
      }
      #endif /* tskSTATIC_AND_DYNAMIC_ALLOCATION_POSSIBLE */
      prvInitialiseNewTask( pxTaskDefinition->pvTaskCode,
                  pxTaskDefinition->pcName,
                  ( uint32_t ) pxTaskDefinition->usStackDepth,
                  pxTaskDefinition->pvParameters,
                  pxTaskDefinition->uxPriority,
                  pxCreatedTask, pxNewTCB,
                  pxTaskDefinition->xRegions );
      prvAddNewTaskToReadyList( pxNewTCB );
      xReturn = pdPASS;
    }
    return xReturn;
  }
#endif /* (portUSING_MPU_WRAPPERS == 1) && (configSUPPORT_STATIC_ALLOCATION == 1) */
/*-----------------------------------------------------------*/
#if((portUSING_MPU_WRAPPERS == 1) && (configSUPPORT_DYNAMIC_ALLOCATION == 1))
  BaseType_t xTaskCreateRestricted( const TaskParameters_t * const pxTaskDefinition, TaskHandle_t *pxCreatedTask )
  {
  TCB_t *pxNewTCB;
  BaseType_t xReturn = errCOULD_NOT_ALLOCATE_REQUIRED_MEMORY;
    configASSERT( pxTaskDefinition->puxStackBuffer );
    if( pxTaskDefinition->puxStackBuffer != NULL )
    {
      /* Allocate space for the TCB.  Where the memory comes from depends
      on the implementation of the port malloc function and whether or
      not static allocation is being used. */
      pxNewTCB = ( TCB_t * ) pvPortMalloc( sizeof( TCB_t ) );
      if( pxNewTCB != NULL )
      {
        /* Store the stack location in the TCB. */
        pxNewTCB->pxStack = pxTaskDefinition->puxStackBuffer;
        #if( tskSTATIC_AND_DYNAMIC_ALLOCATION_POSSIBLE != 0 )
        {
          /* Tasks can be created statically or dynamically, so note
          this task had a statically allocated stack in case it is
          later deleted.  The TCB was allocated dynamically. */
          pxNewTCB->ucStaticallyAllocated = tskSTATICALLY_ALLOCATED_STACK_ONLY;
        }
        #endif /* tskSTATIC_AND_DYNAMIC_ALLOCATION_POSSIBLE */
        prvInitialiseNewTask( pxTaskDefinition->pvTaskCode,
                    pxTaskDefinition->pcName,
                    ( uint32_t ) pxTaskDefinition->usStackDepth,
                    pxTaskDefinition->pvParameters,
                    pxTaskDefinition->uxPriority,
                    pxCreatedTask, pxNewTCB,
                    pxTaskDefinition->xRegions );
        prvAddNewTaskToReadyList( pxNewTCB );
        xReturn = pdPASS;
      }
    }
    return xReturn;
  }
#endif /* portUSING_MPU_WRAPPERS */
/*-----------------------------------------------------------*/
#if(configSUPPORT_DYNAMIC_ALLOCATION == 1)
  BaseType_t xTaskCreate( TaskFunction_t pxTaskCode,
              const char * const pcName,    /*lint !e971 Unqualified char types are allowed for strings and single characters only. */
              const configSTACK_DEPTH_TYPE usStackDepth,
              void * const pvParameters,
              UBaseType_t uxPriority,
              TaskHandle_t * const pxCreatedTask )
  {
  TCB_t *pxNewTCB;
  BaseType_t xReturn;
    /* If the stack grows down then allocate the stack then the TCB so the stack
    does not grow into the TCB.  Likewise if the stack grows up then allocate
    the TCB then the stack. */
    #if( portSTACK_GROWTH > 0 )
    {
      /* Allocate space for the TCB.  Where the memory comes from depends on
      the implementation of the port malloc function and whether or not static
      allocation is being used. */
      pxNewTCB = ( TCB_t * ) pvPortMalloc( sizeof( TCB_t ) );
      if( pxNewTCB != NULL )
      {
        /* Allocate space for the stack used by the task being created.
        The base of the stack memory stored in the TCB so the task can
        be deleted later if required. */
        pxNewTCB->pxStack = ( StackType_t * ) pvPortMalloc( ( ( ( size_t ) usStackDepth ) * sizeof( StackType_t ) ) ); /*lint !e961 MISRA exception as the casts are only redundant for some ports. */
        if( pxNewTCB->pxStack == NULL )
        {
          /* Could not allocate the stack.  Delete the allocated TCB. */
          vPortFree( pxNewTCB );
          pxNewTCB = NULL;
        }
      }
    }
    #else /* portSTACK_GROWTH */
    {
    StackType_t *pxStack;
      /* Allocate space for the stack used by the task being created. */
      pxStack = pvPortMalloc( ( ( ( size_t ) usStackDepth ) * sizeof( StackType_t ) ) ); /*lint !e9079 All values returned by pvPortMalloc() have at least the alignment required by the MCU's stack and this allocation is the stack. */
      if( pxStack != NULL )
      {
        /* Allocate space for the TCB. */
        pxNewTCB = ( TCB_t * ) pvPortMalloc( sizeof( TCB_t ) ); /*lint !e9087 !e9079 All values returned by pvPortMalloc() have at least the alignment required by the MCU's stack, and the first member of TCB_t is always a pointer to the task's stack. */
        if( pxNewTCB != NULL )
        {
          /* Store the stack location in the TCB. */
          pxNewTCB->pxStack = pxStack;
        }
        else
        {
          /* The stack cannot be used as the TCB was not created.  Free
          it again. */
          vPortFree( pxStack );
        }
      }
      else
      {
        pxNewTCB = NULL;
      }
    }
    #endif /* portSTACK_GROWTH */
    if( pxNewTCB != NULL )
    {
      #if( tskSTATIC_AND_DYNAMIC_ALLOCATION_POSSIBLE != 0 ) /*lint !e9029 !e731 Macro has been consolidated for readability reasons. */
      {
        /* Tasks can be created statically or dynamically, so note this
        task was created dynamically in case it is later deleted. */
        pxNewTCB->ucStaticallyAllocated = tskDYNAMICALLY_ALLOCATED_STACK_AND_TCB;
      }
      #endif /* tskSTATIC_AND_DYNAMIC_ALLOCATION_POSSIBLE */
      prvInitialiseNewTask( pxTaskCode, pcName, ( uint32_t ) usStackDepth, pvParameters, uxPriority, pxCreatedTask, pxNewTCB, NULL );
      prvAddNewTaskToReadyList( pxNewTCB );
      xReturn = pdPASS;
    }
    else
    {
      xReturn = errCOULD_NOT_ALLOCATE_REQUIRED_MEMORY;
    }
    return xReturn;
  }
#endif /* configSUPPORT_DYNAMIC_ALLOCATION */
/*-----------------------------------------------------------*/
static void prvInitialiseNewTask(TaskFunction_t pxTaskCode,
                  const char * const pcName,    /*lint !e971 Unqualified char types are allowed for strings and single characters only. */
                  const uint32_t ulStackDepth,
                  void * const pvParameters,
                  UBaseType_t uxPriority,
                  TaskHandle_t * const pxCreatedTask,
                  TCB_t *pxNewTCB,
                  const MemoryRegion_t * const xRegions )
{
StackType_t *pxTopOfStack;
UBaseType_t x;
  #if( portUSING_MPU_WRAPPERS == 1 )
    /* Should the task be created in privileged mode? */
    BaseType_t xRunPrivileged;
    if( ( uxPriority & portPRIVILEGE_BIT ) != 0U )
    {
      xRunPrivileged = pdTRUE;
    }
    else
    {
      xRunPrivileged = pdFALSE;
    }
    uxPriority &= ~portPRIVILEGE_BIT;
  #endif /* portUSING_MPU_WRAPPERS == 1 */
  /* Avoid dependency on memset() if it is not required. */
  #if( tskSET_NEW_STACKS_TO_KNOWN_VALUE == 1 )
  {
    /* Fill the stack with a known value to assist debugging. */
    ( void ) memset( pxNewTCB->pxStack, ( int ) tskSTACK_FILL_BYTE, ( size_t ) ulStackDepth * sizeof( StackType_t ) );
  }
  #endif /* tskSET_NEW_STACKS_TO_KNOWN_VALUE */
  /* Calculate the top of stack address.  This depends on whether the stack
  grows from high memory to low (as per the 80x86) or vice versa.
  portSTACK_GROWTH is used to make the result positive or negative as required
  by the port. */
  #if( portSTACK_GROWTH < 0 )
  {
    pxTopOfStack = &( pxNewTCB->pxStack[ ulStackDepth - ( uint32_t ) 1 ] );
    pxTopOfStack = ( StackType_t * ) ( ( ( portPOINTER_SIZE_TYPE ) pxTopOfStack ) & ( ~( ( portPOINTER_SIZE_TYPE ) portBYTE_ALIGNMENT_MASK ) ) ); /*lint !e923 !e9033 !e9078 MISRA exception.  Avoiding casts between pointers and integers is not practical.  Size differences accounted for using portPOINTER_SIZE_TYPE type.  Checked by assert(). */
    /* Check the alignment of the calculated top of stack is correct. */
    configASSERT( ( ( ( portPOINTER_SIZE_TYPE ) pxTopOfStack & ( portPOINTER_SIZE_TYPE ) portBYTE_ALIGNMENT_MASK ) == 0UL ) );
    #if( configRECORD_STACK_HIGH_ADDRESS == 1 )
    {
      /* Also record the stack's high address, which may assist
      debugging. */
      pxNewTCB->pxEndOfStack = pxTopOfStack;
    }
    #endif /* configRECORD_STACK_HIGH_ADDRESS */
  }
  #else /* portSTACK_GROWTH */
  {
    pxTopOfStack = pxNewTCB->pxStack;
    /* Check the alignment of the stack buffer is correct. */
    configASSERT( ( ( ( portPOINTER_SIZE_TYPE ) pxNewTCB->pxStack & ( portPOINTER_SIZE_TYPE ) portBYTE_ALIGNMENT_MASK ) == 0UL ) );
    /* The other extreme of the stack space is required if stack checking is
    performed. */
    pxNewTCB->pxEndOfStack = pxNewTCB->pxStack + ( ulStackDepth - ( uint32_t ) 1 );
  }
  #endif /* portSTACK_GROWTH */
  /* Store the task name in the TCB. */
  if( pcName != NULL )
  {
    for( x = ( UBaseType_t ) 0; x < ( UBaseType_t ) configMAX_TASK_NAME_LEN; x++ )
    {
      pxNewTCB->pcTaskName[ x ] = pcName[ x ];
      /* Don't copy all configMAX_TASK_NAME_LEN if the string is shorter than
      configMAX_TASK_NAME_LEN characters just in case the memory after the
      string is not accessible (extremely unlikely). */
      if( pcName[ x ] == ( char ) 0x00 )
      {
        break;
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
    /* Ensure the name string is terminated in the case that the string length
    was greater or equal to configMAX_TASK_NAME_LEN. */
    pxNewTCB->pcTaskName[ configMAX_TASK_NAME_LEN - 1 ] = '\0';
  }
  else
  {
    /* The task has not been given a name, so just ensure there is a NULL
    terminator when it is read out. */
    pxNewTCB->pcTaskName[ 0 ] = 0x00;
  }
  /* This is used as an array index so must ensure it's not too large.  First
  remove the privilege bit if one is present. */
  if( uxPriority >= ( UBaseType_t ) configMAX_PRIORITIES )
  {
    uxPriority = ( UBaseType_t ) configMAX_PRIORITIES - ( UBaseType_t ) 1U;
  }
  else
  {
    mtCOVERAGE_TEST_MARKER();
  }
  pxNewTCB->uxPriority = uxPriority;
  #if ( configUSE_MUTEXES == 1 )
  {
    pxNewTCB->uxBasePriority = uxPriority;
    pxNewTCB->uxMutexesHeld = 0;
  }
  #endif /* configUSE_MUTEXES */
  vListInitialiseItem( &( pxNewTCB->xStateListItem ) );
  vListInitialiseItem( &( pxNewTCB->xEventListItem ) );
  /* Set the pxNewTCB as a link back from the ListItem_t.  This is so we can get
  back to the containing TCB from a generic item in a list. */
  listSET_LIST_ITEM_OWNER( &( pxNewTCB->xStateListItem ), pxNewTCB );
  /* Event lists are always in priority order. */
  listSET_LIST_ITEM_VALUE( &( pxNewTCB->xEventListItem ), ( TickType_t ) configMAX_PRIORITIES - ( TickType_t ) uxPriority ); /*lint !e961 MISRA exception as the casts are only redundant for some ports. */
  listSET_LIST_ITEM_OWNER( &( pxNewTCB->xEventListItem ), pxNewTCB );
  #if ( portCRITICAL_NESTING_IN_TCB == 1 )
  {
    pxNewTCB->uxCriticalNesting = ( UBaseType_t ) 0U;
  }
  #endif /* portCRITICAL_NESTING_IN_TCB */
  #if ( configUSE_APPLICATION_TASK_TAG == 1 )
  {
    pxNewTCB->pxTaskTag = NULL;
  }
  #endif /* configUSE_APPLICATION_TASK_TAG */
  #if ( configGENERATE_RUN_TIME_STATS == 1 )
  {
    pxNewTCB->ulRunTimeCounter = 0UL;
  }
  #endif /* configGENERATE_RUN_TIME_STATS */
  #if ( portUSING_MPU_WRAPPERS == 1 )
  {
    vPortStoreTaskMPUSettings( &( pxNewTCB->xMPUSettings ), xRegions, pxNewTCB->pxStack, ulStackDepth );
  }
  #else
  {
    /* Avoid compiler warning about unreferenced parameter. */
    ( void ) xRegions;
  }
  #endif
  #if( configNUM_THREAD_LOCAL_STORAGE_POINTERS != 0 )
  {
    for( x = 0; x < ( UBaseType_t ) configNUM_THREAD_LOCAL_STORAGE_POINTERS; x++ )
    {
      pxNewTCB->pvThreadLocalStoragePointers[ x ] = NULL;
    }
  }
  #endif
  #if ( configUSE_TASK_NOTIFICATIONS == 1 )
  {
    pxNewTCB->ulNotifiedValue = 0;
    pxNewTCB->ucNotifyState = taskNOT_WAITING_NOTIFICATION;
  }
  #endif
  #if ( configUSE_NEWLIB_REENTRANT == 1 )
  {
    /* Initialise this task's Newlib reent structure.
    See the third party link http://www.nadler.com/embedded/newlibAndFreeRTOS.html
    for additional information. */
    _REENT_INIT_PTR( ( &( pxNewTCB->xNewLib_reent ) ) );
  }
  #endif
  #if( INCLUDE_xTaskAbortDelay == 1 )
  {
    pxNewTCB->ucDelayAborted = pdFALSE;
  }
  #endif
  /* Initialize the TCB stack to look as if the task was already running,
  but had been interrupted by the scheduler.  The return address is set
  to the start of the task function. Once the stack has been initialised
  the top of stack variable is updated. */
  #if( portUSING_MPU_WRAPPERS == 1 )
  {
    /* If the port has capability to detect stack overflow,
    pass the stack end address to the stack initialization
    function as well. */
    #if( portHAS_STACK_OVERFLOW_CHECKING == 1 )
    {
      #if( portSTACK_GROWTH < 0 )
      {
        pxNewTCB->pxTopOfStack = pxPortInitialiseStack( pxTopOfStack, pxNewTCB->pxStack, pxTaskCode, pvParameters, xRunPrivileged );
      }
      #else /* portSTACK_GROWTH */
      {
        pxNewTCB->pxTopOfStack = pxPortInitialiseStack( pxTopOfStack, pxNewTCB->pxEndOfStack, pxTaskCode, pvParameters, xRunPrivileged );
      }
      #endif /* portSTACK_GROWTH */
    }
    #else /* portHAS_STACK_OVERFLOW_CHECKING */
    {
      pxNewTCB->pxTopOfStack = pxPortInitialiseStack( pxTopOfStack, pxTaskCode, pvParameters, xRunPrivileged );
    }
    #endif /* portHAS_STACK_OVERFLOW_CHECKING */
  }
  #else /* portUSING_MPU_WRAPPERS */
  {
    /* If the port has capability to detect stack overflow,
    pass the stack end address to the stack initialization
    function as well. */
    #if( portHAS_STACK_OVERFLOW_CHECKING == 1 )
    {
      #if( portSTACK_GROWTH < 0 )
      {
        pxNewTCB->pxTopOfStack = pxPortInitialiseStack( pxTopOfStack, pxNewTCB->pxStack, pxTaskCode, pvParameters );
      }
      #else /* portSTACK_GROWTH */
      {
        pxNewTCB->pxTopOfStack = pxPortInitialiseStack( pxTopOfStack, pxNewTCB->pxEndOfStack, pxTaskCode, pvParameters );
      }
      #endif /* portSTACK_GROWTH */
    }
    #else /* portHAS_STACK_OVERFLOW_CHECKING */
    {
      pxNewTCB->pxTopOfStack = pxPortInitialiseStack( pxTopOfStack, pxTaskCode, pvParameters );
    }
    #endif /* portHAS_STACK_OVERFLOW_CHECKING */
  }
  #endif /* portUSING_MPU_WRAPPERS */
  if( pxCreatedTask != NULL )
  {
    /* Pass the handle out in an anonymous way.  The handle can be used to
    change the created task's priority, delete the created task, etc.*/
    *pxCreatedTask = ( TaskHandle_t ) pxNewTCB;
  }
  else
  {
    mtCOVERAGE_TEST_MARKER();
  }
prvInitialiseTaskLists() [2/2]
static void prvInitialiseTaskLists (void) static
Definition at line 3606 of file tasks.c.
{
UBaseType_t uxPriority;
  for( uxPriority = ( UBaseType_t ) 0U; uxPriority < ( UBaseType_t ) configMAX_PRIORITIES; uxPriority++ )
  {
    vListInitialise( &( pxReadyTasksLists[ uxPriority ] ) );
  }
  vListInitialise( &xDelayedTaskList1 );
  vListInitialise( &xDelayedTaskList2 );
  vListInitialise( &xPendingReadyList );
  #if ( INCLUDE_vTaskDelete == 1 )
  {
    vListInitialise( &xTasksWaitingTermination );
  }
  #endif /* INCLUDE_vTaskDelete */
  #if ( INCLUDE_vTaskSuspend == 1 )
  {
    vListInitialise( &xSuspendedTaskList );
  }
  #endif /* INCLUDE_vTaskSuspend */
  /* Start with pxDelayedTaskList using list1 and the pxOverflowDelayedTaskList
  using list2. */
  pxDelayedTaskList = &xDelayedTaskList1;
  pxOverflowDelayedTaskList = &xDelayedTaskList2;
References configMAX_PRIORITIES, pxDelayedTaskList, pxOverflowDelayedTaskList, pxReadyTasksLists, vListInitialise(), xDelayedTaskList1, xDelayedTaskList2, and xPendingReadyList.
Referenced by prvAddNewTaskToReadyList().
prvResetNextTaskUnblockTime()
static void prvResetNextTaskUnblockTime (void) static
Definition at line 3942 of file tasks.c.
{
TCB_t *pxTCB;
  if( listLIST_IS_EMPTY( pxDelayedTaskList ) != pdFALSE )
  {
    /* The new current delayed list is empty.  Set xNextTaskUnblockTime to
    the maximum possible value so it is extremely unlikely that the
    if( xTickCount >= xNextTaskUnblockTime ) test will pass until
    there is an item in the delayed list. */
    xNextTaskUnblockTime = portMAX_DELAY;
  }
  else
  {
    /* The new current delayed list is not empty, get the value of
    the item at the head of the delayed list.  This is the time at
    which the task at the head of the delayed list should be removed
    from the Blocked state. */
    ( pxTCB ) = listGET_OWNER_OF_HEAD_ENTRY( pxDelayedTaskList ); /*lint !e9079 void * is used as this macro is used with timers and co-routines too.  Alignment is known to be fine as the type of the pointer stored and retrieved is the same. */
    xNextTaskUnblockTime = listGET_LIST_ITEM_VALUE( &( ( pxTCB )->xStateListItem ) );
  }
References listGET_LIST_ITEM_VALUE, listGET_OWNER_OF_HEAD_ENTRY, listLIST_IS_EMPTY, pdFALSE, portMAX_DELAY, pxDelayedTaskList, and xNextTaskUnblockTime.
Referenced by vTaskRemoveFromUnorderedEventList(), xTaskRemoveFromEventList(), and xTaskResumeAll().
uxTaskGetNumberOfTasks()
UBaseType_t uxTaskGetNumberOfTasks (void)
Definition at line 2349 of file tasks.c.
{
  /* A critical section is not required because the variables are of type
  BaseType_t. */
  return uxCurrentNumberOfTasks;
References uxCurrentNumberOfTasks.
Referenced by osThreadEnumerate(), and osThreadGetCount().
uxTaskResetEventItemValue()
TickType_t uxTaskResetEventItemValue (void)
Definition at line 4601 of file tasks.c.
{
TickType_t uxReturn;
  uxReturn = listGET_LIST_ITEM_VALUE( &( pxCurrentTCB->xEventListItem ) );
  /* Reset the event list item to its normal value - so it can be used with
  queues and semaphores. */
  listSET_LIST_ITEM_VALUE( &( pxCurrentTCB->xEventListItem ), ( ( TickType_t ) configMAX_PRIORITIES - ( TickType_t ) pxCurrentTCB->uxPriority ) ); /*lint !e961 MISRA exception as the casts are only redundant for some ports. */
  return uxReturn;
References configMAX_PRIORITIES, listGET_LIST_ITEM_VALUE, listSET_LIST_ITEM_VALUE, pxCurrentTCB, tskTaskControlBlock::uxPriority, and tskTaskControlBlock::xEventListItem.
Referenced by xEventGroupSync(), and xEventGroupWaitBits().
vTaskEndScheduler()
void vTaskEndScheduler (void)
Definition at line 2098 of file tasks.c.
{
  /* Stop the scheduler interrupts and call the portable scheduler end
  routine so the original ISRs can be restored if necessary.  The port
  layer must ensure interrupts enable bit is left in the correct state. */
  portDISABLE_INTERRUPTS();
  xSchedulerRunning = pdFALSE;
  vPortEndScheduler();
References pdFALSE, portDISABLE_INTERRUPTS, vPortEndScheduler(), and xSchedulerRunning.
vTaskInternalSetTimeOutState()
void vTaskInternalSetTimeOutState (TimeOut_t *const pxTimeOut)
Definition at line 3265 of file tasks.c.
{
  /* For internal use only as it does not use a critical section. */
  pxTimeOut->xOverflowCount = xNumOfOverflows;
  pxTimeOut->xTimeOnEntering = xTickCount;
References xNumOfOverflows, xTIME_OUT::xOverflowCount, xTickCount, and xTIME_OUT::xTimeOnEntering.
Referenced by xQueueGenericSend(), xQueuePeek(), xQueueReceive(), xQueueSemaphoreTake(), and xTaskCheckForTimeOut().
vTaskMissedYield()
void vTaskMissedYield (void)
Definition at line 3336 of file tasks.c.
{
  xYieldPending = pdTRUE;
References pdTRUE, and xYieldPending.
Referenced by prvUnlockQueue().
vTaskPlaceOnEventList()
void vTaskPlaceOnEventList (List_t *const pxEventList, const TickType_t xTicksToWait)
Definition at line 3063 of file tasks.c.
{
  configASSERT( pxEventList );
  /* THIS FUNCTION MUST BE CALLED WITH EITHER INTERRUPTS DISABLED OR THE
  SCHEDULER SUSPENDED AND THE QUEUE BEING ACCESSED LOCKED. */
  /* Place the event list item of the TCB in the appropriate event list.
  This is placed in the list in priority order so the highest priority task
  is the first to be woken by the event.  The queue that contains the event
  list is locked, preventing simultaneous access from interrupts. */
  vListInsert( pxEventList, &( pxCurrentTCB->xEventListItem ) );
  prvAddCurrentTaskToDelayedList( xTicksToWait, pdTRUE );
References configASSERT, pdTRUE, prvAddCurrentTaskToDelayedList(), pxCurrentTCB, vListInsert(), and tskTaskControlBlock::xEventListItem.
Referenced by xQueueGenericSend(), xQueuePeek(), xQueueReceive(), and xQueueSemaphoreTake().
vTaskPlaceOnUnorderedEventList()
void vTaskPlaceOnUnorderedEventList (List_t * pxEventList, const TickType_t xItemValue, const TickType_t xTicksToWait)
Definition at line 3080 of file tasks.c.
{
  configASSERT( pxEventList );
  /* THIS FUNCTION MUST BE CALLED WITH THE SCHEDULER SUSPENDED.  It is used by
  the event groups implementation. */
  configASSERT( uxSchedulerSuspended != 0 );
  /* Store the item value in the event list item.  It is safe to access the
  event list item here as interrupts won't access the event list item of a
  task that is not in the Blocked state. */
  listSET_LIST_ITEM_VALUE( &( pxCurrentTCB->xEventListItem ), xItemValue | taskEVENT_LIST_ITEM_VALUE_IN_USE );
  /* Place the event list item of the TCB at the end of the appropriate event
  list.  It is safe to access the event list here because it is part of an
  event group implementation - and interrupts don't access event groups
  directly (instead they access them indirectly by pending function calls to
  the task level). */
  vListInsertEnd( pxEventList, &( pxCurrentTCB->xEventListItem ) );
  prvAddCurrentTaskToDelayedList( xTicksToWait, pdTRUE );
References configASSERT, listSET_LIST_ITEM_VALUE, pdTRUE, prvAddCurrentTaskToDelayedList(), pxCurrentTCB, taskEVENT_LIST_ITEM_VALUE_IN_USE, uxSchedulerSuspended, vListInsertEnd(), and tskTaskControlBlock::xEventListItem.
Referenced by xEventGroupSync(), and xEventGroupWaitBits().
vTaskRemoveFromUnorderedEventList()
void vTaskRemoveFromUnorderedEventList (ListItem_t * pxEventListItem, const TickType_t xItemValue)
Definition at line 3205 of file tasks.c.
{
TCB_t *pxUnblockedTCB;
  /* THIS FUNCTION MUST BE CALLED WITH THE SCHEDULER SUSPENDED.  It is used by
  the event flags implementation. */
  configASSERT( uxSchedulerSuspended != pdFALSE );
  /* Store the new item value in the event list. */
  listSET_LIST_ITEM_VALUE( pxEventListItem, xItemValue | taskEVENT_LIST_ITEM_VALUE_IN_USE );
  /* Remove the event list form the event flag.  Interrupts do not access
  event flags. */
  pxUnblockedTCB = listGET_LIST_ITEM_OWNER( pxEventListItem ); /*lint !e9079 void * is used as this macro is used with timers and co-routines too.  Alignment is known to be fine as the type of the pointer stored and retrieved is the same. */
  configASSERT( pxUnblockedTCB );
  ( void ) uxListRemove( pxEventListItem );
  #if( configUSE_TICKLESS_IDLE != 0 )
  {
    /* If a task is blocked on a kernel object then xNextTaskUnblockTime
    might be set to the blocked task's time out time.  If the task is
    unblocked for a reason other than a timeout xNextTaskUnblockTime is
    normally left unchanged, because it is automatically reset to a new
    value when the tick count equals xNextTaskUnblockTime.  However if
    tickless idling is used it might be more important to enter sleep mode
    at the earliest possible time - so reset xNextTaskUnblockTime here to
    ensure it is updated at the earliest possible time. */
    prvResetNextTaskUnblockTime();
  }
  #endif
  /* Remove the task from the delayed list and add it to the ready list.  The
  scheduler is suspended so interrupts will not be accessing the ready
  lists. */
  ( void ) uxListRemove( &( pxUnblockedTCB->xStateListItem ) );
  prvAddTaskToReadyList( pxUnblockedTCB );
  if( pxUnblockedTCB->uxPriority > pxCurrentTCB->uxPriority )
  {
    /* The unblocked task has a priority above that of the calling task, so
    a context switch is required.  This function is called with the
    scheduler suspended so xYieldPending is set so the context switch
    occurs immediately that the scheduler is resumed (unsuspended). */
    xYieldPending = pdTRUE;
  }
References configASSERT, listGET_LIST_ITEM_OWNER, listSET_LIST_ITEM_VALUE, pdFALSE, pdTRUE, prvAddTaskToReadyList, prvResetNextTaskUnblockTime(), pxCurrentTCB, taskEVENT_LIST_ITEM_VALUE_IN_USE, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, tskTaskControlBlock::xStateListItem, and xYieldPending.
Referenced by vEventGroupDelete(), and xEventGroupSetBits().
vTaskSetTimeOutState()
void vTaskSetTimeOutState (TimeOut_t *const pxTimeOut)
Definition at line 3253 of file tasks.c.
{
  configASSERT( pxTimeOut );
  taskENTER_CRITICAL();
  {
    pxTimeOut->xOverflowCount = xNumOfOverflows;
    pxTimeOut->xTimeOnEntering = xTickCount;
  }
  taskEXIT_CRITICAL();
References configASSERT, taskENTER_CRITICAL, taskEXIT_CRITICAL, xNumOfOverflows, xTIME_OUT::xOverflowCount, xTickCount, and xTIME_OUT::xTimeOnEntering.
Referenced by xStreamBufferSend().
vTaskStartScheduler()
void vTaskStartScheduler (void)
Definition at line 1974 of file tasks.c.
{
BaseType_t xReturn;
  /* Add the idle task at the lowest priority. */
  #if( configSUPPORT_STATIC_ALLOCATION == 1 )
  {
    StaticTask_t *pxIdleTaskTCBBuffer = NULL;
    StackType_t *pxIdleTaskStackBuffer = NULL;
    uint32_t ulIdleTaskStackSize;
    /* The Idle task is created using user provided RAM - obtain the
    address of the RAM then create the idle task. */
    vApplicationGetIdleTaskMemory( &pxIdleTaskTCBBuffer, &pxIdleTaskStackBuffer, &ulIdleTaskStackSize );
    xIdleTaskHandle = xTaskCreateStatic(  prvIdleTask,
                        configIDLE_TASK_NAME,
                        ulIdleTaskStackSize,
                        ( void * ) NULL, /*lint !e961.  The cast is not redundant for all compilers. */
                        portPRIVILEGE_BIT, /* In effect ( tskIDLE_PRIORITY | portPRIVILEGE_BIT ), but tskIDLE_PRIORITY is zero. */
                        pxIdleTaskStackBuffer,
                        pxIdleTaskTCBBuffer ); /*lint !e961 MISRA exception, justified as it is not a redundant explicit cast to all supported compilers. */
    if( xIdleTaskHandle != NULL )
    {
      xReturn = pdPASS;
    }
    else
    {
      xReturn = pdFAIL;
    }
  }
  #else
  {
    /* The Idle task is being created using dynamically allocated RAM. */
    xReturn = xTaskCreate(  prvIdleTask,
                configIDLE_TASK_NAME,
                configMINIMAL_STACK_SIZE,
                ( void * ) NULL,
                portPRIVILEGE_BIT, /* In effect ( tskIDLE_PRIORITY | portPRIVILEGE_BIT ), but tskIDLE_PRIORITY is zero. */
                &xIdleTaskHandle ); /*lint !e961 MISRA exception, justified as it is not a redundant explicit cast to all supported compilers. */
  }
  #endif /* configSUPPORT_STATIC_ALLOCATION */
  #if ( configUSE_TIMERS == 1 )
  {
    if( xReturn == pdPASS )
    {
      xReturn = xTimerCreateTimerTask();
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
  }
  #endif /* configUSE_TIMERS */
  if( xReturn == pdPASS )
  {
    /* freertos_tasks_c_additions_init() should only be called if the user
    definable macro FREERTOS_TASKS_C_ADDITIONS_INIT() is defined, as that is
    the only macro called by the function. */
    #ifdef FREERTOS_TASKS_C_ADDITIONS_INIT
    {
      freertos_tasks_c_additions_init();
    }
    #endif
    /* Interrupts are turned off here, to ensure a tick does not occur
    before or during the call to xPortStartScheduler().  The stacks of
    the created tasks contain a status word with interrupts switched on
    so interrupts will automatically get re-enabled when the first task
    starts to run. */
    portDISABLE_INTERRUPTS();
    #if ( configUSE_NEWLIB_REENTRANT == 1 )
    {
      /* Switch Newlib's _impure_ptr variable to point to the _reent
      structure specific to the task that will run first.
      See the third party link http://www.nadler.com/embedded/newlibAndFreeRTOS.html
      for additional information. */
      _impure_ptr = &( pxCurrentTCB->xNewLib_reent );
    }
    #endif /* configUSE_NEWLIB_REENTRANT */
    xNextTaskUnblockTime = portMAX_DELAY;
    xSchedulerRunning = pdTRUE;
    xTickCount = ( TickType_t ) configINITIAL_TICK_COUNT;
    /* If configGENERATE_RUN_TIME_STATS is defined then the following
    macro must be defined to configure the timer/counter used to generate
    the run time counter time base.   NOTE:  If configGENERATE_RUN_TIME_STATS
    is set to 0 and the following line fails to build then ensure you do not
    have portCONFIGURE_TIMER_FOR_RUN_TIME_STATS() defined in your
    FreeRTOSConfig.h file. */
    portCONFIGURE_TIMER_FOR_RUN_TIME_STATS();
    traceTASK_SWITCHED_IN();
    /* Setting up the timer tick is hardware specific and thus in the
    portable interface. */
    if( xPortStartScheduler() != pdFALSE )
    {
      /* Should not reach here as if the scheduler is running the
      function will not return. */
    }
    else
    {
      /* Should only reach here if a task calls xTaskEndScheduler(). */
    }
  }
  else
  {
    /* This line will only be reached if the kernel could not be started,
    because there was not enough FreeRTOS heap to create the idle task
    or the timer task. */
    configASSERT( xReturn != errCOULD_NOT_ALLOCATE_REQUIRED_MEMORY );
  }
  /* Prevent compiler warnings if INCLUDE_xTaskGetIdleTaskHandle is set to 0,
  meaning xIdleTaskHandle is not used anywhere else. */
  ( void ) xIdleTaskHandle;
References configASSERT, configIDLE_TASK_NAME, configINITIAL_TICK_COUNT, configMINIMAL_STACK_SIZE, errCOULD_NOT_ALLOCATE_REQUIRED_MEMORY, mtCOVERAGE_TEST_MARKER, pdFAIL, pdFALSE, pdPASS, pdTRUE, portCONFIGURE_TIMER_FOR_RUN_TIME_STATS, portDISABLE_INTERRUPTS, portMAX_DELAY, portPRIVILEGE_BIT, pxCurrentTCB, traceTASK_SWITCHED_IN, xIdleTaskHandle, xNextTaskUnblockTime, xPortStartScheduler(), xSchedulerRunning, xTickCount, and xTimerCreateTimerTask().
Referenced by osKernelStart().
vTaskSuspendAll()
void vTaskSuspendAll (void)
Definition at line 2109 of file tasks.c.
{
  /* A critical section is not required as the variable is of type
  BaseType_t.  Please read Richard Barry's reply in the following link to a
  post in the FreeRTOS support forum before reporting this as a bug! -
  http://goo.gl/wu4acr */
  /* portSOFRWARE_BARRIER() is only implemented for emulated/simulated ports that
  do not otherwise exhibit real time behaviour. */
  portSOFTWARE_BARRIER();
  /* The scheduler is suspended if uxSchedulerSuspended is non-zero.  An increment
  is used to allow calls to vTaskSuspendAll() to nest. */
  ++uxSchedulerSuspended;
  /* Enforces ordering for ports and optimised compilers that may otherwise place
  the above increment elsewhere. */
  portMEMORY_BARRIER();
References portMEMORY_BARRIER, portSOFTWARE_BARRIER, and uxSchedulerSuspended.
Referenced by osKernelLock(), osKernelRestoreLock(), osThreadEnumerate(), portTASK_FUNCTION(), pvPortMalloc(), vEventGroupDelete(), vPortFree(), vPortGetHeapStats(), xEventGroupSetBits(), xEventGroupSync(), xEventGroupWaitBits(), xQueueGenericSend(), xQueuePeek(), xQueueReceive(), xQueueSemaphoreTake(), and xTaskCatchUpTicks().
vTaskSwitchContext()
void vTaskSwitchContext (void)
Definition at line 2988 of file tasks.c.
{
  if( uxSchedulerSuspended != ( UBaseType_t ) pdFALSE )
  {
    /* The scheduler is currently suspended - do not allow a context
    switch. */
    xYieldPending = pdTRUE;
  }
  else
  {
    xYieldPending = pdFALSE;
    traceTASK_SWITCHED_OUT();
    #if ( configGENERATE_RUN_TIME_STATS == 1 )
    {
      #ifdef portALT_GET_RUN_TIME_COUNTER_VALUE
        portALT_GET_RUN_TIME_COUNTER_VALUE( ulTotalRunTime );
      #else
        ulTotalRunTime = portGET_RUN_TIME_COUNTER_VALUE();
      #endif
      /* Add the amount of time the task has been running to the
      accumulated time so far.  The time the task started running was
      stored in ulTaskSwitchedInTime.  Note that there is no overflow
      protection here so count values are only valid until the timer
      overflows.  The guard against negative values is to protect
      against suspect run time stat counter implementations - which
      are provided by the application, not the kernel. */
      if( ulTotalRunTime > ulTaskSwitchedInTime )
      {
        pxCurrentTCB->ulRunTimeCounter += ( ulTotalRunTime - ulTaskSwitchedInTime );
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
      ulTaskSwitchedInTime = ulTotalRunTime;
    }
    #endif /* configGENERATE_RUN_TIME_STATS */
    /* Check for stack overflow, if configured. */
    taskCHECK_FOR_STACK_OVERFLOW();
    /* Before the currently running task is switched out, save its errno. */
    #if( configUSE_POSIX_ERRNO == 1 )
    {
      pxCurrentTCB->iTaskErrno = FreeRTOS_errno;
    }
    #endif
    /* Select a new task to run using either the generic C or port
    optimised asm code. */
    taskSELECT_HIGHEST_PRIORITY_TASK(); /*lint !e9079 void * is used as this macro is used with timers and co-routines too.  Alignment is known to be fine as the type of the pointer stored and retrieved is the same. */
    traceTASK_SWITCHED_IN();
    /* After the new task is switched in, update the global errno. */
    #if( configUSE_POSIX_ERRNO == 1 )
    {
      FreeRTOS_errno = pxCurrentTCB->iTaskErrno;
    }
    #endif
    #if ( configUSE_NEWLIB_REENTRANT == 1 )
    {
      /* Switch Newlib's _impure_ptr variable to point to the _reent
      structure specific to this task.
      See the third party link http://www.nadler.com/embedded/newlibAndFreeRTOS.html
      for additional information. */
      _impure_ptr = &( pxCurrentTCB->xNewLib_reent );
    }
    #endif /* configUSE_NEWLIB_REENTRANT */
  }
References mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, pxCurrentTCB, taskCHECK_FOR_STACK_OVERFLOW, taskSELECT_HIGHEST_PRIORITY_TASK, traceTASK_SWITCHED_IN, traceTASK_SWITCHED_OUT, uxSchedulerSuspended, and xYieldPending.
Referenced by xPortStartScheduler().
xTaskCatchUpTicks()
BaseType_t xTaskCatchUpTicks (TickType_t xTicksToCatchUp)
Definition at line 2608 of file tasks.c.
{
BaseType_t xYieldRequired = pdFALSE;
  /* Must not be called with the scheduler suspended as the implementation
  relies on xPendedTicks being wound down to 0 in xTaskResumeAll(). */
  configASSERT( uxSchedulerSuspended == 0 );
  /* Use xPendedTicks to mimic xTicksToCatchUp number of ticks occurring when
  the scheduler is suspended so the ticks are executed in xTaskResumeAll(). */
  vTaskSuspendAll();
  xPendedTicks += xTicksToCatchUp;
  xYieldRequired = xTaskResumeAll();
  return xYieldRequired;
References configASSERT, pdFALSE, uxSchedulerSuspended, vTaskSuspendAll(), xPendedTicks, and xTaskResumeAll().
xTaskCheckForTimeOut()
BaseType_t xTaskCheckForTimeOut (TimeOut_t *const pxTimeOut, TickType_t *const pxTicksToWait)
Definition at line 3273 of file tasks.c.
{
BaseType_t xReturn;
  configASSERT( pxTimeOut );
  configASSERT( pxTicksToWait );
  taskENTER_CRITICAL();
  {
    /* Minor optimisation.  The tick count cannot change in this block. */
    const TickType_t xConstTickCount = xTickCount;
    const TickType_t xElapsedTime = xConstTickCount - pxTimeOut->xTimeOnEntering;
    #if( INCLUDE_xTaskAbortDelay == 1 )
      if( pxCurrentTCB->ucDelayAborted != ( uint8_t ) pdFALSE )
      {
        /* The delay was aborted, which is not the same as a time out,
        but has the same result. */
        pxCurrentTCB->ucDelayAborted = pdFALSE;
        xReturn = pdTRUE;
      }
      else
    #endif
    #if ( INCLUDE_vTaskSuspend == 1 )
      if( *pxTicksToWait == portMAX_DELAY )
      {
        /* If INCLUDE_vTaskSuspend is set to 1 and the block time
        specified is the maximum block time then the task should block
        indefinitely, and therefore never time out. */
        xReturn = pdFALSE;
      }
      else
    #endif
    if( ( xNumOfOverflows != pxTimeOut->xOverflowCount ) && ( xConstTickCount >= pxTimeOut->xTimeOnEntering ) ) /*lint !e525 Indentation preferred as is to make code within pre-processor directives clearer. */
    {
      /* The tick count is greater than the time at which
      vTaskSetTimeout() was called, but has also overflowed since
      vTaskSetTimeOut() was called.  It must have wrapped all the way
      around and gone past again. This passed since vTaskSetTimeout()
      was called. */
      xReturn = pdTRUE;
    }
    else if( xElapsedTime < *pxTicksToWait ) /*lint !e961 Explicit casting is only redundant with some compilers, whereas others require it to prevent integer conversion errors. */
    {
      /* Not a genuine timeout. Adjust parameters for time remaining. */
      *pxTicksToWait -= xElapsedTime;
      vTaskInternalSetTimeOutState( pxTimeOut );
      xReturn = pdFALSE;
    }
    else
    {
      *pxTicksToWait = 0;
      xReturn = pdTRUE;
    }
  }
  taskEXIT_CRITICAL();
  return xReturn;
References configASSERT, pdFALSE, pdTRUE, portMAX_DELAY, pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, vTaskInternalSetTimeOutState(), xNumOfOverflows, xTIME_OUT::xOverflowCount, xTickCount, and xTIME_OUT::xTimeOnEntering.
Referenced by xQueueGenericSend(), xQueuePeek(), xQueueReceive(), xQueueSemaphoreTake(), and xStreamBufferSend().
xTaskGetTickCount()
TickType_t xTaskGetTickCount (void)
Definition at line 2303 of file tasks.c.
{
TickType_t xTicks;
  /* Critical section required if running on a 16 bit processor. */
  portTICK_TYPE_ENTER_CRITICAL();
  {
    xTicks = xTickCount;
  }
  portTICK_TYPE_EXIT_CRITICAL();
  return xTicks;
References portTICK_TYPE_ENTER_CRITICAL, portTICK_TYPE_EXIT_CRITICAL, and xTickCount.
Referenced by osDelayUntil(), osKernelGetSysTimerCount(), and osKernelGetTickCount().
xTaskGetTickCountFromISR()
TickType_t xTaskGetTickCountFromISR (void)
Definition at line 2318 of file tasks.c.
{
TickType_t xReturn;
UBaseType_t uxSavedInterruptStatus;
  /* RTOS ports that support interrupt nesting have the concept of a maximum
  system call (or maximum API call) interrupt priority.  Interrupts that are
  above the maximum system call priority are kept permanently enabled, even
  when the RTOS kernel is in a critical section, but cannot make any calls to
  FreeRTOS API functions.  If configASSERT() is defined in FreeRTOSConfig.h
  then portASSERT_IF_INTERRUPT_PRIORITY_INVALID() will result in an assertion
  failure if a FreeRTOS API function is called from an interrupt that has been
  assigned a priority above the configured maximum system call priority.
  Only FreeRTOS functions that end in FromISR can be called from interrupts
  that have been assigned a priority at or (logically) below the maximum
  system call interrupt priority.  FreeRTOS maintains a separate interrupt
  safe API to ensure interrupt entry is as fast and as simple as possible.
  More information (albeit Cortex-M specific) is provided on the following
  link: https://www.freertos.org/RTOS-Cortex-M3-M4.html */
  portASSERT_IF_INTERRUPT_PRIORITY_INVALID();
  uxSavedInterruptStatus = portTICK_TYPE_SET_INTERRUPT_MASK_FROM_ISR();
  {
    xReturn = xTickCount;
  }
  portTICK_TYPE_CLEAR_INTERRUPT_MASK_FROM_ISR( uxSavedInterruptStatus );
  return xReturn;
References portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portTICK_TYPE_CLEAR_INTERRUPT_MASK_FROM_ISR, portTICK_TYPE_SET_INTERRUPT_MASK_FROM_ISR, and xTickCount.
Referenced by osKernelGetTickCount().
xTaskIncrementTick()
BaseType_t xTaskIncrementTick (void)
Definition at line 2706 of file tasks.c.
{
TCB_t * pxTCB;
TickType_t xItemValue;
BaseType_t xSwitchRequired = pdFALSE;
  /* Called by the portable layer each time a tick interrupt occurs.
  Increments the tick then checks to see if the new tick value will cause any
  tasks to be unblocked. */
  traceTASK_INCREMENT_TICK( xTickCount );
  if( uxSchedulerSuspended == ( UBaseType_t ) pdFALSE )
  {
    /* Minor optimisation.  The tick count cannot change in this
    block. */
    const TickType_t xConstTickCount = xTickCount + ( TickType_t ) 1;
    /* Increment the RTOS tick, switching the delayed and overflowed
    delayed lists if it wraps to 0. */
    xTickCount = xConstTickCount;
    if( xConstTickCount == ( TickType_t ) 0U ) /*lint !e774 'if' does not always evaluate to false as it is looking for an overflow. */
    {
      taskSWITCH_DELAYED_LISTS();
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
    /* See if this tick has made a timeout expire.  Tasks are stored in
    the queue in the order of their wake time - meaning once one task
    has been found whose block time has not expired there is no need to
    look any further down the list. */
    if( xConstTickCount >= xNextTaskUnblockTime )
    {
      for( ;; )
      {
        if( listLIST_IS_EMPTY( pxDelayedTaskList ) != pdFALSE )
        {
          /* The delayed list is empty.  Set xNextTaskUnblockTime
          to the maximum possible value so it is extremely
          unlikely that the
          if( xTickCount >= xNextTaskUnblockTime ) test will pass
          next time through. */
          xNextTaskUnblockTime = portMAX_DELAY; /*lint !e961 MISRA exception as the casts are only redundant for some ports. */
          break;
        }
        else
        {
          /* The delayed list is not empty, get the value of the
          item at the head of the delayed list.  This is the time
          at which the task at the head of the delayed list must
          be removed from the Blocked state. */
          pxTCB = listGET_OWNER_OF_HEAD_ENTRY( pxDelayedTaskList ); /*lint !e9079 void * is used as this macro is used with timers and co-routines too.  Alignment is known to be fine as the type of the pointer stored and retrieved is the same. */
          xItemValue = listGET_LIST_ITEM_VALUE( &( pxTCB->xStateListItem ) );
          if( xConstTickCount < xItemValue )
          {
            /* It is not time to unblock this item yet, but the
            item value is the time at which the task at the head
            of the blocked list must be removed from the Blocked
            state - so record the item value in
            xNextTaskUnblockTime. */
            xNextTaskUnblockTime = xItemValue;
            break; /*lint !e9011 Code structure here is deedmed easier to understand with multiple breaks. */
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
          /* It is time to remove the item from the Blocked state. */
          ( void ) uxListRemove( &( pxTCB->xStateListItem ) );
          /* Is the task waiting on an event also?  If so remove
          it from the event list. */
          if( listLIST_ITEM_CONTAINER( &( pxTCB->xEventListItem ) ) != NULL )
          {
            ( void ) uxListRemove( &( pxTCB->xEventListItem ) );
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
          /* Place the unblocked task into the appropriate ready
          list. */
          prvAddTaskToReadyList( pxTCB );
          /* A task being unblocked cannot cause an immediate
          context switch if preemption is turned off. */
          #if (  configUSE_PREEMPTION == 1 )
          {
            /* Preemption is on, but a context switch should
            only be performed if the unblocked task has a
            priority that is equal to or higher than the
            currently executing task. */
            if( pxTCB->uxPriority >= pxCurrentTCB->uxPriority )
            {
              xSwitchRequired = pdTRUE;
            }
            else
            {
              mtCOVERAGE_TEST_MARKER();
            }
          }
          #endif /* configUSE_PREEMPTION */
        }
      }
    }
    /* Tasks of equal priority to the currently running task will share
    processing time (time slice) if preemption is on, and the application
    writer has not explicitly turned time slicing off. */
    #if ( ( configUSE_PREEMPTION == 1 ) && ( configUSE_TIME_SLICING == 1 ) )
    {
      if( listCURRENT_LIST_LENGTH( &( pxReadyTasksLists[ pxCurrentTCB->uxPriority ] ) ) > ( UBaseType_t ) 1 )
      {
        xSwitchRequired = pdTRUE;
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
    #endif /* ( ( configUSE_PREEMPTION == 1 ) && ( configUSE_TIME_SLICING == 1 ) ) */
    #if ( configUSE_TICK_HOOK == 1 )
    {
      /* Guard against the tick hook being called when the pended tick
      count is being unwound (when the scheduler is being unlocked). */
      if( xPendedTicks == ( TickType_t ) 0 )
      {
        vApplicationTickHook();
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
    #endif /* configUSE_TICK_HOOK */
    #if ( configUSE_PREEMPTION == 1 )
    {
      if( xYieldPending != pdFALSE )
      {
        xSwitchRequired = pdTRUE;
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
    #endif /* configUSE_PREEMPTION */
  }
  else
  {
    ++xPendedTicks;
    /* The tick hook gets called at regular intervals, even if the
    scheduler is locked. */
    #if ( configUSE_TICK_HOOK == 1 )
    {
      vApplicationTickHook();
    }
    #endif
  }
  return xSwitchRequired;
References listCURRENT_LIST_LENGTH, listGET_LIST_ITEM_VALUE, listGET_OWNER_OF_HEAD_ENTRY, listLIST_IS_EMPTY, listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portMAX_DELAY, prvAddTaskToReadyList, pxCurrentTCB, pxDelayedTaskList, pxReadyTasksLists, taskSWITCH_DELAYED_LISTS, traceTASK_INCREMENT_TICK, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vApplicationTickHook(), tskTaskControlBlock::xEventListItem, xNextTaskUnblockTime, xPendedTicks, tskTaskControlBlock::xStateListItem, xTickCount, and xYieldPending.
Referenced by xPortSysTickHandler(), and xTaskResumeAll().
xTaskRemoveFromEventList()
BaseType_t xTaskRemoveFromEventList (const List_t *const pxEventList)
Definition at line 3137 of file tasks.c.
{
TCB_t *pxUnblockedTCB;
BaseType_t xReturn;
  /* THIS FUNCTION MUST BE CALLED FROM A CRITICAL SECTION.  It can also be
  called from a critical section within an ISR. */
  /* The event list is sorted in priority order, so the first in the list can
  be removed as it is known to be the highest priority.  Remove the TCB from
  the delayed list, and add it to the ready list.
  If an event is for a queue that is locked then this function will never
  get called - the lock count on the queue will get modified instead.  This
  means exclusive access to the event list is guaranteed here.
  This function assumes that a check has already been made to ensure that
  pxEventList is not empty. */
  pxUnblockedTCB = listGET_OWNER_OF_HEAD_ENTRY( pxEventList ); /*lint !e9079 void * is used as this macro is used with timers and co-routines too.  Alignment is known to be fine as the type of the pointer stored and retrieved is the same. */
  configASSERT( pxUnblockedTCB );
  ( void ) uxListRemove( &( pxUnblockedTCB->xEventListItem ) );
  if( uxSchedulerSuspended == ( UBaseType_t ) pdFALSE )
  {
    ( void ) uxListRemove( &( pxUnblockedTCB->xStateListItem ) );
    prvAddTaskToReadyList( pxUnblockedTCB );
    #if( configUSE_TICKLESS_IDLE != 0 )
    {
      /* If a task is blocked on a kernel object then xNextTaskUnblockTime
      might be set to the blocked task's time out time.  If the task is
      unblocked for a reason other than a timeout xNextTaskUnblockTime is
      normally left unchanged, because it is automatically reset to a new
      value when the tick count equals xNextTaskUnblockTime.  However if
      tickless idling is used it might be more important to enter sleep mode
      at the earliest possible time - so reset xNextTaskUnblockTime here to
      ensure it is updated at the earliest possible time. */
      prvResetNextTaskUnblockTime();
    }
    #endif
  }
  else
  {
    /* The delayed and ready lists cannot be accessed, so hold this task
    pending until the scheduler is resumed. */
    vListInsertEnd( &( xPendingReadyList ), &( pxUnblockedTCB->xEventListItem ) );
  }
  if( pxUnblockedTCB->uxPriority > pxCurrentTCB->uxPriority )
  {
    /* Return true if the task removed from the event list has a higher
    priority than the calling task.  This allows the calling task to know if
    it should force a context switch now. */
    xReturn = pdTRUE;
    /* Mark that a yield is pending in case the user is not using the
    "xHigherPriorityTaskWoken" parameter to an ISR safe FreeRTOS function. */
    xYieldPending = pdTRUE;
  }
  else
  {
    xReturn = pdFALSE;
  }
  return xReturn;
References configASSERT, listGET_OWNER_OF_HEAD_ENTRY, pdFALSE, pdTRUE, prvAddTaskToReadyList, prvResetNextTaskUnblockTime(), pxCurrentTCB, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vListInsertEnd(), tskTaskControlBlock::xEventListItem, xPendingReadyList, tskTaskControlBlock::xStateListItem, and xYieldPending.
Referenced by prvUnlockQueue(), xQueueGenericReset(), xQueueGenericSend(), xQueueGenericSendFromISR(), xQueueGiveFromISR(), xQueuePeek(), xQueueReceive(), xQueueReceiveFromISR(), and xQueueSemaphoreTake().
xTaskResumeAll()
BaseType_t xTaskResumeAll (void)
Definition at line 2193 of file tasks.c.
{
TCB_t *pxTCB = NULL;
BaseType_t xAlreadyYielded = pdFALSE;
  /* If uxSchedulerSuspended is zero then this function does not match a
  previous call to vTaskSuspendAll(). */
  configASSERT( uxSchedulerSuspended );
  /* It is possible that an ISR caused a task to be removed from an event
  list while the scheduler was suspended.  If this was the case then the
  removed task will have been added to the xPendingReadyList.  Once the
  scheduler has been resumed it is safe to move all the pending ready
  tasks from this list into their appropriate ready list. */
  taskENTER_CRITICAL();
  {
    --uxSchedulerSuspended;
    if( uxSchedulerSuspended == ( UBaseType_t ) pdFALSE )
    {
      if( uxCurrentNumberOfTasks > ( UBaseType_t ) 0U )
      {
        /* Move any readied tasks from the pending list into the
        appropriate ready list. */
        while( listLIST_IS_EMPTY( &xPendingReadyList ) == pdFALSE )
        {
          pxTCB = listGET_OWNER_OF_HEAD_ENTRY( ( &xPendingReadyList ) ); /*lint !e9079 void * is used as this macro is used with timers and co-routines too.  Alignment is known to be fine as the type of the pointer stored and retrieved is the same. */
          ( void ) uxListRemove( &( pxTCB->xEventListItem ) );
          ( void ) uxListRemove( &( pxTCB->xStateListItem ) );
          prvAddTaskToReadyList( pxTCB );
          /* If the moved task has a priority higher than the current
          task then a yield must be performed. */
          if( pxTCB->uxPriority >= pxCurrentTCB->uxPriority )
          {
            xYieldPending = pdTRUE;
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
        }
        if( pxTCB != NULL )
        {
          /* A task was unblocked while the scheduler was suspended,
          which may have prevented the next unblock time from being
          re-calculated, in which case re-calculate it now.  Mainly
          important for low power tickless implementations, where
          this can prevent an unnecessary exit from low power
          state. */
          prvResetNextTaskUnblockTime();
        }
        /* If any ticks occurred while the scheduler was suspended then
        they should be processed now.  This ensures the tick count does
        not slip, and that any delayed tasks are resumed at the correct
        time. */
        {
          TickType_t xPendedCounts = xPendedTicks; /* Non-volatile copy. */
          if( xPendedCounts > ( TickType_t ) 0U )
          {
            do
            {
              if( xTaskIncrementTick() != pdFALSE )
              {
                xYieldPending = pdTRUE;
              }
              else
              {
                mtCOVERAGE_TEST_MARKER();
              }
              --xPendedCounts;
            } while( xPendedCounts > ( TickType_t ) 0U );
            xPendedTicks = 0;
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
        }
        if( xYieldPending != pdFALSE )
        {
          #if( configUSE_PREEMPTION != 0 )
          {
            xAlreadyYielded = pdTRUE;
          }
          #endif
          taskYIELD_IF_USING_PREEMPTION();
        }
        else
        {
          mtCOVERAGE_TEST_MARKER();
        }
      }
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
  }
  taskEXIT_CRITICAL();
  return xAlreadyYielded;
References configASSERT, listGET_OWNER_OF_HEAD_ENTRY, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, prvAddTaskToReadyList, prvResetNextTaskUnblockTime(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskYIELD_IF_USING_PREEMPTION, uxCurrentNumberOfTasks, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, tskTaskControlBlock::xEventListItem, xPendedTicks, xPendingReadyList, tskTaskControlBlock::xStateListItem, xTaskIncrementTick(), and xYieldPending.
Referenced by osKernelRestoreLock(), osKernelUnlock(), osThreadEnumerate(), portTASK_FUNCTION(), pvPortMalloc(), vEventGroupDelete(), vPortFree(), vPortGetHeapStats(), xEventGroupSetBits(), xEventGroupSync(), xEventGroupWaitBits(), xQueueGenericSend(), xQueuePeek(), xQueueReceive(), xQueueSemaphoreTake(), and xTaskCatchUpTicks().
Variable Documentation
pxCurrentTCB
PRIVILEGED_DATA TCB_t* volatile pxCurrentTCB = NULL
Definition at line 336 of file tasks.c.
Referenced by prvAddCurrentTaskToDelayedList(), prvAddNewTaskToReadyList(), uxTaskResetEventItemValue(), vTaskPlaceOnEventList(), vTaskPlaceOnUnorderedEventList(), vTaskRemoveFromUnorderedEventList(), vTaskStartScheduler(), vTaskSwitchContext(), xTaskCheckForTimeOut(), xTaskIncrementTick(), xTaskRemoveFromEventList(), and xTaskResumeAll().
pxDelayedTaskList
PRIVILEGED_DATA List_t* volatile pxDelayedTaskList static
Definition at line 345 of file tasks.c.
Referenced by prvAddCurrentTaskToDelayedList(), prvInitialiseTaskLists(), prvResetNextTaskUnblockTime(), and xTaskIncrementTick().
pxOverflowDelayedTaskList
PRIVILEGED_DATA List_t* volatile pxOverflowDelayedTaskList static
Definition at line 346 of file tasks.c.
Referenced by prvAddCurrentTaskToDelayedList(), and prvInitialiseTaskLists().
pxReadyTasksLists
PRIVILEGED_DATA List_t pxReadyTasksLists[configMAX_PRIORITIES] static
Definition at line 342 of file tasks.c.
Referenced by portTASK_FUNCTION(), prvInitialiseTaskLists(), and xTaskIncrementTick().
uxCurrentNumberOfTasks
PRIVILEGED_DATA volatile UBaseType_t uxCurrentNumberOfTasks = (UBaseType_t) 0U static
Definition at line 369 of file tasks.c.
Referenced by prvAddNewTaskToReadyList(), prvCheckTasksWaitingTermination(), uxTaskGetNumberOfTasks(), and xTaskResumeAll().
uxSchedulerSuspended
PRIVILEGED_DATA volatile UBaseType_t uxSchedulerSuspended = (UBaseType_t) pdFALSE static
Definition at line 388 of file tasks.c.
Referenced by vTaskPlaceOnUnorderedEventList(), vTaskRemoveFromUnorderedEventList(), vTaskSuspendAll(), vTaskSwitchContext(), xTaskCatchUpTicks(), xTaskIncrementTick(), xTaskRemoveFromEventList(), and xTaskResumeAll().
uxTaskNumber
PRIVILEGED_DATA UBaseType_t uxTaskNumber = (UBaseType_t) 0U static
Definition at line 376 of file tasks.c.
Referenced by prvAddNewTaskToReadyList().
uxTopReadyPriority
PRIVILEGED_DATA volatile UBaseType_t uxTopReadyPriority = tskIDLE_PRIORITY static
Definition at line 371 of file tasks.c.
Referenced by prvAddCurrentTaskToDelayedList().
xDelayedTaskList1
PRIVILEGED_DATA List_t xDelayedTaskList1 static
Definition at line 343 of file tasks.c.
Referenced by prvInitialiseTaskLists().
xDelayedTaskList2
PRIVILEGED_DATA List_t xDelayedTaskList2 static
Definition at line 344 of file tasks.c.
Referenced by prvInitialiseTaskLists().
xIdleTaskHandle
PRIVILEGED_DATA TaskHandle_t xIdleTaskHandle = NULL static
Definition at line 378 of file tasks.c.
Referenced by vTaskStartScheduler().
xNextTaskUnblockTime
PRIVILEGED_DATA volatile TickType_t xNextTaskUnblockTime = (TickType_t) 0U static
Definition at line 377 of file tasks.c.
Referenced by portTASK_FUNCTION(), prvAddCurrentTaskToDelayedList(), prvResetNextTaskUnblockTime(), vTaskStartScheduler(), and xTaskIncrementTick().
xNumOfOverflows
PRIVILEGED_DATA volatile BaseType_t xNumOfOverflows = (BaseType_t) 0 static
Definition at line 375 of file tasks.c.
Referenced by vTaskInternalSetTimeOutState(), vTaskSetTimeOutState(), and xTaskCheckForTimeOut().
xPendedTicks
PRIVILEGED_DATA volatile TickType_t xPendedTicks = (TickType_t) 0U static
Definition at line 373 of file tasks.c.
Referenced by xTaskCatchUpTicks(), xTaskIncrementTick(), and xTaskResumeAll().
xPendingReadyList
PRIVILEGED_DATA List_t xPendingReadyList static
Definition at line 347 of file tasks.c.
Referenced by prvInitialiseTaskLists(), xTaskRemoveFromEventList(), and xTaskResumeAll().
xSchedulerRunning
PRIVILEGED_DATA volatile BaseType_t xSchedulerRunning = pdFALSE static
Definition at line 372 of file tasks.c.
Referenced by prvAddNewTaskToReadyList(), vTaskEndScheduler(), and vTaskStartScheduler().
xTickCount
PRIVILEGED_DATA volatile TickType_t xTickCount = (TickType_t) configINITIAL_TICK_COUNT static
Definition at line 370 of file tasks.c.
Referenced by portTASK_FUNCTION(), prvAddCurrentTaskToDelayedList(), vTaskInternalSetTimeOutState(), vTaskSetTimeOutState(), vTaskStartScheduler(), xTaskCheckForTimeOut(), xTaskGetTickCount(), xTaskGetTickCountFromISR(), and xTaskIncrementTick().
xYieldPending
PRIVILEGED_DATA volatile BaseType_t xYieldPending = pdFALSE static
Definition at line 374 of file tasks.c.
Referenced by vTaskMissedYield(), vTaskRemoveFromUnorderedEventList(), vTaskSwitchContext(), xTaskIncrementTick(), xTaskRemoveFromEventList(), and xTaskResumeAll().