NUCLEO-G0B1RE Examples: NUCLEO-G0B1RE/TIM_PWMOutput/Inc/main.h File Reference
main.h File Reference
#include "stm32g0xx_hal.h"
#include "stm32g0xx_nucleo.h"
Macros
#define PRESCALER_VALUE (uint32_t)(((SystemCoreClock) / 64000000) - 1)
#define PERIOD_VALUE (uint32_t)(2667 - 1) /* Period Value */
#define PULSE1_VALUE (uint32_t)(2667 / 2) /* Capture Compare 1 Value */
#define PULSE2_VALUE (uint32_t)(2667 * 37.5 / 100) /* Capture Compare 2 Value */
#define PULSE3_VALUE (uint32_t)(2667 / 4) /* Capture Compare 3 Value */
#define PULSE4_VALUE (uint32_t)(2667 * 12.5 /100) /* Capture Compare 4 Value */
Functions
void HAL_TIM_MspPostInit (TIM_HandleTypeDef *htim)
File Name : TIM/TIM_PWMOutput/Src/stm32g0xx_hal_msp.c.
void Error_Handler (void)
This function is executed in case of error occurrence.
Macro Definition Documentation
PERIOD_VALUE
#define PERIOD_VALUE (uint32_t)(2667 - 1) /* Period Value */
Definition at line 104 of file main.h.
Referenced by MX_TIM1_Init().
PRESCALER_VALUE
#define PRESCALER_VALUE (uint32_t)(((SystemCoreClock) / 64000000) - 1)
Definition at line 66 of file main.h.
Referenced by MX_TIM1_Init().
PULSE1_VALUE
#define PULSE1_VALUE (uint32_t)(2667 / 2) /* Capture Compare 1 Value */
Definition at line 105 of file main.h.
Referenced by MX_TIM1_Init().
PULSE2_VALUE
#define PULSE2_VALUE (uint32_t)(2667 * 37.5 / 100) /* Capture Compare 2 Value */
Definition at line 106 of file main.h.
Referenced by MX_TIM1_Init().
PULSE3_VALUE
#define PULSE3_VALUE (uint32_t)(2667 / 4) /* Capture Compare 3 Value */
Definition at line 107 of file main.h.
Referenced by MX_TIM1_Init().
PULSE4_VALUE
#define PULSE4_VALUE (uint32_t)(2667 * 12.5 /100) /* Capture Compare 4 Value */
Definition at line 108 of file main.h.
Referenced by MX_TIM1_Init().
Function Documentation
Error_Handler()
void Error_Handler (void)
This function is executed in case of error occurrence.
Return values
None
Definition at line 319 of file main.c.
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  /* USER CODE END Error_Handler_Debug */
}
Referenced by main(), MX_TIM1_Init(), and SystemClock_Config().
HAL_TIM_MspPostInit()
void HAL_TIM_MspPostInit (TIM_HandleTypeDef * htim)
File Name : TIM/TIM_PWMOutput/Src/stm32g0xx_hal_msp.c.
Author
: MCD Application Team Description : This file provides code for the MSP Initialization and de-Initialization codes.
Attention
Copyright (c) 2020 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
TIM1 GPIO Configuration PA8 ------> TIM1_CH1 PA9 ------> TIM1_CH2 PA10 ------> TIM1_CH3 PA11 [PA9] ------> TIM1_CH4
TIM1 GPIO Configuration PA8 ------> TIM1_CH1 PA9 ------> TIM1_CH2 PA10 ------> TIM1_CH3 PA11 [PA9] ------> TIM1_CH4
Definition at line 120 of file stm32g0xx_hal_msp.c.
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  if(htim->Instance==TIM1)
  {
  /* USER CODE BEGIN TIM1_MspPostInit 0 */
  /* USER CODE END TIM1_MspPostInit 0 */
    __HAL_RCC_GPIOA_CLK_ENABLE();
    GPIO_InitStruct.Pin = GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10|GPIO_PIN_11;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_PULLUP;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    GPIO_InitStruct.Alternate = GPIO_AF2_TIM1;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
  /* USER CODE BEGIN TIM1_MspPostInit 1 */
  /* USER CODE END TIM1_MspPostInit 1 */
  }
}
References GPIO_InitStruct.
Referenced by MX_TIM1_Init().