NUCLEO-G0B1RE Examples: NUCLEO-G0B1RE/FreeRTOS_Queues/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.h File Reference
cmsis_os2.h File Reference
#include <stdint.h>
#include <stddef.h>
Data Structures
struct osVersion_t
Version information.
struct osThreadAttr_t
Attributes structure for thread.
struct osTimerAttr_t
Attributes structure for timer.
struct osEventFlagsAttr_t
Attributes structure for event flags.
struct osMutexAttr_t
Attributes structure for mutex.
struct osSemaphoreAttr_t
Attributes structure for semaphore.
struct osMemoryPoolAttr_t
Attributes structure for memory pool.
struct osMessageQueueAttr_t
Attributes structure for message queue.
Macros
#define __NO_RETURN
#define osWaitForever 0xFFFFFFFFU
Wait forever timeout value.
#define osFlagsWaitAny 0x00000000U
Wait for any flag (default).
#define osFlagsWaitAll 0x00000001U
Wait for all flags.
#define osFlagsNoClear 0x00000002U
Do not clear flags which have been specified to wait for.
#define osFlagsError 0x80000000U
Error indicator.
#define osFlagsErrorUnknown 0xFFFFFFFFU
osError (-1).
#define osFlagsErrorTimeout 0xFFFFFFFEU
osErrorTimeout (-2).
#define osFlagsErrorResource 0xFFFFFFFDU
osErrorResource (-3).
#define osFlagsErrorParameter 0xFFFFFFFCU
osErrorParameter (-4).
#define osFlagsErrorISR 0xFFFFFFFAU
osErrorISR (-6).
#define osThreadDetached 0x00000000U
Thread created in detached mode (default)
#define osThreadJoinable 0x00000001U
Thread created in joinable mode.
#define osMutexRecursive 0x00000001U
Recursive mutex.
#define osMutexPrioInherit 0x00000002U
Priority inherit protocol.
#define osMutexRobust 0x00000008U
Robust mutex.
#define TZ_MODULEID_T
Typedefs
typedef void(* osThreadFunc_t) (void *argument)
Entry point of a thread.
typedef void(* osTimerFunc_t) (void *argument)
Timer callback function.
typedef void * osThreadId_t
typedef void * osTimerId_t
typedef void * osEventFlagsId_t
typedef void * osMutexId_t
typedef void * osSemaphoreId_t
typedef void * osMemoryPoolId_t
typedef void * osMessageQueueId_t
typedef uint32_t TZ_ModuleId_t
Enumerations
enum osKernelState_t {
osKernelInactive = 0 , osKernelReady = 1 , osKernelRunning = 2 , osKernelLocked = 3 ,
osKernelSuspended = 4 , osKernelError = -1 , osKernelReserved = 0x7FFFFFFFU
}
Kernel state.
enum osThreadState_t {
osThreadInactive = 0 , osThreadReady = 1 , osThreadRunning = 2 , osThreadBlocked = 3 ,
osThreadTerminated = 4 , osThreadError = -1 , osThreadReserved = 0x7FFFFFFF
}
Thread state.
enum osPriority_t {
osPriorityNone = 0 , osPriorityIdle = 1 , osPriorityLow = 8 , osPriorityLow1 = 8+1 ,
osPriorityLow2 = 8+2 , osPriorityLow3 = 8+3 , osPriorityLow4 = 8+4 , osPriorityLow5 = 8+5 ,
osPriorityLow6 = 8+6 , osPriorityLow7 = 8+7 , osPriorityBelowNormal = 16 , osPriorityBelowNormal1 = 16+1 ,
osPriorityBelowNormal2 = 16+2 , osPriorityBelowNormal3 = 16+3 , osPriorityBelowNormal4 = 16+4 , osPriorityBelowNormal5 = 16+5 ,
osPriorityBelowNormal6 = 16+6 , osPriorityBelowNormal7 = 16+7 , osPriorityNormal = 24 , osPriorityNormal1 = 24+1 ,
osPriorityNormal2 = 24+2 , osPriorityNormal3 = 24+3 , osPriorityNormal4 = 24+4 , osPriorityNormal5 = 24+5 ,
osPriorityNormal6 = 24+6 , osPriorityNormal7 = 24+7 , osPriorityAboveNormal = 32 , osPriorityAboveNormal1 = 32+1 ,
osPriorityAboveNormal2 = 32+2 , osPriorityAboveNormal3 = 32+3 , osPriorityAboveNormal4 = 32+4 , osPriorityAboveNormal5 = 32+5 ,
osPriorityAboveNormal6 = 32+6 , osPriorityAboveNormal7 = 32+7 , osPriorityHigh = 40 , osPriorityHigh1 = 40+1 ,
osPriorityHigh2 = 40+2 , osPriorityHigh3 = 40+3 , osPriorityHigh4 = 40+4 , osPriorityHigh5 = 40+5 ,
osPriorityHigh6 = 40+6 , osPriorityHigh7 = 40+7 , osPriorityRealtime = 48 , osPriorityRealtime1 = 48+1 ,
osPriorityRealtime2 = 48+2 , osPriorityRealtime3 = 48+3 , osPriorityRealtime4 = 48+4 , osPriorityRealtime5 = 48+5 ,
osPriorityRealtime6 = 48+6 , osPriorityRealtime7 = 48+7 , osPriorityISR = 56 , osPriorityError = -1 ,
osPriorityReserved = 0x7FFFFFFF
}
Priority values.
enum osTimerType_t { osTimerOnce = 0 , osTimerPeriodic = 1 }
Timer type.
enum osStatus_t {
osOK = 0 , osError = -1 , osErrorTimeout = -2 , osErrorResource = -3 ,
osErrorParameter = -4 , osErrorNoMemory = -5 , osErrorISR = -6 , osStatusReserved = 0x7FFFFFFF
}
Status code values returned by CMSIS-RTOS functions.
Functions
osStatus_t osKernelInitialize (void)
Initialize the RTOS Kernel.
osStatus_t osKernelGetInfo (osVersion_t *version, char *id_buf, uint32_t id_size)
Get RTOS Kernel Information.
osKernelState_t osKernelGetState (void)
Get the current RTOS Kernel state.
osStatus_t osKernelStart (void)
Start the RTOS Kernel scheduler.
int32_t osKernelLock (void)
Lock the RTOS Kernel scheduler.
int32_t osKernelUnlock (void)
Unlock the RTOS Kernel scheduler.
int32_t osKernelRestoreLock (int32_t lock)
Restore the RTOS Kernel scheduler lock state.
uint32_t osKernelSuspend (void)
Suspend the RTOS Kernel scheduler.
void osKernelResume (uint32_t sleep_ticks)
Resume the RTOS Kernel scheduler.
uint32_t osKernelGetTickCount (void)
Get the RTOS kernel tick count.
uint32_t osKernelGetTickFreq (void)
Get the RTOS kernel tick frequency.
uint32_t osKernelGetSysTimerCount (void)
Get the RTOS kernel system timer count.
uint32_t osKernelGetSysTimerFreq (void)
Get the RTOS kernel system timer frequency.
osThreadId_t osThreadNew (osThreadFunc_t func, void *argument, const osThreadAttr_t *attr)
Create a thread and add it to Active Threads.
const char * osThreadGetName (osThreadId_t thread_id)
Get name of a thread.
osThreadId_t osThreadGetId (void)
Return the thread ID of the current running thread.
osThreadState_t osThreadGetState (osThreadId_t thread_id)
Get current thread state of a thread.
uint32_t osThreadGetStackSize (osThreadId_t thread_id)
Get stack size of a thread.
uint32_t osThreadGetStackSpace (osThreadId_t thread_id)
Get available stack space of a thread based on stack watermark recording during execution.
osStatus_t osThreadSetPriority (osThreadId_t thread_id, osPriority_t priority)
Change priority of a thread.
osPriority_t osThreadGetPriority (osThreadId_t thread_id)
Get current priority of a thread.
osStatus_t osThreadYield (void)
Pass control to next thread that is in state READY.
osStatus_t osThreadSuspend (osThreadId_t thread_id)
Suspend execution of a thread.
osStatus_t osThreadResume (osThreadId_t thread_id)
Resume execution of a thread.
osStatus_t osThreadDetach (osThreadId_t thread_id)
Detach a thread (thread storage can be reclaimed when thread terminates).
osStatus_t osThreadJoin (osThreadId_t thread_id)
Wait for specified thread to terminate.
void osThreadExit (void)
Terminate execution of current running thread.
osStatus_t osThreadTerminate (osThreadId_t thread_id)
Terminate execution of a thread.
uint32_t osThreadGetCount (void)
Get number of active threads.
uint32_t osThreadEnumerate (osThreadId_t *thread_array, uint32_t array_items)
Enumerate active threads.
uint32_t osThreadFlagsSet (osThreadId_t thread_id, uint32_t flags)
Set the specified Thread Flags of a thread.
uint32_t osThreadFlagsClear (uint32_t flags)
Clear the specified Thread Flags of current running thread.
uint32_t osThreadFlagsGet (void)
Get the current Thread Flags of current running thread.
uint32_t osThreadFlagsWait (uint32_t flags, uint32_t options, uint32_t timeout)
Wait for one or more Thread Flags of the current running thread to become signaled.
osStatus_t osDelay (uint32_t ticks)
Wait for Timeout (Time Delay).
osStatus_t osDelayUntil (uint32_t ticks)
Wait until specified time.
osTimerId_t osTimerNew (osTimerFunc_t func, osTimerType_t type, void *argument, const osTimerAttr_t *attr)
Create and Initialize a timer.
const char * osTimerGetName (osTimerId_t timer_id)
Get name of a timer.
osStatus_t osTimerStart (osTimerId_t timer_id, uint32_t ticks)
Start or restart a timer.
osStatus_t osTimerStop (osTimerId_t timer_id)
Stop a timer.
uint32_t osTimerIsRunning (osTimerId_t timer_id)
Check if a timer is running.
osStatus_t osTimerDelete (osTimerId_t timer_id)
Delete a timer.
osEventFlagsId_t osEventFlagsNew (const osEventFlagsAttr_t *attr)
Create and Initialize an Event Flags object.
const char * osEventFlagsGetName (osEventFlagsId_t ef_id)
Get name of an Event Flags object.
uint32_t osEventFlagsSet (osEventFlagsId_t ef_id, uint32_t flags)
Set the specified Event Flags.
uint32_t osEventFlagsClear (osEventFlagsId_t ef_id, uint32_t flags)
Clear the specified Event Flags.
uint32_t osEventFlagsGet (osEventFlagsId_t ef_id)
Get the current Event Flags.
uint32_t osEventFlagsWait (osEventFlagsId_t ef_id, uint32_t flags, uint32_t options, uint32_t timeout)
Wait for one or more Event Flags to become signaled.
osStatus_t osEventFlagsDelete (osEventFlagsId_t ef_id)
Delete an Event Flags object.
osMutexId_t osMutexNew (const osMutexAttr_t *attr)
Create and Initialize a Mutex object.
const char * osMutexGetName (osMutexId_t mutex_id)
Get name of a Mutex object.
osStatus_t osMutexAcquire (osMutexId_t mutex_id, uint32_t timeout)
Acquire a Mutex or timeout if it is locked.
osStatus_t osMutexRelease (osMutexId_t mutex_id)
Release a Mutex that was acquired by osMutexAcquire.
osThreadId_t osMutexGetOwner (osMutexId_t mutex_id)
Get Thread which owns a Mutex object.
osStatus_t osMutexDelete (osMutexId_t mutex_id)
Delete a Mutex object.
osSemaphoreId_t osSemaphoreNew (uint32_t max_count, uint32_t initial_count, const osSemaphoreAttr_t *attr)
Create and Initialize a Semaphore object.
const char * osSemaphoreGetName (osSemaphoreId_t semaphore_id)
Get name of a Semaphore object.
osStatus_t osSemaphoreAcquire (osSemaphoreId_t semaphore_id, uint32_t timeout)
Acquire a Semaphore token or timeout if no tokens are available.
osStatus_t osSemaphoreRelease (osSemaphoreId_t semaphore_id)
Release a Semaphore token up to the initial maximum count.
uint32_t osSemaphoreGetCount (osSemaphoreId_t semaphore_id)
Get current Semaphore token count.
osStatus_t osSemaphoreDelete (osSemaphoreId_t semaphore_id)
Delete a Semaphore object.
osMemoryPoolId_t osMemoryPoolNew (uint32_t block_count, uint32_t block_size, const osMemoryPoolAttr_t *attr)
Create and Initialize a Memory Pool object.
const char * osMemoryPoolGetName (osMemoryPoolId_t mp_id)
Get name of a Memory Pool object.
void * osMemoryPoolAlloc (osMemoryPoolId_t mp_id, uint32_t timeout)
Allocate a memory block from a Memory Pool.
osStatus_t osMemoryPoolFree (osMemoryPoolId_t mp_id, void *block)
Return an allocated memory block back to a Memory Pool.
uint32_t osMemoryPoolGetCapacity (osMemoryPoolId_t mp_id)
Get maximum number of memory blocks in a Memory Pool.
uint32_t osMemoryPoolGetBlockSize (osMemoryPoolId_t mp_id)
Get memory block size in a Memory Pool.
uint32_t osMemoryPoolGetCount (osMemoryPoolId_t mp_id)
Get number of memory blocks used in a Memory Pool.
uint32_t osMemoryPoolGetSpace (osMemoryPoolId_t mp_id)
Get number of memory blocks available in a Memory Pool.
osStatus_t osMemoryPoolDelete (osMemoryPoolId_t mp_id)
Delete a Memory Pool object.
osMessageQueueId_t osMessageQueueNew (uint32_t msg_count, uint32_t msg_size, const osMessageQueueAttr_t *attr)
Create and Initialize a Message Queue object.
const char * osMessageQueueGetName (osMessageQueueId_t mq_id)
Get name of a Message Queue object.
osStatus_t osMessageQueuePut (osMessageQueueId_t mq_id, const void *msg_ptr, uint8_t msg_prio, uint32_t timeout)
Put a Message into a Queue or timeout if Queue is full.
osStatus_t osMessageQueueGet (osMessageQueueId_t mq_id, void *msg_ptr, uint8_t *msg_prio, uint32_t timeout)
Get a Message from a Queue or timeout if Queue is empty.
uint32_t osMessageQueueGetCapacity (osMessageQueueId_t mq_id)
Get maximum number of messages in a Message Queue.
uint32_t osMessageQueueGetMsgSize (osMessageQueueId_t mq_id)
Get maximum message size in a Memory Pool.
uint32_t osMessageQueueGetCount (osMessageQueueId_t mq_id)
Get number of queued messages in a Message Queue.
uint32_t osMessageQueueGetSpace (osMessageQueueId_t mq_id)
Get number of available slots for messages in a Message Queue.
osStatus_t osMessageQueueReset (osMessageQueueId_t mq_id)
Reset a Message Queue to initial empty state.
osStatus_t osMessageQueueDelete (osMessageQueueId_t mq_id)
Delete a Message Queue object.
Macro Definition Documentation
__NO_RETURN
#define __NO_RETURN
Definition at line 38 of file cmsis_os2.h.
osFlagsError
#define osFlagsError 0x80000000U
Error indicator.
Definition at line 159 of file cmsis_os2.h.
osFlagsErrorISR
#define osFlagsErrorISR 0xFFFFFFFAU
osErrorISR (-6).
Definition at line 164 of file cmsis_os2.h.
osFlagsErrorParameter
#define osFlagsErrorParameter 0xFFFFFFFCU
osErrorParameter (-4).
Definition at line 163 of file cmsis_os2.h.
osFlagsErrorResource
#define osFlagsErrorResource 0xFFFFFFFDU
osErrorResource (-3).
Definition at line 162 of file cmsis_os2.h.
osFlagsErrorTimeout
#define osFlagsErrorTimeout 0xFFFFFFFEU
osErrorTimeout (-2).
Definition at line 161 of file cmsis_os2.h.
osFlagsErrorUnknown
#define osFlagsErrorUnknown 0xFFFFFFFFU
osError (-1).
Definition at line 160 of file cmsis_os2.h.
osFlagsNoClear
#define osFlagsNoClear 0x00000002U
Do not clear flags which have been specified to wait for.
Definition at line 156 of file cmsis_os2.h.
Referenced by osEventFlagsWait().
osFlagsWaitAll
#define osFlagsWaitAll 0x00000001U
Wait for all flags.
Definition at line 155 of file cmsis_os2.h.
Referenced by osEventFlagsWait().
osFlagsWaitAny
#define osFlagsWaitAny 0x00000000U
Wait for any flag (default).
Definition at line 154 of file cmsis_os2.h.
osMutexPrioInherit
#define osMutexPrioInherit 0x00000002U
Priority inherit protocol.
Definition at line 172 of file cmsis_os2.h.
osMutexRecursive
#define osMutexRecursive 0x00000001U
Recursive mutex.
Definition at line 171 of file cmsis_os2.h.
osMutexRobust
#define osMutexRobust 0x00000008U
Robust mutex.
Definition at line 173 of file cmsis_os2.h.
osThreadDetached
#define osThreadDetached 0x00000000U
Thread created in detached mode (default)
Definition at line 167 of file cmsis_os2.h.
osThreadJoinable
#define osThreadJoinable 0x00000001U
Thread created in joinable mode.
Definition at line 168 of file cmsis_os2.h.
Referenced by osThreadNew().
osWaitForever
#define osWaitForever 0xFFFFFFFFU
Wait forever timeout value.
Definition at line 151 of file cmsis_os2.h.
TZ_MODULEID_T
#define TZ_MODULEID_T
Definition at line 211 of file cmsis_os2.h.
Typedef Documentation
osEventFlagsId_t
typedef void* osEventFlagsId_t
Event Flags ID identifies the event flags.
Definition at line 195 of file cmsis_os2.h.
osMemoryPoolId_t
typedef void* osMemoryPoolId_t
Memory Pool ID identifies the memory pool.
Definition at line 204 of file cmsis_os2.h.
osMessageQueueId_t
typedef void* osMessageQueueId_t
Message Queue ID identifies the message queue.
Definition at line 207 of file cmsis_os2.h.
osMutexId_t
typedef void* osMutexId_t
Mutex ID identifies the mutex.
Definition at line 198 of file cmsis_os2.h.
osSemaphoreId_t
typedef void* osSemaphoreId_t
Semaphore ID identifies the semaphore.
Definition at line 201 of file cmsis_os2.h.
osThreadFunc_t
typedef void(* osThreadFunc_t) (void *argument)
Entry point of a thread.
Definition at line 139 of file cmsis_os2.h.
osThreadId_t
typedef void* osThreadId_t
Thread ID identifies the thread.
Definition at line 189 of file cmsis_os2.h.
osTimerFunc_t
typedef void(* osTimerFunc_t) (void *argument)
Timer callback function.
Definition at line 142 of file cmsis_os2.h.
osTimerId_t
typedef void* osTimerId_t
Timer ID identifies the timer.
Definition at line 192 of file cmsis_os2.h.
TZ_ModuleId_t
typedef uint32_t TZ_ModuleId_t
Data type that identifies secure software modules called by a process.
Definition at line 213 of file cmsis_os2.h.
Enumeration Type Documentation
osKernelState_t
enum osKernelState_t
Kernel state.
Enumerator
osKernelInactive
Inactive.
osKernelReady
Ready.
osKernelRunning
Running.
osKernelLocked
Locked.
osKernelSuspended
Suspended.
osKernelError
Error.
osKernelReserved
Prevents enum down-size compiler optimization.
Definition at line 60 of file cmsis_os2.h.
             {
  osKernelInactive        =  0,
  osKernelReady           =  1,
  osKernelRunning         =  2,
  osKernelLocked          =  3,
  osKernelSuspended       =  4,
  osKernelError           = -1,
  osKernelReserved        = 0x7FFFFFFFU
} osKernelState_t;
osPriority_t
enum osPriority_t
Priority values.
Enumerator
osPriorityNone
No priority (not initialized).
osPriorityIdle
Reserved for Idle thread.
osPriorityLow
Priority: low.
osPriorityLow1
Priority: low + 1.
osPriorityLow2
Priority: low + 2.
osPriorityLow3
Priority: low + 3.
osPriorityLow4
Priority: low + 4.
osPriorityLow5
Priority: low + 5.
osPriorityLow6
Priority: low + 6.
osPriorityLow7
Priority: low + 7.
osPriorityBelowNormal
Priority: below normal.
osPriorityBelowNormal1
Priority: below normal + 1.
osPriorityBelowNormal2
Priority: below normal + 2.
osPriorityBelowNormal3
Priority: below normal + 3.
osPriorityBelowNormal4
Priority: below normal + 4.
osPriorityBelowNormal5
Priority: below normal + 5.
osPriorityBelowNormal6
Priority: below normal + 6.
osPriorityBelowNormal7
Priority: below normal + 7.
osPriorityNormal
Priority: normal.
osPriorityNormal1
Priority: normal + 1.
osPriorityNormal2
Priority: normal + 2.
osPriorityNormal3
Priority: normal + 3.
osPriorityNormal4
Priority: normal + 4.
osPriorityNormal5
Priority: normal + 5.
osPriorityNormal6
Priority: normal + 6.
osPriorityNormal7
Priority: normal + 7.
osPriorityAboveNormal
Priority: above normal.
osPriorityAboveNormal1
Priority: above normal + 1.
osPriorityAboveNormal2
Priority: above normal + 2.
osPriorityAboveNormal3
Priority: above normal + 3.
osPriorityAboveNormal4
Priority: above normal + 4.
osPriorityAboveNormal5
Priority: above normal + 5.
osPriorityAboveNormal6
Priority: above normal + 6.
osPriorityAboveNormal7
Priority: above normal + 7.
osPriorityHigh
Priority: high.
osPriorityHigh1
Priority: high + 1.
osPriorityHigh2
Priority: high + 2.
osPriorityHigh3
Priority: high + 3.
osPriorityHigh4
Priority: high + 4.
osPriorityHigh5
Priority: high + 5.
osPriorityHigh6
Priority: high + 6.
osPriorityHigh7
Priority: high + 7.
osPriorityRealtime
Priority: realtime.
osPriorityRealtime1
Priority: realtime + 1.
osPriorityRealtime2
Priority: realtime + 2.
osPriorityRealtime3
Priority: realtime + 3.
osPriorityRealtime4
Priority: realtime + 4.
osPriorityRealtime5
Priority: realtime + 5.
osPriorityRealtime6
Priority: realtime + 6.
osPriorityRealtime7
Priority: realtime + 7.
osPriorityISR
Reserved for ISR deferred thread.
osPriorityError
System cannot determine priority or illegal priority.
osPriorityReserved
Prevents enum down-size compiler optimization.
Definition at line 82 of file cmsis_os2.h.
             {
  osPriorityNone          =  0,
  osPriorityIdle          =  1,
  osPriorityLow           =  8,
  osPriorityLow1          =  8+1,
  osPriorityLow2          =  8+2,
  osPriorityLow3          =  8+3,
  osPriorityLow4          =  8+4,
  osPriorityLow5          =  8+5,
  osPriorityLow6          =  8+6,
  osPriorityLow7          =  8+7,
  osPriorityBelowNormal   = 16,
  osPriorityBelowNormal1  = 16+1,
  osPriorityBelowNormal2  = 16+2,
  osPriorityBelowNormal3  = 16+3,
  osPriorityBelowNormal4  = 16+4,
  osPriorityBelowNormal5  = 16+5,
  osPriorityBelowNormal6  = 16+6,
  osPriorityBelowNormal7  = 16+7,
  osPriorityNormal        = 24,
  osPriorityNormal1       = 24+1,
  osPriorityNormal2       = 24+2,
  osPriorityNormal3       = 24+3,
  osPriorityNormal4       = 24+4,
  osPriorityNormal5       = 24+5,
  osPriorityNormal6       = 24+6,
  osPriorityNormal7       = 24+7,
  osPriorityAboveNormal   = 32,
  osPriorityAboveNormal1  = 32+1,
  osPriorityAboveNormal2  = 32+2,
  osPriorityAboveNormal3  = 32+3,
  osPriorityAboveNormal4  = 32+4,
  osPriorityAboveNormal5  = 32+5,
  osPriorityAboveNormal6  = 32+6,
  osPriorityAboveNormal7  = 32+7,
  osPriorityHigh          = 40,
  osPriorityHigh1         = 40+1,
  osPriorityHigh2         = 40+2,
  osPriorityHigh3         = 40+3,
  osPriorityHigh4         = 40+4,
  osPriorityHigh5         = 40+5,
  osPriorityHigh6         = 40+6,
  osPriorityHigh7         = 40+7,
  osPriorityRealtime      = 48,
  osPriorityRealtime1     = 48+1,
  osPriorityRealtime2     = 48+2,
  osPriorityRealtime3     = 48+3,
  osPriorityRealtime4     = 48+4,
  osPriorityRealtime5     = 48+5,
  osPriorityRealtime6     = 48+6,
  osPriorityRealtime7     = 48+7,
  osPriorityISR           = 56,
  osPriorityError         = -1,
  osPriorityReserved      = 0x7FFFFFFF
} osPriority_t;
osStatus_t
enum osStatus_t
Status code values returned by CMSIS-RTOS functions.
Enumerator
osOK
Operation completed successfully.
osError
Unspecified RTOS error: run-time error but no other error message fits.
osErrorTimeout
Operation not completed within the timeout period.
osErrorResource
Resource not available.
osErrorParameter
Parameter error.
osErrorNoMemory
System is out of memory: it was impossible to allocate or reserve memory for the operation.
osErrorISR
Not allowed in ISR context: the function cannot be called from interrupt service routines.
osStatusReserved
Prevents enum down-size compiler optimization.
Definition at line 176 of file cmsis_os2.h.
             {
  osOK                      =  0,
  osError                   = -1,
  osErrorTimeout            = -2,
  osErrorResource           = -3,
  osErrorParameter          = -4,
  osErrorNoMemory           = -5,
  osErrorISR                = -6,
  osStatusReserved          = 0x7FFFFFFF
} osStatus_t;
osThreadState_t
enum osThreadState_t
Thread state.
Enumerator
osThreadInactive
Inactive.
osThreadReady
Ready.
osThreadRunning
Running.
osThreadBlocked
Blocked.
osThreadTerminated
Terminated.
osThreadError
Error.
osThreadReserved
Prevents enum down-size compiler optimization.
Definition at line 71 of file cmsis_os2.h.
             {
  osThreadInactive        =  0,
  osThreadReady           =  1,
  osThreadRunning         =  2,
  osThreadBlocked         =  3,
  osThreadTerminated      =  4,
  osThreadError           = -1,
  osThreadReserved        = 0x7FFFFFFF
} osThreadState_t;
osTimerType_t
enum osTimerType_t
Timer type.
Enumerator
osTimerOnce
One-shot timer.
osTimerPeriodic
Repeating timer.
Definition at line 145 of file cmsis_os2.h.
             {
  osTimerOnce               = 0,
  osTimerPeriodic           = 1
} osTimerType_t;
Function Documentation
osDelay()
osStatus_t osDelay (uint32_t ticks)
Wait for Timeout (Time Delay).
Parameters
[in] ticks time ticks value
Returns
status code that indicates the execution status of the function.
Definition at line 881 of file cmsis_os2.c.
{
  osStatus_t stat;
  if (IS_IRQ()) {
    stat = osErrorISR;
  }
  else {
    stat = osOK;
    if (ticks != 0U) {
      vTaskDelay(ticks);
    }
  }
  return (stat);
}
References IS_IRQ, osErrorISR, osOK, and vTaskDelay().
Referenced by MessageQueueProducer().
osDelayUntil()
osStatus_t osDelayUntil (uint32_t ticks)
Wait until specified time.
Parameters
[in] ticks absolute time in ticks
Returns
status code that indicates the execution status of the function.
Definition at line 898 of file cmsis_os2.c.
{
  TickType_t tcnt, delay;
  osStatus_t stat;
  if (IS_IRQ()) {
    stat = osErrorISR;
  }
  else {
    stat = osOK;
    tcnt = xTaskGetTickCount();
    /* Determine remaining number of ticks to delay */
    delay = (TickType_t)ticks - tcnt;
    /* Check if target tick has not expired */
    if((delay != 0U) && (0 == (delay >> (8 * sizeof(TickType_t) - 1)))) {
      vTaskDelayUntil (&tcnt, delay);
    }
    else
    {
      /* No delay or already expired */
      stat = osErrorParameter;
    }
  }
  return (stat);
}
References IS_IRQ, osErrorISR, osErrorParameter, osOK, vTaskDelayUntil(), and xTaskGetTickCount().
osEventFlagsClear()
uint32_t osEventFlagsClear (osEventFlagsId_t ef_id, uint32_t flags)
Clear the specified Event Flags.
Parameters
[in] ef_id event flags ID obtained by osEventFlagsNew.
[in] flags specifies the flags that shall be cleared.
Returns
event flags before clearing or error code if highest bit set.
Definition at line 1181 of file cmsis_os2.c.
{
  EventGroupHandle_t hEventGroup = (EventGroupHandle_t)ef_id;
  uint32_t rflags;
  if ((hEventGroup == NULL) || ((flags & EVENT_FLAGS_INVALID_BITS) != 0U)) {
    rflags = (uint32_t)osErrorParameter;
  }
  else if (IS_IRQ()) {
  #if (configUSE_OS2_EVENTFLAGS_FROM_ISR == 0)
    /* Enable timers and xTimerPendFunctionCall function to support osEventFlagsSet from ISR */
    rflags = (uint32_t)osErrorResource;
  #else
    rflags = xEventGroupGetBitsFromISR (hEventGroup);
    if (xEventGroupClearBitsFromISR (hEventGroup, (EventBits_t)flags) == pdFAIL) {
      rflags = (uint32_t)osErrorResource;
    }
  #endif
  }
  else {
    rflags = xEventGroupClearBits (hEventGroup, (EventBits_t)flags);
  }
  return (rflags);
}
References EVENT_FLAGS_INVALID_BITS, IS_IRQ, osErrorParameter, osErrorResource, pdFAIL, xEventGroupClearBits(), xEventGroupClearBitsFromISR, and xEventGroupGetBitsFromISR().
osEventFlagsDelete()
osStatus_t osEventFlagsDelete (osEventFlagsId_t ef_id)
Delete an Event Flags object.
Parameters
[in] ef_id event flags ID obtained by osEventFlagsNew.
Returns
status code that indicates the execution status of the function.
Definition at line 1274 of file cmsis_os2.c.
{
  EventGroupHandle_t hEventGroup = (EventGroupHandle_t)ef_id;
  osStatus_t stat;
#ifndef USE_FreeRTOS_HEAP_1
  if (IS_IRQ()) {
    stat = osErrorISR;
  }
  else if (hEventGroup == NULL) {
    stat = osErrorParameter;
  }
  else {
    stat = osOK;
    vEventGroupDelete (hEventGroup);
  }
#else
  stat = osError;
#endif
  return (stat);
}
References IS_IRQ, osError, osErrorISR, osErrorParameter, osOK, and vEventGroupDelete().
osEventFlagsGet()
uint32_t osEventFlagsGet (osEventFlagsId_t ef_id)
Get the current Event Flags.
Parameters
[in] ef_id event flags ID obtained by osEventFlagsNew.
Returns
current event flags.
Definition at line 1207 of file cmsis_os2.c.
{
  EventGroupHandle_t hEventGroup = (EventGroupHandle_t)ef_id;
  uint32_t rflags;
  if (ef_id == NULL) {
    rflags = 0U;
  }
  else if (IS_IRQ()) {
    rflags = xEventGroupGetBitsFromISR (hEventGroup);
  }
  else {
    rflags = xEventGroupGetBits (hEventGroup);
  }
  return (rflags);
}
References IS_IRQ, xEventGroupGetBits, and xEventGroupGetBitsFromISR().
osEventFlagsGetName()
const char * osEventFlagsGetName (osEventFlagsId_t ef_id)
Get name of an Event Flags object.
Parameters
[in] ef_id event flags ID obtained by osEventFlagsNew.
Returns
name as NULL terminated string.
osEventFlagsNew()
osEventFlagsId_t osEventFlagsNew (const osEventFlagsAttr_t * attr)
Create and Initialize an Event Flags object.
Parameters
[in] attr event flags attributes; NULL: default values.
Returns
event flags ID for reference by other functions or NULL in case of error.
Definition at line 1110 of file cmsis_os2.c.
{
  EventGroupHandle_t hEventGroup;
  int32_t mem;
  hEventGroup = NULL;
  if (!IS_IRQ()) {
    mem = -1;
    if (attr != NULL) {
      if ((attr->cb_mem != NULL) && (attr->cb_size >= sizeof(StaticEventGroup_t))) {
        mem = 1;
      }
      else {
        if ((attr->cb_mem == NULL) && (attr->cb_size == 0U)) {
          mem = 0;
        }
      }
    }
    else {
      mem = 0;
    }
    if (mem == 1) {
      #if (configSUPPORT_STATIC_ALLOCATION == 1)
      hEventGroup = xEventGroupCreateStatic (attr->cb_mem);
      #endif
    }
    else {
      if (mem == 0) {
        #if (configSUPPORT_DYNAMIC_ALLOCATION == 1)
          hEventGroup = xEventGroupCreate();
        #endif
      }
    }
  }
  return ((osEventFlagsId_t)hEventGroup);
}
References osEventFlagsAttr_t::cb_mem, osEventFlagsAttr_t::cb_size, and IS_IRQ.
osEventFlagsSet()
uint32_t osEventFlagsSet (osEventFlagsId_t ef_id, uint32_t flags)
Set the specified Event Flags.
Parameters
[in] ef_id event flags ID obtained by osEventFlagsNew.
[in] flags specifies the flags that shall be set.
Returns
event flags after setting or error code if highest bit set.
Definition at line 1150 of file cmsis_os2.c.
{
  EventGroupHandle_t hEventGroup = (EventGroupHandle_t)ef_id;
  uint32_t rflags;
  BaseType_t yield;
  if ((hEventGroup == NULL) || ((flags & EVENT_FLAGS_INVALID_BITS) != 0U)) {
    rflags = (uint32_t)osErrorParameter;
  }
  else if (IS_IRQ()) {
  #if (configUSE_OS2_EVENTFLAGS_FROM_ISR == 0)
    (void)yield;
    /* Enable timers and xTimerPendFunctionCall function to support osEventFlagsSet from ISR */
    rflags = (uint32_t)osErrorResource;
  #else
    yield = pdFALSE;
    if (xEventGroupSetBitsFromISR (hEventGroup, (EventBits_t)flags, &yield) == pdFAIL) {
      rflags = (uint32_t)osErrorResource;
    } else {
      rflags = flags;
      portYIELD_FROM_ISR (yield);
    }
  #endif
  }
  else {
    rflags = xEventGroupSetBits (hEventGroup, (EventBits_t)flags);
  }
  return (rflags);
}
References EVENT_FLAGS_INVALID_BITS, IS_IRQ, osErrorParameter, osErrorResource, pdFAIL, pdFALSE, portYIELD_FROM_ISR, xEventGroupSetBits(), and xEventGroupSetBitsFromISR.
osEventFlagsWait()
uint32_t osEventFlagsWait (osEventFlagsId_t ef_id, uint32_t flags, uint32_t options, uint32_t timeout)
Wait for one or more Event Flags to become signaled.
Parameters
[in] ef_id event flags ID obtained by osEventFlagsNew.
[in] flags specifies the flags to wait for.
[in] options specifies flags options (osFlagsXxxx).
[in] timeout CMSIS_RTOS_TimeOutValue or 0 in case of no time-out.
Returns
event flags before clearing or error code if highest bit set.
Definition at line 1224 of file cmsis_os2.c.
{
  EventGroupHandle_t hEventGroup = (EventGroupHandle_t)ef_id;
  BaseType_t wait_all;
  BaseType_t exit_clr;
  uint32_t rflags;
  if ((hEventGroup == NULL) || ((flags & EVENT_FLAGS_INVALID_BITS) != 0U)) {
    rflags = (uint32_t)osErrorParameter;
  }
  else if (IS_IRQ()) {
    rflags = (uint32_t)osErrorISR;
  }
  else {
    if (options & osFlagsWaitAll) {
      wait_all = pdTRUE;
    } else {
      wait_all = pdFAIL;
    }
    if (options & osFlagsNoClear) {
      exit_clr = pdFAIL;
    } else {
      exit_clr = pdTRUE;
    }
    rflags = xEventGroupWaitBits (hEventGroup, (EventBits_t)flags, exit_clr, wait_all, (TickType_t)timeout);
    if (options & osFlagsWaitAll) {
      if ((flags & rflags) != flags) {
        if (timeout > 0U) {
          rflags = (uint32_t)osErrorTimeout;
        } else {
          rflags = (uint32_t)osErrorResource;
        }
      }
    }
    else {
      if ((flags & rflags) == 0U) {
        if (timeout > 0U) {
          rflags = (uint32_t)osErrorTimeout;
        } else {
          rflags = (uint32_t)osErrorResource;
        }
      }
    }
  }
  return (rflags);
}
References EVENT_FLAGS_INVALID_BITS, IS_IRQ, osErrorISR, osErrorParameter, osErrorResource, osErrorTimeout, osFlagsNoClear, osFlagsWaitAll, pdFAIL, pdTRUE, and xEventGroupWaitBits().
osKernelGetInfo()
osStatus_t osKernelGetInfo (osVersion_t * version, char * id_buf, uint32_t id_size)
Get RTOS Kernel Information.
Parameters
[out] version pointer to buffer for retrieving version information.
[out] id_buf pointer to buffer for retrieving kernel identification string.
[in] id_size size of buffer for kernel identification string.
Returns
status code that indicates the execution status of the function.
Definition at line 222 of file cmsis_os2.c.
{
  if (version != NULL) {
    /* Version encoding is major.minor.rev: mmnnnrrrr dec */
    version->api    = KERNEL_VERSION;
    version->kernel = KERNEL_VERSION;
  }
  if ((id_buf != NULL) && (id_size != 0U)) {
    if (id_size > sizeof(KERNEL_ID)) {
      id_size = sizeof(KERNEL_ID);
    }
    memcpy(id_buf, KERNEL_ID, id_size);
  }
  return (osOK);
}
References osVersion_t::api, osVersion_t::kernel, KERNEL_ID, KERNEL_VERSION, and osOK.
osKernelGetState()
osKernelState_t osKernelGetState (void)
Get the current RTOS Kernel state.
Returns
current RTOS Kernel state.
Definition at line 240 of file cmsis_os2.c.
{
  osKernelState_t state;
  switch (xTaskGetSchedulerState()) {
    case taskSCHEDULER_RUNNING:
      state = osKernelRunning;
      break;
    case taskSCHEDULER_SUSPENDED:
      state = osKernelLocked;
      break;
    case taskSCHEDULER_NOT_STARTED:
    default:
      if (KernelState == osKernelReady) {
        state = osKernelReady;
      } else {
        state = osKernelInactive;
      }
      break;
  }
  return (state);
}
References KernelState, osKernelInactive, osKernelLocked, osKernelReady, osKernelRunning, taskSCHEDULER_NOT_STARTED, taskSCHEDULER_RUNNING, taskSCHEDULER_SUSPENDED, and xTaskGetSchedulerState().
osKernelGetSysTimerCount()
uint32_t osKernelGetSysTimerCount (void)
Get the RTOS kernel system timer count.
Returns
RTOS kernel current system timer count as 32-bit value.
Definition at line 415 of file cmsis_os2.c.
{
  uint32_t irqmask = IS_IRQ_MASKED();
  TickType_t ticks;
  uint32_t val;
  __disable_irq();
  ticks = xTaskGetTickCount();
  val   = OS_Tick_GetCount();
  if (OS_Tick_GetOverflow() != 0U) {
    val = OS_Tick_GetCount();
    ticks++;
  }
  val += ticks * OS_Tick_GetInterval();
  if (irqmask == 0U) {
    __enable_irq();
  }
  return (val);
}
References IS_IRQ_MASKED, OS_Tick_GetCount(), OS_Tick_GetInterval(), OS_Tick_GetOverflow(), and xTaskGetTickCount().
osKernelGetSysTimerFreq()
uint32_t osKernelGetSysTimerFreq (void)
Get the RTOS kernel system timer frequency.
Returns
frequency of the system timer in hertz, i.e. timer ticks per second.
Definition at line 438 of file cmsis_os2.c.
{
  return (configCPU_CLOCK_HZ);
}
References configCPU_CLOCK_HZ.
osKernelGetTickCount()
uint32_t osKernelGetTickCount (void)
Get the RTOS kernel tick count.
Returns
RTOS kernel current tick count.
Definition at line 383 of file cmsis_os2.c.
{
  TickType_t ticks;
  if (IS_IRQ()) {
    ticks = xTaskGetTickCountFromISR();
  } else {
    ticks = xTaskGetTickCount();
  }
  return (ticks);
}
References IS_IRQ, xTaskGetTickCount(), and xTaskGetTickCountFromISR().
osKernelGetTickFreq()
uint32_t osKernelGetTickFreq (void)
Get the RTOS kernel tick frequency.
Returns
frequency of the kernel tick in hertz, i.e. kernel ticks per second.
Definition at line 395 of file cmsis_os2.c.
{
  return (configTICK_RATE_HZ);
}
References configTICK_RATE_HZ.
osKernelInitialize()
osStatus_t osKernelInitialize (void)
Initialize the RTOS Kernel.
Returns
status code that indicates the execution status of the function.
Definition at line 198 of file cmsis_os2.c.
{
  osStatus_t stat;
  if (IS_IRQ()) {
    stat = osErrorISR;
  }
  else {
    if (KernelState == osKernelInactive) {
      #if defined(USE_TRACE_EVENT_RECORDER)
        EvrFreeRTOSSetup(0U);
      #endif
      #if defined(USE_FreeRTOS_HEAP_5) && (HEAP_5_REGION_SETUP == 1)
        vPortDefineHeapRegions (configHEAP_5_REGIONS);
      #endif
      KernelState = osKernelReady;
      stat = osOK;
    } else {
      stat = osError;
    }
  }
  return (stat);
}
References IS_IRQ, KernelState, osError, osErrorISR, osKernelInactive, osKernelReady, osOK, and vPortDefineHeapRegions().
Referenced by main().
osKernelLock()
int32_t osKernelLock (void)
Lock the RTOS Kernel scheduler.
Returns
previous lock state (1 - locked, 0 - not locked, error code if negative).
Definition at line 288 of file cmsis_os2.c.
{
  int32_t lock;
  if (IS_IRQ()) {
    lock = (int32_t)osErrorISR;
  }
  else {
    switch (xTaskGetSchedulerState()) {
      case taskSCHEDULER_SUSPENDED:
        lock = 1;
        break;
      case taskSCHEDULER_RUNNING:
        vTaskSuspendAll();
        lock = 0;
        break;
      case taskSCHEDULER_NOT_STARTED:
      default:
        lock = (int32_t)osError;
        break;
    }
  }
  return (lock);
}
References IS_IRQ, osError, osErrorISR, taskSCHEDULER_NOT_STARTED, taskSCHEDULER_RUNNING, taskSCHEDULER_SUSPENDED, vTaskSuspendAll(), and xTaskGetSchedulerState().
osKernelRestoreLock()
int32_t osKernelRestoreLock (int32_t lock)
Restore the RTOS Kernel scheduler lock state.
Parameters
[in] lock lock state obtained by osKernelLock or osKernelUnlock.
Returns
new lock state (1 - locked, 0 - not locked, error code if negative).
Definition at line 347 of file cmsis_os2.c.
{
  if (IS_IRQ()) {
    lock = (int32_t)osErrorISR;
  }
  else {
    switch (xTaskGetSchedulerState()) {
      case taskSCHEDULER_SUSPENDED:
      case taskSCHEDULER_RUNNING:
        if (lock == 1) {
          vTaskSuspendAll();
        }
        else {
          if (lock != 0) {
            lock = (int32_t)osError;
          }
          else {
            if (xTaskResumeAll() != pdTRUE) {
              if (xTaskGetSchedulerState() != taskSCHEDULER_RUNNING) {
                lock = (int32_t)osError;
              }
            }
          }
        }
        break;
      case taskSCHEDULER_NOT_STARTED:
      default:
        lock = (int32_t)osError;
        break;
    }
  }
  return (lock);
}
References IS_IRQ, osError, osErrorISR, pdTRUE, taskSCHEDULER_NOT_STARTED, taskSCHEDULER_RUNNING, taskSCHEDULER_SUSPENDED, vTaskSuspendAll(), xTaskGetSchedulerState(), and xTaskResumeAll().
osKernelResume()
void osKernelResume (uint32_t sleep_ticks)
Resume the RTOS Kernel scheduler.
Parameters
[in] sleep_ticks time in ticks for how long the system was in sleep or power-down mode.
osKernelStart()
osStatus_t osKernelStart (void)
Start the RTOS Kernel scheduler.
Returns
status code that indicates the execution status of the function.
Definition at line 265 of file cmsis_os2.c.
{
  osStatus_t stat;
  if (IS_IRQ()) {
    stat = osErrorISR;
  }
  else {
    if (KernelState == osKernelReady) {
      /* Ensure SVC priority is at the reset value */
      SVC_Setup();
      /* Change state to enable IRQ masking check */
      KernelState = osKernelRunning;
      /* Start the kernel scheduler */
      vTaskStartScheduler();
      stat = osOK;
    } else {
      stat = osError;
    }
  }
  return (stat);
}
References IS_IRQ, KernelState, osError, osErrorISR, osKernelReady, osKernelRunning, osOK, SVC_Setup(), and vTaskStartScheduler().
Referenced by main().
osKernelSuspend()
uint32_t osKernelSuspend (void)
Suspend the RTOS Kernel scheduler.
Returns
time in ticks, for how long the system can sleep or power-down.
osKernelUnlock()
int32_t osKernelUnlock (void)
Unlock the RTOS Kernel scheduler.
Returns
previous lock state (1 - locked, 0 - not locked, error code if negative).
Definition at line 315 of file cmsis_os2.c.
{
  int32_t lock;
  if (IS_IRQ()) {
    lock = (int32_t)osErrorISR;
  }
  else {
    switch (xTaskGetSchedulerState()) {
      case taskSCHEDULER_SUSPENDED:
        lock = 1;
        if (xTaskResumeAll() != pdTRUE) {
          if (xTaskGetSchedulerState() == taskSCHEDULER_SUSPENDED) {
            lock = (int32_t)osError;
          }
        }
        break;
      case taskSCHEDULER_RUNNING:
        lock = 0;
        break;
      case taskSCHEDULER_NOT_STARTED:
      default:
        lock = (int32_t)osError;
        break;
    }
  }
  return (lock);
}
References IS_IRQ, osError, osErrorISR, pdTRUE, taskSCHEDULER_NOT_STARTED, taskSCHEDULER_RUNNING, taskSCHEDULER_SUSPENDED, xTaskGetSchedulerState(), and xTaskResumeAll().
osMemoryPoolAlloc()
void * osMemoryPoolAlloc (osMemoryPoolId_t mp_id, uint32_t timeout)
Allocate a memory block from a Memory Pool.
Parameters
[in] mp_id memory pool ID obtained by osMemoryPoolNew.
[in] timeout CMSIS_RTOS_TimeOutValue or 0 in case of no time-out.
Returns
address of the allocated memory block or NULL in case of no memory is available.
osMemoryPoolDelete()
osStatus_t osMemoryPoolDelete (osMemoryPoolId_t mp_id)
Delete a Memory Pool object.
Parameters
[in] mp_id memory pool ID obtained by osMemoryPoolNew.
Returns
status code that indicates the execution status of the function.
osMemoryPoolFree()
osStatus_t osMemoryPoolFree (osMemoryPoolId_t mp_id, void * block)
Return an allocated memory block back to a Memory Pool.
Parameters
[in] mp_id memory pool ID obtained by osMemoryPoolNew.
[in] block address of the allocated memory block to be returned to the memory pool.
Returns
status code that indicates the execution status of the function.
osMemoryPoolGetBlockSize()
uint32_t osMemoryPoolGetBlockSize (osMemoryPoolId_t mp_id)
Get memory block size in a Memory Pool.
Parameters
[in] mp_id memory pool ID obtained by osMemoryPoolNew.
Returns
memory block size in bytes.
osMemoryPoolGetCapacity()
uint32_t osMemoryPoolGetCapacity (osMemoryPoolId_t mp_id)
Get maximum number of memory blocks in a Memory Pool.
Parameters
[in] mp_id memory pool ID obtained by osMemoryPoolNew.
Returns
maximum number of memory blocks.
osMemoryPoolGetCount()
uint32_t osMemoryPoolGetCount (osMemoryPoolId_t mp_id)
Get number of memory blocks used in a Memory Pool.
Parameters
[in] mp_id memory pool ID obtained by osMemoryPoolNew.
Returns
number of memory blocks used.
osMemoryPoolGetName()
const char * osMemoryPoolGetName (osMemoryPoolId_t mp_id)
Get name of a Memory Pool object.
Parameters
[in] mp_id memory pool ID obtained by osMemoryPoolNew.
Returns
name as NULL terminated string.
osMemoryPoolGetSpace()
uint32_t osMemoryPoolGetSpace (osMemoryPoolId_t mp_id)
Get number of memory blocks available in a Memory Pool.
Parameters
[in] mp_id memory pool ID obtained by osMemoryPoolNew.
Returns
number of memory blocks available.
osMemoryPoolNew()
osMemoryPoolId_t osMemoryPoolNew (uint32_t block_count, uint32_t block_size, const osMemoryPoolAttr_t * attr)
Create and Initialize a Memory Pool object.
Parameters
[in] block_count maximum number of memory blocks in memory pool.
[in] block_size memory block size in bytes.
[in] attr memory pool attributes; NULL: default values.
Returns
memory pool ID for reference by other functions or NULL in case of error.
osMessageQueueDelete()
osStatus_t osMessageQueueDelete (osMessageQueueId_t mq_id)
Delete a Message Queue object.
Parameters
[in] mq_id message queue ID obtained by osMessageQueueNew.
Returns
status code that indicates the execution status of the function.
Definition at line 1918 of file cmsis_os2.c.
{
  QueueHandle_t hQueue = (QueueHandle_t)mq_id;
  osStatus_t stat;
#ifndef USE_FreeRTOS_HEAP_1
  if (IS_IRQ()) {
    stat = osErrorISR;
  }
  else if (hQueue == NULL) {
    stat = osErrorParameter;
  }
  else {
    #if (configQUEUE_REGISTRY_SIZE > 0)
    vQueueUnregisterQueue (hQueue);
    #endif
    stat = osOK;
    vQueueDelete (hQueue);
  }
#else
  stat = osError;
#endif
  return (stat);
}
References IS_IRQ, osError, osErrorISR, osErrorParameter, osOK, vQueueDelete(), and vQueueUnregisterQueue.
osMessageQueueGet()
osStatus_t osMessageQueueGet (osMessageQueueId_t mq_id, void * msg_ptr, uint8_t * msg_prio, uint32_t timeout)
Get a Message from a Queue or timeout if Queue is empty.
Parameters
[in] mq_id message queue ID obtained by osMessageQueueNew.
[out] msg_ptr pointer to buffer for message to get from a queue.
[out] msg_prio pointer to buffer for message priority or NULL.
[in] timeout CMSIS_RTOS_TimeOutValue or 0 in case of no time-out.
Returns
status code that indicates the execution status of the function.
Definition at line 1791 of file cmsis_os2.c.
{
  QueueHandle_t hQueue = (QueueHandle_t)mq_id;
  osStatus_t stat;
  BaseType_t yield;
  (void)msg_prio; /* Message priority is ignored */
  stat = osOK;
  if (IS_IRQ()) {
    if ((hQueue == NULL) || (msg_ptr == NULL) || (timeout != 0U)) {
      stat = osErrorParameter;
    }
    else {
      yield = pdFALSE;
      if (xQueueReceiveFromISR (hQueue, msg_ptr, &yield) != pdPASS) {
        stat = osErrorResource;
      } else {
        portYIELD_FROM_ISR (yield);
      }
    }
  }
  else {
    if ((hQueue == NULL) || (msg_ptr == NULL)) {
      stat = osErrorParameter;
    }
    else {
      if (xQueueReceive (hQueue, msg_ptr, (TickType_t)timeout) != pdPASS) {
        if (timeout != 0U) {
          stat = osErrorTimeout;
        } else {
          stat = osErrorResource;
        }
      }
    }
  }
  return (stat);
}
References IS_IRQ, osErrorParameter, osErrorResource, osErrorTimeout, osOK, pdFALSE, pdPASS, portYIELD_FROM_ISR, xQueueReceive(), and xQueueReceiveFromISR().
Referenced by MessageQueueConsumer().
osMessageQueueGetCapacity()
uint32_t osMessageQueueGetCapacity (osMessageQueueId_t mq_id)
Get maximum number of messages in a Message Queue.
Parameters
[in] mq_id message queue ID obtained by osMessageQueueNew.
Returns
maximum number of messages.
Definition at line 1832 of file cmsis_os2.c.
{
  StaticQueue_t *mq = (StaticQueue_t *)mq_id;
  uint32_t capacity;
  if (mq == NULL) {
    capacity = 0U;
  } else {
    /* capacity = pxQueue->uxLength */
    capacity = mq->uxDummy4[1];
  }
  return (capacity);
}
References xSTATIC_QUEUE::uxDummy4.
osMessageQueueGetCount()
uint32_t osMessageQueueGetCount (osMessageQueueId_t mq_id)
Get number of queued messages in a Message Queue.
Parameters
[in] mq_id message queue ID obtained by osMessageQueueNew.
Returns
number of queued messages.
Definition at line 1860 of file cmsis_os2.c.
{
  QueueHandle_t hQueue = (QueueHandle_t)mq_id;
  UBaseType_t count;
  if (hQueue == NULL) {
    count = 0U;
  }
  else if (IS_IRQ()) {
    count = uxQueueMessagesWaitingFromISR (hQueue);
  }
  else {
    count = uxQueueMessagesWaiting (hQueue);
  }
  return ((uint32_t)count);
}
References IS_IRQ, uxQueueMessagesWaiting(), and uxQueueMessagesWaitingFromISR().
osMessageQueueGetMsgSize()
uint32_t osMessageQueueGetMsgSize (osMessageQueueId_t mq_id)
Get maximum message size in a Memory Pool.
Parameters
[in] mq_id message queue ID obtained by osMessageQueueNew.
Returns
maximum message size in bytes.
Definition at line 1846 of file cmsis_os2.c.
{
  StaticQueue_t *mq = (StaticQueue_t *)mq_id;
  uint32_t size;
  if (mq == NULL) {
    size = 0U;
  } else {
    /* size = pxQueue->uxItemSize */
    size = mq->uxDummy4[2];
  }
  return (size);
}
References xSTATIC_QUEUE::uxDummy4.
osMessageQueueGetName()
const char * osMessageQueueGetName (osMessageQueueId_t mq_id)
Get name of a Message Queue object.
Parameters
[in] mq_id message queue ID obtained by osMessageQueueNew.
Returns
name as NULL terminated string.
osMessageQueueGetSpace()
uint32_t osMessageQueueGetSpace (osMessageQueueId_t mq_id)
Get number of available slots for messages in a Message Queue.
Parameters
[in] mq_id message queue ID obtained by osMessageQueueNew.
Returns
number of available slots for messages.
Definition at line 1877 of file cmsis_os2.c.
{
  StaticQueue_t *mq = (StaticQueue_t *)mq_id;
  uint32_t space;
  uint32_t isrm;
  if (mq == NULL) {
    space = 0U;
  }
  else if (IS_IRQ()) {
    isrm = taskENTER_CRITICAL_FROM_ISR();
    /* space = pxQueue->uxLength - pxQueue->uxMessagesWaiting; */
    space = mq->uxDummy4[1] - mq->uxDummy4[0];
    taskEXIT_CRITICAL_FROM_ISR(isrm);
  }
  else {
    space = (uint32_t)uxQueueSpacesAvailable ((QueueHandle_t)mq);
  }
  return (space);
}
References IS_IRQ, taskENTER_CRITICAL_FROM_ISR, taskEXIT_CRITICAL_FROM_ISR, xSTATIC_QUEUE::uxDummy4, and uxQueueSpacesAvailable().
osMessageQueueNew()
osMessageQueueId_t osMessageQueueNew (uint32_t msg_count, uint32_t msg_size, const osMessageQueueAttr_t * attr)
Create and Initialize a Message Queue object.
Parameters
[in] msg_count maximum number of messages in queue.
[in] msg_size maximum message size in bytes.
[in] attr message queue attributes; NULL: default values.
Returns
message queue ID for reference by other functions or NULL in case of error.
Definition at line 1693 of file cmsis_os2.c.
{
  QueueHandle_t hQueue;
  int32_t mem;
  #if (configQUEUE_REGISTRY_SIZE > 0)
  const char *name;
  #endif
  hQueue = NULL;
  if (!IS_IRQ() && (msg_count > 0U) && (msg_size > 0U)) {
    mem = -1;
    if (attr != NULL) {
      if ((attr->cb_mem != NULL) && (attr->cb_size >= sizeof(StaticQueue_t)) &&
          (attr->mq_mem != NULL) && (attr->mq_size >= (msg_count * msg_size))) {
        mem = 1;
      }
      else {
        if ((attr->cb_mem == NULL) && (attr->cb_size == 0U) &&
            (attr->mq_mem == NULL) && (attr->mq_size == 0U)) {
          mem = 0;
        }
      }
    }
    else {
      mem = 0;
    }
    if (mem == 1) {
      #if (configSUPPORT_STATIC_ALLOCATION == 1)
        hQueue = xQueueCreateStatic (msg_count, msg_size, attr->mq_mem, attr->cb_mem);
      #endif
    }
    else {
      if (mem == 0) {
        #if (configSUPPORT_DYNAMIC_ALLOCATION == 1)
          hQueue = xQueueCreate (msg_count, msg_size);
        #endif
      }
    }
    #if (configQUEUE_REGISTRY_SIZE > 0)
    if (hQueue != NULL) {
      if (attr != NULL) {
        name = attr->name;
      } else {
        name = NULL;
      }
      vQueueAddToRegistry (hQueue, name);
    }
    #endif
  }
  return ((osMessageQueueId_t)hQueue);
}
References osMessageQueueAttr_t::cb_mem, osMessageQueueAttr_t::cb_size, IS_IRQ, osMessageQueueAttr_t::mq_mem, osMessageQueueAttr_t::mq_size, osMessageQueueAttr_t::name, and vQueueAddToRegistry.
Referenced by main().
osMessageQueuePut()
osStatus_t osMessageQueuePut (osMessageQueueId_t mq_id, const void * msg_ptr, uint8_t msg_prio, uint32_t timeout)
Put a Message into a Queue or timeout if Queue is full.
Parameters
[in] mq_id message queue ID obtained by osMessageQueueNew.
[in] msg_ptr pointer to buffer with message to put into a queue.
[in] msg_prio message priority.
[in] timeout CMSIS_RTOS_TimeOutValue or 0 in case of no time-out.
Returns
status code that indicates the execution status of the function.
Definition at line 1750 of file cmsis_os2.c.
{
  QueueHandle_t hQueue = (QueueHandle_t)mq_id;
  osStatus_t stat;
  BaseType_t yield;
  (void)msg_prio; /* Message priority is ignored */
  stat = osOK;
  if (IS_IRQ()) {
    if ((hQueue == NULL) || (msg_ptr == NULL) || (timeout != 0U)) {
      stat = osErrorParameter;
    }
    else {
      yield = pdFALSE;
      if (xQueueSendToBackFromISR (hQueue, msg_ptr, &yield) != pdTRUE) {
        stat = osErrorResource;
      } else {
        portYIELD_FROM_ISR (yield);
      }
    }
  }
  else {
    if ((hQueue == NULL) || (msg_ptr == NULL)) {
      stat = osErrorParameter;
    }
    else {
      if (xQueueSendToBack (hQueue, msg_ptr, (TickType_t)timeout) != pdPASS) {
        if (timeout != 0U) {
          stat = osErrorTimeout;
        } else {
          stat = osErrorResource;
        }
      }
    }
  }
  return (stat);
}
References IS_IRQ, osErrorParameter, osErrorResource, osErrorTimeout, osOK, pdFALSE, pdPASS, pdTRUE, portYIELD_FROM_ISR, xQueueSendToBack, and xQueueSendToBackFromISR.
Referenced by MessageQueueProducer().
osMessageQueueReset()
osStatus_t osMessageQueueReset (osMessageQueueId_t mq_id)
Reset a Message Queue to initial empty state.
Parameters
[in] mq_id message queue ID obtained by osMessageQueueNew.
Returns
status code that indicates the execution status of the function.
Definition at line 1900 of file cmsis_os2.c.
{
  QueueHandle_t hQueue = (QueueHandle_t)mq_id;
  osStatus_t stat;
  if (IS_IRQ()) {
    stat = osErrorISR;
  }
  else if (hQueue == NULL) {
    stat = osErrorParameter;
  }
  else {
    stat = osOK;
    (void)xQueueReset (hQueue);
  }
  return (stat);
}
References IS_IRQ, osErrorISR, osErrorParameter, osOK, and xQueueReset.
osMutexAcquire()
osStatus_t osMutexAcquire (osMutexId_t mutex_id, uint32_t timeout)
Acquire a Mutex or timeout if it is locked.
Parameters
[in] mutex_id mutex ID obtained by osMutexNew.
[in] timeout CMSIS_RTOS_TimeOutValue or 0 in case of no time-out.
Returns
status code that indicates the execution status of the function.
osMutexDelete()
osStatus_t osMutexDelete (osMutexId_t mutex_id)
Delete a Mutex object.
Parameters
[in] mutex_id mutex ID obtained by osMutexNew.
Returns
status code that indicates the execution status of the function.
osMutexGetName()
const char * osMutexGetName (osMutexId_t mutex_id)
Get name of a Mutex object.
Parameters
[in] mutex_id mutex ID obtained by osMutexNew.
Returns
name as NULL terminated string.
osMutexGetOwner()
osThreadId_t osMutexGetOwner (osMutexId_t mutex_id)
Get Thread which owns a Mutex object.
Parameters
[in] mutex_id mutex ID obtained by osMutexNew.
Returns
thread ID of owner thread or NULL when mutex was not acquired.
osMutexNew()
osMutexId_t osMutexNew (const osMutexAttr_t * attr)
Create and Initialize a Mutex object.
Parameters
[in] attr mutex attributes; NULL: default values.
Returns
mutex ID for reference by other functions or NULL in case of error.
osMutexRelease()
osStatus_t osMutexRelease (osMutexId_t mutex_id)
Release a Mutex that was acquired by osMutexAcquire.
Parameters
[in] mutex_id mutex ID obtained by osMutexNew.
Returns
status code that indicates the execution status of the function.
osSemaphoreAcquire()
osStatus_t osSemaphoreAcquire (osSemaphoreId_t semaphore_id, uint32_t timeout)
Acquire a Semaphore token or timeout if no tokens are available.
Parameters
[in] semaphore_id semaphore ID obtained by osSemaphoreNew.
[in] timeout CMSIS_RTOS_TimeOutValue or 0 in case of no time-out.
Returns
status code that indicates the execution status of the function.
Definition at line 1584 of file cmsis_os2.c.
{
  SemaphoreHandle_t hSemaphore = (SemaphoreHandle_t)semaphore_id;
  osStatus_t stat;
  BaseType_t yield;
  stat = osOK;
  if (hSemaphore == NULL) {
    stat = osErrorParameter;
  }
  else if (IS_IRQ()) {
    if (timeout != 0U) {
      stat = osErrorParameter;
    }
    else {
      yield = pdFALSE;
      if (xSemaphoreTakeFromISR (hSemaphore, &yield) != pdPASS) {
        stat = osErrorResource;
      } else {
        portYIELD_FROM_ISR (yield);
      }
    }
  }
  else {
    if (xSemaphoreTake (hSemaphore, (TickType_t)timeout) != pdPASS) {
      if (timeout != 0U) {
        stat = osErrorTimeout;
      } else {
        stat = osErrorResource;
      }
    }
  }
  return (stat);
}
References IS_IRQ, osErrorParameter, osErrorResource, osErrorTimeout, osOK, pdFALSE, pdPASS, portYIELD_FROM_ISR, xSemaphoreTake, and xSemaphoreTakeFromISR.
osSemaphoreDelete()
osStatus_t osSemaphoreDelete (osSemaphoreId_t semaphore_id)
Delete a Semaphore object.
Parameters
[in] semaphore_id semaphore ID obtained by osSemaphoreNew.
Returns
status code that indicates the execution status of the function.
Definition at line 1665 of file cmsis_os2.c.
{
  SemaphoreHandle_t hSemaphore = (SemaphoreHandle_t)semaphore_id;
  osStatus_t stat;
#ifndef USE_FreeRTOS_HEAP_1
  if (IS_IRQ()) {
    stat = osErrorISR;
  }
  else if (hSemaphore == NULL) {
    stat = osErrorParameter;
  }
  else {
    #if (configQUEUE_REGISTRY_SIZE > 0)
    vQueueUnregisterQueue (hSemaphore);
    #endif
    stat = osOK;
    vSemaphoreDelete (hSemaphore);
  }
#else
  stat = osError;
#endif
  return (stat);
}
References IS_IRQ, osError, osErrorISR, osErrorParameter, osOK, vQueueUnregisterQueue, and vSemaphoreDelete.
osSemaphoreGetCount()
uint32_t osSemaphoreGetCount (osSemaphoreId_t semaphore_id)
Get current Semaphore token count.
Parameters
[in] semaphore_id semaphore ID obtained by osSemaphoreNew.
Returns
number of tokens available.
Definition at line 1649 of file cmsis_os2.c.
{
  SemaphoreHandle_t hSemaphore = (SemaphoreHandle_t)semaphore_id;
  uint32_t count;
  if (hSemaphore == NULL) {
    count = 0U;
  }
  else if (IS_IRQ()) {
    count = uxQueueMessagesWaitingFromISR (hSemaphore);
  } else {
    count = (uint32_t)uxSemaphoreGetCount (hSemaphore);
  }
  return (count);
}
References IS_IRQ, uxQueueMessagesWaitingFromISR(), and uxSemaphoreGetCount.
osSemaphoreGetName()
const char * osSemaphoreGetName (osSemaphoreId_t semaphore_id)
Get name of a Semaphore object.
Parameters
[in] semaphore_id semaphore ID obtained by osSemaphoreNew.
Returns
name as NULL terminated string.
osSemaphoreNew()
osSemaphoreId_t osSemaphoreNew (uint32_t max_count, uint32_t initial_count, const osSemaphoreAttr_t * attr)
Create and Initialize a Semaphore object.
Parameters
[in] max_count maximum number of available tokens.
[in] initial_count initial number of available tokens.
[in] attr semaphore attributes; NULL: default values.
Returns
semaphore ID for reference by other functions or NULL in case of error.
Definition at line 1509 of file cmsis_os2.c.
{
  SemaphoreHandle_t hSemaphore;
  int32_t mem;
  #if (configQUEUE_REGISTRY_SIZE > 0)
  const char *name;
  #endif
  hSemaphore = NULL;
  if (!IS_IRQ() && (max_count > 0U) && (initial_count <= max_count)) {
    mem = -1;
    if (attr != NULL) {
      if ((attr->cb_mem != NULL) && (attr->cb_size >= sizeof(StaticSemaphore_t))) {
        mem = 1;
      }
      else {
        if ((attr->cb_mem == NULL) && (attr->cb_size == 0U)) {
          mem = 0;
        }
      }
    }
    else {
      mem = 0;
    }
    if (mem != -1) {
      if (max_count == 1U) {
        if (mem == 1) {
          #if (configSUPPORT_STATIC_ALLOCATION == 1)
            hSemaphore = xSemaphoreCreateBinaryStatic ((StaticSemaphore_t *)attr->cb_mem);
          #endif
        }
        else {
          #if (configSUPPORT_DYNAMIC_ALLOCATION == 1)
            hSemaphore = xSemaphoreCreateBinary();
          #endif
        }
        if ((hSemaphore != NULL) && (initial_count != 0U)) {
          if (xSemaphoreGive (hSemaphore) != pdPASS) {
            vSemaphoreDelete (hSemaphore);
            hSemaphore = NULL;
          }
        }
      }
      else {
        if (mem == 1) {
          #if (configSUPPORT_STATIC_ALLOCATION == 1)
            hSemaphore = xSemaphoreCreateCountingStatic (max_count, initial_count, (StaticSemaphore_t *)attr->cb_mem);
          #endif
        }
        else {
          #if (configSUPPORT_DYNAMIC_ALLOCATION == 1)
            hSemaphore = xSemaphoreCreateCounting (max_count, initial_count);
          #endif
        }
      }
      #if (configQUEUE_REGISTRY_SIZE > 0)
      if (hSemaphore != NULL) {
        if (attr != NULL) {
          name = attr->name;
        } else {
          name = NULL;
        }
        vQueueAddToRegistry (hSemaphore, name);
      }
      #endif
    }
  }
  return ((osSemaphoreId_t)hSemaphore);
}
References osSemaphoreAttr_t::cb_mem, osSemaphoreAttr_t::cb_size, IS_IRQ, osSemaphoreAttr_t::name, pdPASS, vQueueAddToRegistry, vSemaphoreDelete, and xSemaphoreGive.
osSemaphoreRelease()
osStatus_t osSemaphoreRelease (osSemaphoreId_t semaphore_id)
Release a Semaphore token up to the initial maximum count.
Parameters
[in] semaphore_id semaphore ID obtained by osSemaphoreNew.
Returns
status code that indicates the execution status of the function.
Definition at line 1621 of file cmsis_os2.c.
{
  SemaphoreHandle_t hSemaphore = (SemaphoreHandle_t)semaphore_id;
  osStatus_t stat;
  BaseType_t yield;
  stat = osOK;
  if (hSemaphore == NULL) {
    stat = osErrorParameter;
  }
  else if (IS_IRQ()) {
    yield = pdFALSE;
    if (xSemaphoreGiveFromISR (hSemaphore, &yield) != pdTRUE) {
      stat = osErrorResource;
    } else {
      portYIELD_FROM_ISR (yield);
    }
  }
  else {
    if (xSemaphoreGive (hSemaphore) != pdPASS) {
      stat = osErrorResource;
    }
  }
  return (stat);
}
References IS_IRQ, osErrorParameter, osErrorResource, osOK, pdFALSE, pdPASS, pdTRUE, portYIELD_FROM_ISR, xSemaphoreGive, and xSemaphoreGiveFromISR.
osThreadDetach()
osStatus_t osThreadDetach (osThreadId_t thread_id)
Detach a thread (thread storage can be reclaimed when thread terminates).
Parameters
[in] thread_id thread ID obtained by osThreadNew or osThreadGetId.
Returns
status code that indicates the execution status of the function.
osThreadEnumerate()
uint32_t osThreadEnumerate (osThreadId_t * thread_array, uint32_t array_items)
Enumerate active threads.
Parameters
[out] thread_array pointer to array for retrieving thread IDs.
[in] array_items maximum number of items in array for retrieving thread IDs.
Returns
number of enumerated threads.
Definition at line 699 of file cmsis_os2.c.
{
  uint32_t i, count;
  TaskStatus_t *task;
  if (IS_IRQ() || (thread_array == NULL) || (array_items == 0U)) {
    count = 0U;
  } else {
    vTaskSuspendAll();
    count = uxTaskGetNumberOfTasks();
    task  = pvPortMalloc (count * sizeof(TaskStatus_t));
    if (task != NULL) {
      count = uxTaskGetSystemState (task, count, NULL);
      for (i = 0U; (i < count) && (i < array_items); i++) {
        thread_array[i] = (osThreadId_t)task[i].xHandle;
      }
      count = i;
    }
    (void)xTaskResumeAll();
    vPortFree (task);
  }
  return (count);
}
References IS_IRQ, pvPortMalloc(), uxTaskGetNumberOfTasks(), uxTaskGetSystemState(), vPortFree(), vTaskSuspendAll(), and xTaskResumeAll().
osThreadExit()
void osThreadExit (void)
Terminate execution of current running thread.
Definition at line 650 of file cmsis_os2.c.
{
#ifndef USE_FreeRTOS_HEAP_1
  vTaskDelete (NULL);
#endif
  for (;;);
}
References vTaskDelete().
osThreadFlagsClear()
uint32_t osThreadFlagsClear (uint32_t flags)
Clear the specified Thread Flags of current running thread.
Parameters
[in] flags specifies the flags of the thread that shall be cleared.
Returns
thread flags before clearing or error code if highest bit set.
osThreadFlagsGet()
uint32_t osThreadFlagsGet (void)
Get the current Thread Flags of current running thread.
Returns
current thread flags.
osThreadFlagsSet()
uint32_t osThreadFlagsSet (osThreadId_t thread_id, uint32_t flags)
Set the specified Thread Flags of a thread.
Parameters
[in] thread_id thread ID obtained by osThreadNew or osThreadGetId.
[in] flags specifies the flags of the thread that shall be set.
Returns
thread flags after setting or error code if highest bit set.
osThreadFlagsWait()
uint32_t osThreadFlagsWait (uint32_t flags, uint32_t options, uint32_t timeout)
Wait for one or more Thread Flags of the current running thread to become signaled.
Parameters
[in] flags specifies the flags to wait for.
[in] options specifies flags options (osFlagsXxxx).
[in] timeout CMSIS_RTOS_TimeOutValue or 0 in case of no time-out.
Returns
thread flags before clearing or error code if highest bit set.
osThreadGetCount()
uint32_t osThreadGetCount (void)
Get number of active threads.
Returns
number of active threads.
Definition at line 686 of file cmsis_os2.c.
{
  uint32_t count;
  if (IS_IRQ()) {
    count = 0U;
  } else {
    count = uxTaskGetNumberOfTasks();
  }
  return (count);
}
References IS_IRQ, and uxTaskGetNumberOfTasks().
osThreadGetId()
osThreadId_t osThreadGetId (void)
Return the thread ID of the current running thread.
Returns
thread ID for reference by other functions or NULL in case of error.
Definition at line 525 of file cmsis_os2.c.
{
  osThreadId_t id;
  id = (osThreadId_t)xTaskGetCurrentTaskHandle();
  return (id);
}
References xTaskGetCurrentTaskHandle().
osThreadGetName()
const char * osThreadGetName (osThreadId_t thread_id)
Get name of a thread.
Parameters
[in] thread_id thread ID obtained by osThreadNew or osThreadGetId.
Returns
name as NULL terminated string.
Definition at line 512 of file cmsis_os2.c.
{
  TaskHandle_t hTask = (TaskHandle_t)thread_id;
  const char *name;
  if (IS_IRQ() || (hTask == NULL)) {
    name = NULL;
  } else {
    name = pcTaskGetName (hTask);
  }
  return (name);
}
References IS_IRQ, and pcTaskGetName().
osThreadGetPriority()
osPriority_t osThreadGetPriority (osThreadId_t thread_id)
Get current priority of a thread.
Parameters
[in] thread_id thread ID obtained by osThreadNew or osThreadGetId.
Returns
current priority value of the specified thread.
Definition at line 586 of file cmsis_os2.c.
{
  TaskHandle_t hTask = (TaskHandle_t)thread_id;
  osPriority_t prio;
  if (IS_IRQ() || (hTask == NULL)) {
    prio = osPriorityError;
  } else {
    prio = (osPriority_t)((int32_t)uxTaskPriorityGet (hTask));
  }
  return (prio);
}
References IS_IRQ, osPriorityError, and uxTaskPriorityGet().
osThreadGetStackSize()
uint32_t osThreadGetStackSize (osThreadId_t thread_id)
Get stack size of a thread.
Parameters
[in] thread_id thread ID obtained by osThreadNew or osThreadGetId.
Returns
stack size in bytes.
osThreadGetStackSpace()
uint32_t osThreadGetStackSpace (osThreadId_t thread_id)
Get available stack space of a thread based on stack watermark recording during execution.
Parameters
[in] thread_id thread ID obtained by osThreadNew or osThreadGetId.
Returns
remaining stack space in bytes.
Definition at line 555 of file cmsis_os2.c.
{
  TaskHandle_t hTask = (TaskHandle_t)thread_id;
  uint32_t sz;
  if (IS_IRQ() || (hTask == NULL)) {
    sz = 0U;
  } else {
    sz = (uint32_t)(uxTaskGetStackHighWaterMark(hTask) * sizeof(StackType_t));
  }
  return (sz);
}
References IS_IRQ, and uxTaskGetStackHighWaterMark().
osThreadGetState()
osThreadState_t osThreadGetState (osThreadId_t thread_id)
Get current thread state of a thread.
Parameters
[in] thread_id thread ID obtained by osThreadNew or osThreadGetId.
Returns
current thread state of the specified thread.
Definition at line 533 of file cmsis_os2.c.
{
  TaskHandle_t hTask = (TaskHandle_t)thread_id;
  osThreadState_t state;
  if (IS_IRQ() || (hTask == NULL)) {
    state = osThreadError;
  }
  else {
    switch (eTaskGetState (hTask)) {
      case eRunning:   state = osThreadRunning;    break;
      case eReady:     state = osThreadReady;      break;
      case eBlocked:
      case eSuspended: state = osThreadBlocked;    break;
      case eDeleted:   state = osThreadTerminated; break;
      case eInvalid:
      default:         state = osThreadError;      break;
    }
  }
  return (state);
}
References eBlocked, eDeleted, eInvalid, eReady, eRunning, eSuspended, eTaskGetState(), IS_IRQ, osThreadBlocked, osThreadError, osThreadReady, osThreadRunning, and osThreadTerminated.
osThreadJoin()
osStatus_t osThreadJoin (osThreadId_t thread_id)
Wait for specified thread to terminate.
Parameters
[in] thread_id thread ID obtained by osThreadNew or osThreadGetId.
Returns
status code that indicates the execution status of the function.
osThreadNew()
osThreadId_t osThreadNew (osThreadFunc_t func, void * argument, const osThreadAttr_t * attr)
Create a thread and add it to Active Threads.
Parameters
[in] func thread function.
[in] argument pointer that is passed to the thread function as start argument.
[in] attr thread attributes; NULL: default values.
Returns
thread ID for reference by other functions or NULL in case of error.
Definition at line 444 of file cmsis_os2.c.
{
  const char *name;
  uint32_t stack;
  TaskHandle_t hTask;
  UBaseType_t prio;
  int32_t mem;
  hTask = NULL;
  if (!IS_IRQ() && (func != NULL)) {
    stack = configMINIMAL_STACK_SIZE;
    prio  = (UBaseType_t)osPriorityNormal;
    name = NULL;
    mem  = -1;
    if (attr != NULL) {
      if (attr->name != NULL) {
        name = attr->name;
      }
      if (attr->priority != osPriorityNone) {
        prio = (UBaseType_t)attr->priority;
      }
      if ((prio < osPriorityIdle) || (prio > osPriorityISR) || ((attr->attr_bits & osThreadJoinable) == osThreadJoinable)) {
        return (NULL);
      }
      if (attr->stack_size > 0U) {
        /* In FreeRTOS stack is not in bytes, but in sizeof(StackType_t) which is 4 on ARM ports.       */
        /* Stack size should be therefore 4 byte aligned in order to avoid division caused side effects */
        stack = attr->stack_size / sizeof(StackType_t);
      }
      if ((attr->cb_mem    != NULL) && (attr->cb_size    >= sizeof(StaticTask_t)) &&
          (attr->stack_mem != NULL) && (attr->stack_size >  0U)) {
        mem = 1;
      }
      else {
        if ((attr->cb_mem == NULL) && (attr->cb_size == 0U) && (attr->stack_mem == NULL)) {
          mem = 0;
        }
      }
    }
    else {
      mem = 0;
    }
    if (mem == 1) {
      #if (configSUPPORT_STATIC_ALLOCATION == 1)
        hTask = xTaskCreateStatic ((TaskFunction_t)func, name, stack, argument, prio, (StackType_t  *)attr->stack_mem,
                                                                                      (StaticTask_t *)attr->cb_mem);
      #endif
    }
    else {
      if (mem == 0) {
        #if (configSUPPORT_DYNAMIC_ALLOCATION == 1)
          if (xTaskCreate ((TaskFunction_t)func, name, (uint16_t)stack, argument, prio, &hTask) != pdPASS) {
            hTask = NULL;
          }
        #endif
      }
    }
  }
  return ((osThreadId_t)hTask);
}
References osThreadAttr_t::attr_bits, osThreadAttr_t::cb_mem, osThreadAttr_t::cb_size, configMINIMAL_STACK_SIZE, IS_IRQ, osThreadAttr_t::name, osPriorityIdle, osPriorityISR, osPriorityNone, osPriorityNormal, osThreadJoinable, pdPASS, osThreadAttr_t::priority, osThreadAttr_t::stack_mem, and osThreadAttr_t::stack_size.
Referenced by main().
osThreadResume()
osStatus_t osThreadResume (osThreadId_t thread_id)
Resume execution of a thread.
Parameters
[in] thread_id thread ID obtained by osThreadNew or osThreadGetId.
Returns
status code that indicates the execution status of the function.
Definition at line 631 of file cmsis_os2.c.
{
  TaskHandle_t hTask = (TaskHandle_t)thread_id;
  osStatus_t stat;
  if (IS_IRQ()) {
    stat = osErrorISR;
  }
  else if (hTask == NULL) {
    stat = osErrorParameter;
  }
  else {
    stat = osOK;
    vTaskResume (hTask);
  }
  return (stat);
}
References IS_IRQ, osErrorISR, osErrorParameter, osOK, and vTaskResume().
osThreadSetPriority()
osStatus_t osThreadSetPriority (osThreadId_t thread_id, osPriority_t priority)
Change priority of a thread.
Parameters
[in] thread_id thread ID obtained by osThreadNew or osThreadGetId.
[in] priority new priority value for the thread function.
Returns
status code that indicates the execution status of the function.
Definition at line 568 of file cmsis_os2.c.
{
  TaskHandle_t hTask = (TaskHandle_t)thread_id;
  osStatus_t stat;
  if (IS_IRQ()) {
    stat = osErrorISR;
  }
  else if ((hTask == NULL) || (priority < osPriorityIdle) || (priority > osPriorityISR)) {
    stat = osErrorParameter;
  }
  else {
    stat = osOK;
    vTaskPrioritySet (hTask, (UBaseType_t)priority);
  }
  return (stat);
}
References IS_IRQ, osErrorISR, osErrorParameter, osOK, osPriorityIdle, osPriorityISR, and vTaskPrioritySet().
osThreadSuspend()
osStatus_t osThreadSuspend (osThreadId_t thread_id)
Suspend execution of a thread.
Parameters
[in] thread_id thread ID obtained by osThreadNew or osThreadGetId.
Returns
status code that indicates the execution status of the function.
Definition at line 613 of file cmsis_os2.c.
{
  TaskHandle_t hTask = (TaskHandle_t)thread_id;
  osStatus_t stat;
  if (IS_IRQ()) {
    stat = osErrorISR;
  }
  else if (hTask == NULL) {
    stat = osErrorParameter;
  }
  else {
    stat = osOK;
    vTaskSuspend (hTask);
  }
  return (stat);
}
References IS_IRQ, osErrorISR, osErrorParameter, osOK, and vTaskSuspend().
osThreadTerminate()
osStatus_t osThreadTerminate (osThreadId_t thread_id)
Terminate execution of a thread.
Parameters
[in] thread_id thread ID obtained by osThreadNew or osThreadGetId.
Returns
status code that indicates the execution status of the function.
Definition at line 657 of file cmsis_os2.c.
{
  TaskHandle_t hTask = (TaskHandle_t)thread_id;
  osStatus_t stat;
#ifndef USE_FreeRTOS_HEAP_1
  eTaskState tstate;
  if (IS_IRQ()) {
    stat = osErrorISR;
  }
  else if (hTask == NULL) {
    stat = osErrorParameter;
  }
  else {
    tstate = eTaskGetState (hTask);
    if (tstate != eDeleted) {
      stat = osOK;
      vTaskDelete (hTask);
    } else {
      stat = osErrorResource;
    }
  }
#else
  stat = osError;
#endif
  return (stat);
}
References eDeleted, eTaskGetState(), IS_IRQ, osError, osErrorISR, osErrorParameter, osErrorResource, osOK, and vTaskDelete().
osThreadYield()
osStatus_t osThreadYield (void)
Pass control to next thread that is in state READY.
Returns
status code that indicates the execution status of the function.
Definition at line 599 of file cmsis_os2.c.
{
  osStatus_t stat;
  if (IS_IRQ()) {
    stat = osErrorISR;
  } else {
    stat = osOK;
    taskYIELD();
  }
  return (stat);
}
References IS_IRQ, osErrorISR, osOK, and taskYIELD.
osTimerDelete()
osStatus_t osTimerDelete (osTimerId_t timer_id)
Delete a timer.
Parameters
[in] timer_id timer ID obtained by osTimerNew.
Returns
status code that indicates the execution status of the function.
osTimerGetName()
const char * osTimerGetName (osTimerId_t timer_id)
Get name of a timer.
Parameters
[in] timer_id timer ID obtained by osTimerNew.
Returns
name as NULL terminated string.
osTimerIsRunning()
uint32_t osTimerIsRunning (osTimerId_t timer_id)
Check if a timer is running.
Parameters
[in] timer_id timer ID obtained by osTimerNew.
Returns
0 not running, 1 running.
osTimerNew()
osTimerId_t osTimerNew (osTimerFunc_t func, osTimerType_t type, void * argument, const osTimerAttr_t * attr)
Create and Initialize a timer.
Parameters
[in] func function pointer to callback function.
[in] type osTimerOnce for one-shot or osTimerPeriodic for periodic behavior.
[in] argument argument to the timer callback function.
[in] attr timer attributes; NULL: default values.
Returns
timer ID for reference by other functions or NULL in case of error.
osTimerStart()
osStatus_t osTimerStart (osTimerId_t timer_id, uint32_t ticks)
Start or restart a timer.
Parameters
[in] timer_id timer ID obtained by osTimerNew.
[in] ticks time ticks value of the timer.
Returns
status code that indicates the execution status of the function.
osTimerStop()
osStatus_t osTimerStop (osTimerId_t timer_id)
Stop a timer.
Parameters
[in] timer_id timer ID obtained by osTimerNew.
Returns
status code that indicates the execution status of the function.