NUCLEO-G0B1RE Examples: NUCLEO-G0B1RE/FreeRTOS_Queues/Middlewares/Third_Party/FreeRTOS/Source/event_groups.c File Reference
event_groups.c File Reference
#include <stdlib.h>
#include "FreeRTOS.h"
#include "task.h"
#include "timers.h"
#include "event_groups.h"
Data Structures
struct EventGroupDef_t
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define eventCLEAR_EVENTS_ON_EXIT_BIT 0x01000000UL
#define eventUNBLOCKED_DUE_TO_BIT_SET 0x02000000UL
#define eventWAIT_FOR_ALL_BITS 0x04000000UL
#define eventEVENT_BITS_CONTROL_BYTES 0xff000000UL
Typedefs
typedef struct EventGroupDef_t EventGroup_t
Functions
static BaseType_t prvTestWaitCondition (const EventBits_t uxCurrentEventBits, const EventBits_t uxBitsToWaitFor, const BaseType_t xWaitForAllBits) PRIVILEGED_FUNCTION
EventBits_t xEventGroupSync (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToSet, const EventBits_t uxBitsToWaitFor, TickType_t xTicksToWait)
EventBits_t xEventGroupWaitBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToWaitFor, const BaseType_t xClearOnExit, const BaseType_t xWaitForAllBits, TickType_t xTicksToWait)
EventBits_t xEventGroupClearBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToClear)
EventBits_t xEventGroupGetBitsFromISR (EventGroupHandle_t xEventGroup)
EventBits_t xEventGroupSetBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToSet)
void vEventGroupDelete (EventGroupHandle_t xEventGroup)
event_groups.h
void vEventGroupSetBitsCallback (void *pvEventGroup, const uint32_t ulBitsToSet)
void vEventGroupClearBitsCallback (void *pvEventGroup, const uint32_t ulBitsToClear)
Macro Definition Documentation
eventCLEAR_EVENTS_ON_EXIT_BIT
#define eventCLEAR_EVENTS_ON_EXIT_BIT 0x01000000UL
Definition at line 57 of file event_groups.c.
Referenced by xEventGroupSetBits(), xEventGroupSync(), and xEventGroupWaitBits().
eventEVENT_BITS_CONTROL_BYTES
#define eventEVENT_BITS_CONTROL_BYTES 0xff000000UL
Definition at line 60 of file event_groups.c.
Referenced by xEventGroupClearBits(), xEventGroupSetBits(), xEventGroupSync(), and xEventGroupWaitBits().
eventUNBLOCKED_DUE_TO_BIT_SET
#define eventUNBLOCKED_DUE_TO_BIT_SET 0x02000000UL
Definition at line 58 of file event_groups.c.
Referenced by vEventGroupDelete(), xEventGroupSetBits(), xEventGroupSync(), and xEventGroupWaitBits().
eventWAIT_FOR_ALL_BITS
#define eventWAIT_FOR_ALL_BITS 0x04000000UL
Definition at line 59 of file event_groups.c.
Referenced by xEventGroupSetBits(), xEventGroupSync(), and xEventGroupWaitBits().
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 34 of file event_groups.c.
Typedef Documentation
EventGroup_t
typedef struct EventGroupDef_t EventGroup_t
Function Documentation
prvTestWaitCondition()
static BaseType_t prvTestWaitCondition (const EventBits_t uxCurrentEventBits, const EventBits_t uxBitsToWaitFor, const BaseType_t xWaitForAllBits) static
Definition at line 671 of file event_groups.c.
{
BaseType_t xWaitConditionMet = pdFALSE;
  if( xWaitForAllBits == pdFALSE )
  {
    /* Task only has to wait for one bit within uxBitsToWaitFor to be
    set.  Is one already set? */
    if( ( uxCurrentEventBits & uxBitsToWaitFor ) != ( EventBits_t ) 0 )
    {
      xWaitConditionMet = pdTRUE;
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
  }
  else
  {
    /* Task has to wait for all the bits in uxBitsToWaitFor to be set.
    Are they set already? */
    if( ( uxCurrentEventBits & uxBitsToWaitFor ) == uxBitsToWaitFor )
    {
      xWaitConditionMet = pdTRUE;
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
  }
  return xWaitConditionMet;
}
References mtCOVERAGE_TEST_MARKER, pdFALSE, and pdTRUE.
Referenced by xEventGroupWaitBits().
vEventGroupClearBitsCallback()
void vEventGroupClearBitsCallback (void * pvEventGroup, const uint32_t ulBitsToClear)
Definition at line 665 of file event_groups.c.
{
  ( void ) xEventGroupClearBits( pvEventGroup, ( EventBits_t ) ulBitsToClear ); /*lint !e9079 Can't avoid cast to void* as a generic timer callback prototype. Callback casts back to original type so safe. */
}
References xEventGroupClearBits().
vEventGroupDelete()
void vEventGroupDelete (EventGroupHandle_t xEventGroup)
event_groups.h
 void xEventGroupDelete( EventGroupHandle_t xEventGroup );
Delete an event group that was previously created by a call to xEventGroupCreate(). Tasks that are blocked on the event group will be unblocked and obtain 0 as the event group's value.
Parameters
xEventGroup The event group being deleted.
Definition at line 613 of file event_groups.c.
{
EventGroup_t *pxEventBits = xEventGroup;
const List_t *pxTasksWaitingForBits = &(pxEventBits->xTasksWaitingForBits);
  vTaskSuspendAll();
  {
    traceEVENT_GROUP_DELETE( xEventGroup );
    while( listCURRENT_LIST_LENGTH( pxTasksWaitingForBits ) > ( UBaseType_t ) 0 )
    {
      /* Unblock the task, returning 0 as the event list is being deleted
      and cannot therefore have any bits set. */
      configASSERT( pxTasksWaitingForBits->xListEnd.pxNext != ( const ListItem_t * ) &( pxTasksWaitingForBits->xListEnd ) );
      vTaskRemoveFromUnorderedEventList( pxTasksWaitingForBits->xListEnd.pxNext, eventUNBLOCKED_DUE_TO_BIT_SET );
    }
    #if( ( configSUPPORT_DYNAMIC_ALLOCATION == 1 ) && ( configSUPPORT_STATIC_ALLOCATION == 0 ) )
    {
      /* The event group can only have been allocated dynamically - free
      it again. */
      vPortFree( pxEventBits );
    }
    #elif( ( configSUPPORT_DYNAMIC_ALLOCATION == 1 ) && ( configSUPPORT_STATIC_ALLOCATION == 1 ) )
    {
      /* The event group could have been allocated statically or
      dynamically, so check before attempting to free the memory. */
      if( pxEventBits->ucStaticallyAllocated == ( uint8_t ) pdFALSE )
      {
        vPortFree( pxEventBits );
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
    #endif /* configSUPPORT_DYNAMIC_ALLOCATION */
  }
  ( void ) xTaskResumeAll();
}
References configASSERT, eventUNBLOCKED_DUE_TO_BIT_SET, listCURRENT_LIST_LENGTH, mtCOVERAGE_TEST_MARKER, pdFALSE, xMINI_LIST_ITEM::pxNext, traceEVENT_GROUP_DELETE, vPortFree(), vTaskRemoveFromUnorderedEventList(), vTaskSuspendAll(), xLIST::xListEnd, xTaskResumeAll(), and EventGroupDef_t::xTasksWaitingForBits.
Referenced by osEventFlagsDelete().
vEventGroupSetBitsCallback()
void vEventGroupSetBitsCallback (void * pvEventGroup, const uint32_t ulBitsToSet)
Definition at line 657 of file event_groups.c.
{
  ( void ) xEventGroupSetBits( pvEventGroup, ( EventBits_t ) ulBitsToSet ); /*lint !e9079 Can't avoid cast to void* as a generic timer callback prototype. Callback casts back to original type so safe. */
}
References xEventGroupSetBits().
xEventGroupClearBits()
EventBits_t xEventGroupClearBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToClear)
Definition at line 461 of file event_groups.c.
{
EventGroup_t *pxEventBits = xEventGroup;
EventBits_t uxReturn;
  /* Check the user is not attempting to clear the bits used by the kernel
  itself. */
  configASSERT( xEventGroup );
  configASSERT( ( uxBitsToClear & eventEVENT_BITS_CONTROL_BYTES ) == 0 );
  taskENTER_CRITICAL();
  {
    traceEVENT_GROUP_CLEAR_BITS( xEventGroup, uxBitsToClear );
    /* The value returned is the event group value prior to the bits being
    cleared. */
    uxReturn = pxEventBits->uxEventBits;
    /* Clear the bits. */
    pxEventBits->uxEventBits &= ~uxBitsToClear;
  }
  taskEXIT_CRITICAL();
  return uxReturn;
}
References configASSERT, eventEVENT_BITS_CONTROL_BYTES, taskENTER_CRITICAL, taskEXIT_CRITICAL, traceEVENT_GROUP_CLEAR_BITS, and EventGroupDef_t::uxEventBits.
Referenced by osEventFlagsClear(), and vEventGroupClearBitsCallback().
xEventGroupGetBitsFromISR()
EventBits_t xEventGroupGetBitsFromISR (EventGroupHandle_t xEventGroup)
Definition at line 503 of file event_groups.c.
{
UBaseType_t uxSavedInterruptStatus;
EventGroup_t const * const pxEventBits = xEventGroup;
EventBits_t uxReturn;
  uxSavedInterruptStatus = portSET_INTERRUPT_MASK_FROM_ISR();
  {
    uxReturn = pxEventBits->uxEventBits;
  }
  portCLEAR_INTERRUPT_MASK_FROM_ISR( uxSavedInterruptStatus );
  return uxReturn;
} /*lint !e818 EventGroupHandle_t is a typedef used in other functions to so can't be pointer to const. */
References portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, and EventGroupDef_t::uxEventBits.
Referenced by osEventFlagsClear(), and osEventFlagsGet().
xEventGroupSetBits()
EventBits_t xEventGroupSetBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToSet)
Definition at line 519 of file event_groups.c.
{
ListItem_t *pxListItem, *pxNext;
ListItem_t const *pxListEnd;
List_t const * pxList;
EventBits_t uxBitsToClear = 0, uxBitsWaitedFor, uxControlBits;
EventGroup_t *pxEventBits = xEventGroup;
BaseType_t xMatchFound = pdFALSE;
  /* Check the user is not attempting to set the bits used by the kernel
  itself. */
  configASSERT( xEventGroup );
  configASSERT( ( uxBitsToSet & eventEVENT_BITS_CONTROL_BYTES ) == 0 );
  pxList = &( pxEventBits->xTasksWaitingForBits );
  pxListEnd = listGET_END_MARKER( pxList ); /*lint !e826 !e740 !e9087 The mini list structure is used as the list end to save RAM.  This is checked and valid. */
  vTaskSuspendAll();
  {
    traceEVENT_GROUP_SET_BITS( xEventGroup, uxBitsToSet );
    pxListItem = listGET_HEAD_ENTRY( pxList );
    /* Set the bits. */
    pxEventBits->uxEventBits |= uxBitsToSet;
    /* See if the new bit value should unblock any tasks. */
    while( pxListItem != pxListEnd )
    {
      pxNext = listGET_NEXT( pxListItem );
      uxBitsWaitedFor = listGET_LIST_ITEM_VALUE( pxListItem );
      xMatchFound = pdFALSE;
      /* Split the bits waited for from the control bits. */
      uxControlBits = uxBitsWaitedFor & eventEVENT_BITS_CONTROL_BYTES;
      uxBitsWaitedFor &= ~eventEVENT_BITS_CONTROL_BYTES;
      if( ( uxControlBits & eventWAIT_FOR_ALL_BITS ) == ( EventBits_t ) 0 )
      {
        /* Just looking for single bit being set. */
        if( ( uxBitsWaitedFor & pxEventBits->uxEventBits ) != ( EventBits_t ) 0 )
        {
          xMatchFound = pdTRUE;
        }
        else
        {
          mtCOVERAGE_TEST_MARKER();
        }
      }
      else if( ( uxBitsWaitedFor & pxEventBits->uxEventBits ) == uxBitsWaitedFor )
      {
        /* All bits are set. */
        xMatchFound = pdTRUE;
      }
      else
      {
        /* Need all bits to be set, but not all the bits were set. */
      }
      if( xMatchFound != pdFALSE )
      {
        /* The bits match.  Should the bits be cleared on exit? */
        if( ( uxControlBits & eventCLEAR_EVENTS_ON_EXIT_BIT ) != ( EventBits_t ) 0 )
        {
          uxBitsToClear |= uxBitsWaitedFor;
        }
        else
        {
          mtCOVERAGE_TEST_MARKER();
        }
        /* Store the actual event flag value in the task's event list
        item before removing the task from the event list.  The
        eventUNBLOCKED_DUE_TO_BIT_SET bit is set so the task knows
        that is was unblocked due to its required bits matching, rather
        than because it timed out. */
        vTaskRemoveFromUnorderedEventList( pxListItem, pxEventBits->uxEventBits | eventUNBLOCKED_DUE_TO_BIT_SET );
      }
      /* Move onto the next list item.  Note pxListItem->pxNext is not
      used here as the list item may have been removed from the event list
      and inserted into the ready/pending reading list. */
      pxListItem = pxNext;
    }
    /* Clear any bits that matched when the eventCLEAR_EVENTS_ON_EXIT_BIT
    bit was set in the control word. */
    pxEventBits->uxEventBits &= ~uxBitsToClear;
  }
  ( void ) xTaskResumeAll();
  return pxEventBits->uxEventBits;
}
References configASSERT, eventCLEAR_EVENTS_ON_EXIT_BIT, eventEVENT_BITS_CONTROL_BYTES, eventUNBLOCKED_DUE_TO_BIT_SET, eventWAIT_FOR_ALL_BITS, listGET_END_MARKER, listGET_HEAD_ENTRY, listGET_LIST_ITEM_VALUE, listGET_NEXT, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, traceEVENT_GROUP_SET_BITS, EventGroupDef_t::uxEventBits, vTaskRemoveFromUnorderedEventList(), vTaskSuspendAll(), xTaskResumeAll(), and EventGroupDef_t::xTasksWaitingForBits.
Referenced by osEventFlagsSet(), vEventGroupSetBitsCallback(), and xEventGroupSync().
xEventGroupSync()
EventBits_t xEventGroupSync (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToSet, const EventBits_t uxBitsToWaitFor, TickType_t xTicksToWait)
Definition at line 191 of file event_groups.c.
{
EventBits_t uxOriginalBitValue, uxReturn;
EventGroup_t *pxEventBits = xEventGroup;
BaseType_t xAlreadyYielded;
BaseType_t xTimeoutOccurred = pdFALSE;
  configASSERT( ( uxBitsToWaitFor & eventEVENT_BITS_CONTROL_BYTES ) == 0 );
  configASSERT( uxBitsToWaitFor != 0 );
  #if ( ( INCLUDE_xTaskGetSchedulerState == 1 ) || ( configUSE_TIMERS == 1 ) )
  {
    configASSERT( !( ( xTaskGetSchedulerState() == taskSCHEDULER_SUSPENDED ) && ( xTicksToWait != 0 ) ) );
  }
  #endif
  vTaskSuspendAll();
  {
    uxOriginalBitValue = pxEventBits->uxEventBits;
    ( void ) xEventGroupSetBits( xEventGroup, uxBitsToSet );
    if( ( ( uxOriginalBitValue | uxBitsToSet ) & uxBitsToWaitFor ) == uxBitsToWaitFor )
    {
      /* All the rendezvous bits are now set - no need to block. */
      uxReturn = ( uxOriginalBitValue | uxBitsToSet );
      /* Rendezvous always clear the bits.  They will have been cleared
      already unless this is the only task in the rendezvous. */
      pxEventBits->uxEventBits &= ~uxBitsToWaitFor;
      xTicksToWait = 0;
    }
    else
    {
      if( xTicksToWait != ( TickType_t ) 0 )
      {
        traceEVENT_GROUP_SYNC_BLOCK( xEventGroup, uxBitsToSet, uxBitsToWaitFor );
        /* Store the bits that the calling task is waiting for in the
        task's event list item so the kernel knows when a match is
        found.  Then enter the blocked state. */
        vTaskPlaceOnUnorderedEventList( &( pxEventBits->xTasksWaitingForBits ), ( uxBitsToWaitFor | eventCLEAR_EVENTS_ON_EXIT_BIT | eventWAIT_FOR_ALL_BITS ), xTicksToWait );
        /* This assignment is obsolete as uxReturn will get set after
        the task unblocks, but some compilers mistakenly generate a
        warning about uxReturn being returned without being set if the
        assignment is omitted. */
        uxReturn = 0;
      }
      else
      {
        /* The rendezvous bits were not set, but no block time was
        specified - just return the current event bit value. */
        uxReturn = pxEventBits->uxEventBits;
        xTimeoutOccurred = pdTRUE;
      }
    }
  }
  xAlreadyYielded = xTaskResumeAll();
  if( xTicksToWait != ( TickType_t ) 0 )
  {
    if( xAlreadyYielded == pdFALSE )
    {
      portYIELD_WITHIN_API();
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
    /* The task blocked to wait for its required bits to be set - at this
    point either the required bits were set or the block time expired.  If
    the required bits were set they will have been stored in the task's
    event list item, and they should now be retrieved then cleared. */
    uxReturn = uxTaskResetEventItemValue();
    if( ( uxReturn & eventUNBLOCKED_DUE_TO_BIT_SET ) == ( EventBits_t ) 0 )
    {
      /* The task timed out, just return the current event bit value. */
      taskENTER_CRITICAL();
      {
        uxReturn = pxEventBits->uxEventBits;
        /* Although the task got here because it timed out before the
        bits it was waiting for were set, it is possible that since it
        unblocked another task has set the bits.  If this is the case
        then it needs to clear the bits before exiting. */
        if( ( uxReturn & uxBitsToWaitFor ) == uxBitsToWaitFor )
        {
          pxEventBits->uxEventBits &= ~uxBitsToWaitFor;
        }
        else
        {
          mtCOVERAGE_TEST_MARKER();
        }
      }
      taskEXIT_CRITICAL();
      xTimeoutOccurred = pdTRUE;
    }
    else
    {
      /* The task unblocked because the bits were set. */
    }
    /* Control bits might be set as the task had blocked should not be
    returned. */
    uxReturn &= ~eventEVENT_BITS_CONTROL_BYTES;
  }
  traceEVENT_GROUP_SYNC_END( xEventGroup, uxBitsToSet, uxBitsToWaitFor, xTimeoutOccurred );
  /* Prevent compiler warnings when trace macros are not used. */
  ( void ) xTimeoutOccurred;
  return uxReturn;
}
References configASSERT, eventCLEAR_EVENTS_ON_EXIT_BIT, eventEVENT_BITS_CONTROL_BYTES, eventUNBLOCKED_DUE_TO_BIT_SET, eventWAIT_FOR_ALL_BITS, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portYIELD_WITHIN_API, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSCHEDULER_SUSPENDED, traceEVENT_GROUP_SYNC_BLOCK, traceEVENT_GROUP_SYNC_END, EventGroupDef_t::uxEventBits, uxTaskResetEventItemValue(), vTaskPlaceOnUnorderedEventList(), vTaskSuspendAll(), xEventGroupSetBits(), xTaskGetSchedulerState(), xTaskResumeAll(), and EventGroupDef_t::xTasksWaitingForBits.
xEventGroupWaitBits()
EventBits_t xEventGroupWaitBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToWaitFor, const BaseType_t xClearOnExit, const BaseType_t xWaitForAllBits, TickType_t xTicksToWait)
Definition at line 311 of file event_groups.c.
{
EventGroup_t *pxEventBits = xEventGroup;
EventBits_t uxReturn, uxControlBits = 0;
BaseType_t xWaitConditionMet, xAlreadyYielded;
BaseType_t xTimeoutOccurred = pdFALSE;
  /* Check the user is not attempting to wait on the bits used by the kernel
  itself, and that at least one bit is being requested. */
  configASSERT( xEventGroup );
  configASSERT( ( uxBitsToWaitFor & eventEVENT_BITS_CONTROL_BYTES ) == 0 );
  configASSERT( uxBitsToWaitFor != 0 );
  #if ( ( INCLUDE_xTaskGetSchedulerState == 1 ) || ( configUSE_TIMERS == 1 ) )
  {
    configASSERT( !( ( xTaskGetSchedulerState() == taskSCHEDULER_SUSPENDED ) && ( xTicksToWait != 0 ) ) );
  }
  #endif
  vTaskSuspendAll();
  {
    const EventBits_t uxCurrentEventBits = pxEventBits->uxEventBits;
    /* Check to see if the wait condition is already met or not. */
    xWaitConditionMet = prvTestWaitCondition( uxCurrentEventBits, uxBitsToWaitFor, xWaitForAllBits );
    if( xWaitConditionMet != pdFALSE )
    {
      /* The wait condition has already been met so there is no need to
      block. */
      uxReturn = uxCurrentEventBits;
      xTicksToWait = ( TickType_t ) 0;
      /* Clear the wait bits if requested to do so. */
      if( xClearOnExit != pdFALSE )
      {
        pxEventBits->uxEventBits &= ~uxBitsToWaitFor;
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
    else if( xTicksToWait == ( TickType_t ) 0 )
    {
      /* The wait condition has not been met, but no block time was
      specified, so just return the current value. */
      uxReturn = uxCurrentEventBits;
      xTimeoutOccurred = pdTRUE;
    }
    else
    {
      /* The task is going to block to wait for its required bits to be
      set.  uxControlBits are used to remember the specified behaviour of
      this call to xEventGroupWaitBits() - for use when the event bits
      unblock the task. */
      if( xClearOnExit != pdFALSE )
      {
        uxControlBits |= eventCLEAR_EVENTS_ON_EXIT_BIT;
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
      if( xWaitForAllBits != pdFALSE )
      {
        uxControlBits |= eventWAIT_FOR_ALL_BITS;
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
      /* Store the bits that the calling task is waiting for in the
      task's event list item so the kernel knows when a match is
      found.  Then enter the blocked state. */
      vTaskPlaceOnUnorderedEventList( &( pxEventBits->xTasksWaitingForBits ), ( uxBitsToWaitFor | uxControlBits ), xTicksToWait );
      /* This is obsolete as it will get set after the task unblocks, but
      some compilers mistakenly generate a warning about the variable
      being returned without being set if it is not done. */
      uxReturn = 0;
      traceEVENT_GROUP_WAIT_BITS_BLOCK( xEventGroup, uxBitsToWaitFor );
    }
  }
  xAlreadyYielded = xTaskResumeAll();
  if( xTicksToWait != ( TickType_t ) 0 )
  {
    if( xAlreadyYielded == pdFALSE )
    {
      portYIELD_WITHIN_API();
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
    /* The task blocked to wait for its required bits to be set - at this
    point either the required bits were set or the block time expired.  If
    the required bits were set they will have been stored in the task's
    event list item, and they should now be retrieved then cleared. */
    uxReturn = uxTaskResetEventItemValue();
    if( ( uxReturn & eventUNBLOCKED_DUE_TO_BIT_SET ) == ( EventBits_t ) 0 )
    {
      taskENTER_CRITICAL();
      {
        /* The task timed out, just return the current event bit value. */
        uxReturn = pxEventBits->uxEventBits;
        /* It is possible that the event bits were updated between this
        task leaving the Blocked state and running again. */
        if( prvTestWaitCondition( uxReturn, uxBitsToWaitFor, xWaitForAllBits ) != pdFALSE )
        {
          if( xClearOnExit != pdFALSE )
          {
            pxEventBits->uxEventBits &= ~uxBitsToWaitFor;
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
        }
        else
        {
          mtCOVERAGE_TEST_MARKER();
        }
        xTimeoutOccurred = pdTRUE;
      }
      taskEXIT_CRITICAL();
    }
    else
    {
      /* The task unblocked because the bits were set. */
    }
    /* The task blocked so control bits may have been set. */
    uxReturn &= ~eventEVENT_BITS_CONTROL_BYTES;
  }
  traceEVENT_GROUP_WAIT_BITS_END( xEventGroup, uxBitsToWaitFor, xTimeoutOccurred );
  /* Prevent compiler warnings when trace macros are not used. */
  ( void ) xTimeoutOccurred;
  return uxReturn;
}
References configASSERT, eventCLEAR_EVENTS_ON_EXIT_BIT, eventEVENT_BITS_CONTROL_BYTES, eventUNBLOCKED_DUE_TO_BIT_SET, eventWAIT_FOR_ALL_BITS, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portYIELD_WITHIN_API, prvTestWaitCondition(), taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSCHEDULER_SUSPENDED, traceEVENT_GROUP_WAIT_BITS_BLOCK, traceEVENT_GROUP_WAIT_BITS_END, EventGroupDef_t::uxEventBits, uxTaskResetEventItemValue(), vTaskPlaceOnUnorderedEventList(), vTaskSuspendAll(), xTaskGetSchedulerState(), xTaskResumeAll(), and EventGroupDef_t::xTasksWaitingForBits.
Referenced by osEventFlagsWait().