NUCLEO-G0B1RE Examples: NUCLEO-G0B1RE/FreeRTOS_Queues/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c File Reference
heap_4.c File Reference
#include <stdlib.h>
#include "FreeRTOS.h"
#include "task.h"
Data Structures
struct A_BLOCK_LINK
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define heapMINIMUM_BLOCK_SIZE ((size_t) (xHeapStructSize << 1))
#define heapBITS_PER_BYTE ((size_t) 8)
Typedefs
typedef struct A_BLOCK_LINK BlockLink_t
Functions
static void prvInsertBlockIntoFreeList (BlockLink_t *pxBlockToInsert)
static void prvHeapInit (void)
void * pvPortMalloc (size_t xWantedSize)
void vPortFree (void *pv)
size_t xPortGetFreeHeapSize (void)
size_t xPortGetMinimumEverFreeHeapSize (void)
void vPortInitialiseBlocks (void)
void vPortGetHeapStats (HeapStats_t *pxHeapStats)
Variables
static uint8_t ucHeap [configTOTAL_HEAP_SIZE]
static const size_t xHeapStructSize = (sizeof(BlockLink_t) + ((size_t) (portBYTE_ALIGNMENT - 1))) & ~((size_t) portBYTE_ALIGNMENT_MASK)
static BlockLink_t xStart
static BlockLink_t * pxEnd = NULL
static size_t xFreeBytesRemaining = 0U
static size_t xMinimumEverFreeBytesRemaining = 0U
static size_t xNumberOfSuccessfulAllocations = 0
static size_t xNumberOfSuccessfulFrees = 0
static size_t xBlockAllocatedBit = 0
Macro Definition Documentation
heapBITS_PER_BYTE
#define heapBITS_PER_BYTE ((size_t) 8)
Definition at line 56 of file heap_4.c.
Referenced by prvHeapInit().
heapMINIMUM_BLOCK_SIZE
#define heapMINIMUM_BLOCK_SIZE ((size_t) (xHeapStructSize << 1))
Definition at line 53 of file heap_4.c.
Referenced by pvPortMalloc().
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 41 of file heap_4.c.
Typedef Documentation
BlockLink_t
typedef struct A_BLOCK_LINK BlockLink_t
Function Documentation
prvHeapInit()
static void prvHeapInit (void) static
Definition at line 333 of file heap_4.c.
{
BlockLink_t *pxFirstFreeBlock;
uint8_t *pucAlignedHeap;
size_t uxAddress;
size_t xTotalHeapSize = configTOTAL_HEAP_SIZE;
  /* Ensure the heap starts on a correctly aligned boundary. */
  uxAddress = ( size_t ) ucHeap;
  if( ( uxAddress & portBYTE_ALIGNMENT_MASK ) != 0 )
  {
    uxAddress += ( portBYTE_ALIGNMENT - 1 );
    uxAddress &= ~( ( size_t ) portBYTE_ALIGNMENT_MASK );
    xTotalHeapSize -= uxAddress - ( size_t ) ucHeap;
  }
  pucAlignedHeap = ( uint8_t * ) uxAddress;
  /* xStart is used to hold a pointer to the first item in the list of free
  blocks.  The void cast is used to prevent compiler warnings. */
  xStart.pxNextFreeBlock = ( void * ) pucAlignedHeap;
  xStart.xBlockSize = ( size_t ) 0;
  /* pxEnd is used to mark the end of the list of free blocks and is inserted
  at the end of the heap space. */
  uxAddress = ( ( size_t ) pucAlignedHeap ) + xTotalHeapSize;
  uxAddress -= xHeapStructSize;
  uxAddress &= ~( ( size_t ) portBYTE_ALIGNMENT_MASK );
  pxEnd = ( void * ) uxAddress;
  pxEnd->xBlockSize = 0;
  pxEnd->pxNextFreeBlock = NULL;
  /* To start with there is a single free block that is sized to take up the
  entire heap space, minus the space taken by pxEnd. */
  pxFirstFreeBlock = ( void * ) pucAlignedHeap;
  pxFirstFreeBlock->xBlockSize = uxAddress - ( size_t ) pxFirstFreeBlock;
  pxFirstFreeBlock->pxNextFreeBlock = pxEnd;
  /* Only one block exists - and it covers the entire usable heap space. */
  xMinimumEverFreeBytesRemaining = pxFirstFreeBlock->xBlockSize;
  xFreeBytesRemaining = pxFirstFreeBlock->xBlockSize;
  /* Work out the position of the top bit in a size_t variable. */
  xBlockAllocatedBit = ( ( size_t ) 1 ) << ( ( sizeof( size_t ) * heapBITS_PER_BYTE ) - 1 );
}
References configTOTAL_HEAP_SIZE, heapBITS_PER_BYTE, portBYTE_ALIGNMENT, pxEnd, A_BLOCK_LINK::pxNextFreeBlock, ucHeap, xBlockAllocatedBit, A_BLOCK_LINK::xBlockSize, xFreeBytesRemaining, xHeapStructSize, xMinimumEverFreeBytesRemaining, and xStart.
Referenced by pvPortMalloc().
prvInsertBlockIntoFreeList()
static void prvInsertBlockIntoFreeList (BlockLink_t * pxBlockToInsert) static
Definition at line 381 of file heap_4.c.
{
BlockLink_t *pxIterator;
uint8_t *puc;
  /* Iterate through the list until a block is found that has a higher address
  than the block being inserted. */
  for( pxIterator = &xStart; pxIterator->pxNextFreeBlock < pxBlockToInsert; pxIterator = pxIterator->pxNextFreeBlock )
  {
    /* Nothing to do here, just iterate to the right position. */
  }
  /* Do the block being inserted, and the block it is being inserted after
  make a contiguous block of memory? */
  puc = ( uint8_t * ) pxIterator;
  if( ( puc + pxIterator->xBlockSize ) == ( uint8_t * ) pxBlockToInsert )
  {
    pxIterator->xBlockSize += pxBlockToInsert->xBlockSize;
    pxBlockToInsert = pxIterator;
  }
  else
  {
    mtCOVERAGE_TEST_MARKER();
  }
  /* Do the block being inserted, and the block it is being inserted before
  make a contiguous block of memory? */
  puc = ( uint8_t * ) pxBlockToInsert;
  if( ( puc + pxBlockToInsert->xBlockSize ) == ( uint8_t * ) pxIterator->pxNextFreeBlock )
  {
    if( pxIterator->pxNextFreeBlock != pxEnd )
    {
      /* Form one big block from the two blocks. */
      pxBlockToInsert->xBlockSize += pxIterator->pxNextFreeBlock->xBlockSize;
      pxBlockToInsert->pxNextFreeBlock = pxIterator->pxNextFreeBlock->pxNextFreeBlock;
    }
    else
    {
      pxBlockToInsert->pxNextFreeBlock = pxEnd;
    }
  }
  else
  {
    pxBlockToInsert->pxNextFreeBlock = pxIterator->pxNextFreeBlock;
  }
  /* If the block being inserted plugged a gab, so was merged with the block
  before and the block after, then it's pxNextFreeBlock pointer will have
  already been set, and should not be set here as that would make it point
  to itself. */
  if( pxIterator != pxBlockToInsert )
  {
    pxIterator->pxNextFreeBlock = pxBlockToInsert;
  }
  else
  {
    mtCOVERAGE_TEST_MARKER();
  }
}
References mtCOVERAGE_TEST_MARKER, pxEnd, A_BLOCK_LINK::pxNextFreeBlock, A_BLOCK_LINK::xBlockSize, and xStart.
Referenced by pvPortMalloc(), and vPortFree().
pvPortMalloc()
void * pvPortMalloc (size_t xWantedSize)
Definition at line 115 of file heap_4.c.
{
BlockLink_t *pxBlock, *pxPreviousBlock, *pxNewBlockLink;
void *pvReturn = NULL;
  vTaskSuspendAll();
  {
    /* If this is the first call to malloc then the heap will require
    initialisation to setup the list of free blocks. */
    if( pxEnd == NULL )
    {
      prvHeapInit();
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
    /* Check the requested block size is not so large that the top bit is
    set.  The top bit of the block size member of the BlockLink_t structure
    is used to determine who owns the block - the application or the
    kernel, so it must be free. */
    if( ( xWantedSize & xBlockAllocatedBit ) == 0 )
    {
      /* The wanted size is increased so it can contain a BlockLink_t
      structure in addition to the requested amount of bytes. */
      if( xWantedSize > 0 )
      {
        xWantedSize += xHeapStructSize;
        /* Ensure that blocks are always aligned to the required number
        of bytes. */
        if( ( xWantedSize & portBYTE_ALIGNMENT_MASK ) != 0x00 )
        {
          /* Byte alignment required. */
          xWantedSize += ( portBYTE_ALIGNMENT - ( xWantedSize & portBYTE_ALIGNMENT_MASK ) );
          configASSERT( ( xWantedSize & portBYTE_ALIGNMENT_MASK ) == 0 );
        }
        else
        {
          mtCOVERAGE_TEST_MARKER();
        }
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
      if( ( xWantedSize > 0 ) && ( xWantedSize <= xFreeBytesRemaining ) )
      {
        /* Traverse the list from the start (lowest address) block until
        one of adequate size is found. */
        pxPreviousBlock = &xStart;
        pxBlock = xStart.pxNextFreeBlock;
        while( ( pxBlock->xBlockSize < xWantedSize ) && ( pxBlock->pxNextFreeBlock != NULL ) )
        {
          pxPreviousBlock = pxBlock;
          pxBlock = pxBlock->pxNextFreeBlock;
        }
        /* If the end marker was reached then a block of adequate size
        was not found. */
        if( pxBlock != pxEnd )
        {
          /* Return the memory space pointed to - jumping over the
          BlockLink_t structure at its start. */
          pvReturn = ( void * ) ( ( ( uint8_t * ) pxPreviousBlock->pxNextFreeBlock ) + xHeapStructSize );
          /* This block is being returned for use so must be taken out
          of the list of free blocks. */
          pxPreviousBlock->pxNextFreeBlock = pxBlock->pxNextFreeBlock;
          /* If the block is larger than required it can be split into
          two. */
          if( ( pxBlock->xBlockSize - xWantedSize ) > heapMINIMUM_BLOCK_SIZE )
          {
            /* This block is to be split into two.  Create a new
            block following the number of bytes requested. The void
            cast is used to prevent byte alignment warnings from the
            compiler. */
            pxNewBlockLink = ( void * ) ( ( ( uint8_t * ) pxBlock ) + xWantedSize );
            configASSERT( ( ( ( size_t ) pxNewBlockLink ) & portBYTE_ALIGNMENT_MASK ) == 0 );
            /* Calculate the sizes of two blocks split from the
            single block. */
            pxNewBlockLink->xBlockSize = pxBlock->xBlockSize - xWantedSize;
            pxBlock->xBlockSize = xWantedSize;
            /* Insert the new block into the list of free blocks. */
            prvInsertBlockIntoFreeList( pxNewBlockLink );
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
          xFreeBytesRemaining -= pxBlock->xBlockSize;
          if( xFreeBytesRemaining < xMinimumEverFreeBytesRemaining )
          {
            xMinimumEverFreeBytesRemaining = xFreeBytesRemaining;
          }
          else
          {
            mtCOVERAGE_TEST_MARKER();
          }
          /* The block is being returned - it is allocated and owned
          by the application and has no "next" block. */
          pxBlock->xBlockSize |= xBlockAllocatedBit;
          pxBlock->pxNextFreeBlock = NULL;
          xNumberOfSuccessfulAllocations++;
        }
        else
        {
          mtCOVERAGE_TEST_MARKER();
        }
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
    traceMALLOC( pvReturn, xWantedSize );
  }
  ( void ) xTaskResumeAll();
  #if( configUSE_MALLOC_FAILED_HOOK == 1 )
  {
    if( pvReturn == NULL )
    {
      extern void vApplicationMallocFailedHook( void );
      vApplicationMallocFailedHook();
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
  }
  #endif
  configASSERT( ( ( ( size_t ) pvReturn ) & ( size_t ) portBYTE_ALIGNMENT_MASK ) == 0 );
  return pvReturn;
}
References configASSERT, heapMINIMUM_BLOCK_SIZE, mtCOVERAGE_TEST_MARKER, portBYTE_ALIGNMENT, prvHeapInit(), prvInsertBlockIntoFreeList(), pxEnd, A_BLOCK_LINK::pxNextFreeBlock, traceMALLOC, vApplicationMallocFailedHook(), vTaskSuspendAll(), xBlockAllocatedBit, A_BLOCK_LINK::xBlockSize, xFreeBytesRemaining, xHeapStructSize, xMinimumEverFreeBytesRemaining, xNumberOfSuccessfulAllocations, xStart, and xTaskResumeAll().
Referenced by osThreadEnumerate().
vPortFree()
void vPortFree (void * pv)
Definition at line 266 of file heap_4.c.
{
uint8_t *puc = (uint8_t *) pv;
BlockLink_t *pxLink;
  if( pv != NULL )
  {
    /* The memory being freed will have an BlockLink_t structure immediately
    before it. */
    puc -= xHeapStructSize;
    /* This casting is to keep the compiler from issuing warnings. */
    pxLink = ( void * ) puc;
    /* Check the block is actually allocated. */
    configASSERT( ( pxLink->xBlockSize & xBlockAllocatedBit ) != 0 );
    configASSERT( pxLink->pxNextFreeBlock == NULL );
    if( ( pxLink->xBlockSize & xBlockAllocatedBit ) != 0 )
    {
      if( pxLink->pxNextFreeBlock == NULL )
      {
        /* The block is being returned to the heap - it is no longer
        allocated. */
        pxLink->xBlockSize &= ~xBlockAllocatedBit;
        vTaskSuspendAll();
        {
          /* Add this block to the list of free blocks. */
          xFreeBytesRemaining += pxLink->xBlockSize;
          traceFREE( pv, pxLink->xBlockSize );
          prvInsertBlockIntoFreeList( ( ( BlockLink_t * ) pxLink ) );
          xNumberOfSuccessfulFrees++;
        }
        ( void ) xTaskResumeAll();
      }
      else
      {
        mtCOVERAGE_TEST_MARKER();
      }
    }
    else
    {
      mtCOVERAGE_TEST_MARKER();
    }
  }
}
References configASSERT, mtCOVERAGE_TEST_MARKER, prvInsertBlockIntoFreeList(), A_BLOCK_LINK::pxNextFreeBlock, traceFREE, vTaskSuspendAll(), xBlockAllocatedBit, A_BLOCK_LINK::xBlockSize, xFreeBytesRemaining, xHeapStructSize, xNumberOfSuccessfulFrees, and xTaskResumeAll().
Referenced by osThreadEnumerate(), vEventGroupDelete(), vQueueDelete(), and vStreamBufferDelete().
vPortGetHeapStats()
void vPortGetHeapStats (HeapStats_t * pxHeapStats)
Definition at line 442 of file heap_4.c.
{
BlockLink_t *pxBlock;
size_t xBlocks = 0, xMaxSize = 0, xMinSize = portMAX_DELAY; /* portMAX_DELAY used as a portable way of getting the maximum value. */
  vTaskSuspendAll();
  {
    pxBlock = xStart.pxNextFreeBlock;
    /* pxBlock will be NULL if the heap has not been initialised.  The heap
    is initialised automatically when the first allocation is made. */
    if( pxBlock != NULL )
    {
      do
      {
        /* Increment the number of blocks and record the largest block seen
        so far. */
        xBlocks++;
        if( pxBlock->xBlockSize > xMaxSize )
        {
          xMaxSize = pxBlock->xBlockSize;
        }
        if( pxBlock->xBlockSize < xMinSize )
        {
          xMinSize = pxBlock->xBlockSize;
        }
        /* Move to the next block in the chain until the last block is
        reached. */
        pxBlock = pxBlock->pxNextFreeBlock;
      } while( pxBlock != pxEnd );
    }
  }
  xTaskResumeAll();
  pxHeapStats->xSizeOfLargestFreeBlockInBytes = xMaxSize;
  pxHeapStats->xSizeOfSmallestFreeBlockInBytes = xMinSize;
  pxHeapStats->xNumberOfFreeBlocks = xBlocks;
  taskENTER_CRITICAL();
  {
    pxHeapStats->xAvailableHeapSpaceInBytes = xFreeBytesRemaining;
    pxHeapStats->xNumberOfSuccessfulAllocations = xNumberOfSuccessfulAllocations;
    pxHeapStats->xNumberOfSuccessfulFrees = xNumberOfSuccessfulFrees;
    pxHeapStats->xMinimumEverFreeBytesRemaining = xMinimumEverFreeBytesRemaining;
  }
  taskEXIT_CRITICAL();
}
References portMAX_DELAY, pxEnd, A_BLOCK_LINK::pxNextFreeBlock, taskENTER_CRITICAL, taskEXIT_CRITICAL, vTaskSuspendAll(), xHeapStats::xAvailableHeapSpaceInBytes, A_BLOCK_LINK::xBlockSize, xFreeBytesRemaining, xHeapStats::xMinimumEverFreeBytesRemaining, xMinimumEverFreeBytesRemaining, xHeapStats::xNumberOfFreeBlocks, xHeapStats::xNumberOfSuccessfulAllocations, xNumberOfSuccessfulAllocations, xHeapStats::xNumberOfSuccessfulFrees, xNumberOfSuccessfulFrees, xHeapStats::xSizeOfLargestFreeBlockInBytes, xHeapStats::xSizeOfSmallestFreeBlockInBytes, xStart, and xTaskResumeAll().
vPortInitialiseBlocks()
void vPortInitialiseBlocks (void)
Definition at line 327 of file heap_4.c.
{
  /* This just exists to keep the linker quiet. */
}
xPortGetFreeHeapSize()
size_t xPortGetFreeHeapSize (void)
Definition at line 315 of file heap_4.c.
{
  return xFreeBytesRemaining;
}
References xFreeBytesRemaining.
xPortGetMinimumEverFreeHeapSize()
size_t xPortGetMinimumEverFreeHeapSize (void)
Definition at line 321 of file heap_4.c.
{
  return xMinimumEverFreeBytesRemaining;
}
References xMinimumEverFreeBytesRemaining.
Variable Documentation
pxEnd
BlockLink_t * pxEnd = NULL static
Definition at line 98 of file heap_4.c.
Referenced by prvHeapInit(), prvInsertBlockIntoFreeList(), pvPortMalloc(), and vPortGetHeapStats().
ucHeap
uint8_t ucHeap[configTOTAL_HEAP_SIZE] static
Definition at line 64 of file heap_4.c.
Referenced by prvHeapInit().
xBlockAllocatedBit
size_t xBlockAllocatedBit = 0 static
Definition at line 111 of file heap_4.c.
Referenced by prvHeapInit(), pvPortMalloc(), and vPortFree().
xFreeBytesRemaining
size_t xFreeBytesRemaining = 0U static
Definition at line 102 of file heap_4.c.
Referenced by prvHeapInit(), pvPortMalloc(), vPortFree(), vPortGetHeapStats(), and xPortGetFreeHeapSize().
xHeapStructSize
const size_t xHeapStructSize = (sizeof(BlockLink_t) + ((size_t) (portBYTE_ALIGNMENT - 1))) & ~((size_t) portBYTE_ALIGNMENT_MASK) static
Definition at line 95 of file heap_4.c.
Referenced by prvHeapInit(), pvPortMalloc(), and vPortFree().
xMinimumEverFreeBytesRemaining
size_t xMinimumEverFreeBytesRemaining = 0U static
Definition at line 103 of file heap_4.c.
Referenced by prvHeapInit(), pvPortMalloc(), vPortGetHeapStats(), and xPortGetMinimumEverFreeHeapSize().
xNumberOfSuccessfulAllocations
size_t xNumberOfSuccessfulAllocations = 0 static
Definition at line 104 of file heap_4.c.
Referenced by pvPortMalloc(), and vPortGetHeapStats().
xNumberOfSuccessfulFrees
size_t xNumberOfSuccessfulFrees = 0 static
Definition at line 105 of file heap_4.c.
Referenced by vPortFree(), and vPortGetHeapStats().
xStart
BlockLink_t xStart static
Definition at line 98 of file heap_4.c.
Referenced by prvHeapInit(), prvInsertBlockIntoFreeList(), pvPortMalloc(), and vPortGetHeapStats().