NUCLEO-G0B1RE Examples: NUCLEO-G0B1RE/FreeRTOS_Queues/Middlewares/Third_Party/FreeRTOS/Source/list.c File Reference
list.c File Reference
#include <stdlib.h>
#include "FreeRTOS.h"
#include "list.h"
Functions
void vListInitialise (List_t *const pxList)
void vListInitialiseItem (ListItem_t *const pxItem)
void vListInsertEnd (List_t *const pxList, ListItem_t *const pxNewListItem)
void vListInsert (List_t *const pxList, ListItem_t *const pxNewListItem)
UBaseType_t uxListRemove (ListItem_t *const pxItemToRemove)
Function Documentation
uxListRemove()
UBaseType_t uxListRemove (ListItem_t *const pxItemToRemove)
Definition at line 170 of file list.c.
{
/* The list item knows which list it is in.  Obtain the list from the list
item. */
List_t * const pxList = pxItemToRemove->pxContainer;
  pxItemToRemove->pxNext->pxPrevious = pxItemToRemove->pxPrevious;
  pxItemToRemove->pxPrevious->pxNext = pxItemToRemove->pxNext;
  /* Only used during decision coverage testing. */
  mtCOVERAGE_TEST_DELAY();
  /* Make sure the index is left pointing to a valid item. */
  if( pxList->pxIndex == pxItemToRemove )
  {
    pxList->pxIndex = pxItemToRemove->pxPrevious;
  }
  else
  {
    mtCOVERAGE_TEST_MARKER();
  }
  pxItemToRemove->pxContainer = NULL;
  ( pxList->uxNumberOfItems )--;
  return pxList->uxNumberOfItems;
}
References mtCOVERAGE_TEST_DELAY, mtCOVERAGE_TEST_MARKER, xLIST_ITEM::pxContainer, xLIST::pxIndex, xLIST_ITEM::pxNext, xLIST_ITEM::pxPrevious, and xLIST::uxNumberOfItems.
Referenced by prvAddCurrentTaskToDelayedList(), prvCheckTasksWaitingTermination(), vTaskRemoveFromUnorderedEventList(), xTaskIncrementTick(), xTaskRemoveFromEventList(), and xTaskResumeAll().
vListInitialise()
void vListInitialise (List_t *const pxList)
Definition at line 37 of file list.c.
{
  /* The list structure contains a list item which is used to mark the
  end of the list.  To initialise the list the list end is inserted
  as the only list entry. */
  pxList->pxIndex = ( ListItem_t * ) &( pxList->xListEnd );     /*lint !e826 !e740 !e9087 The mini list structure is used as the list end to save RAM.  This is checked and valid. */
  /* The list end value is the highest possible value in the list to
  ensure it remains at the end of the list. */
  pxList->xListEnd.xItemValue = portMAX_DELAY;
  /* The list end next and previous pointers point to itself so we know
  when the list is empty. */
  pxList->xListEnd.pxNext = ( ListItem_t * ) &( pxList->xListEnd ); /*lint !e826 !e740 !e9087 The mini list structure is used as the list end to save RAM.  This is checked and valid. */
  pxList->xListEnd.pxPrevious = ( ListItem_t * ) &( pxList->xListEnd );/*lint !e826 !e740 !e9087 The mini list structure is used as the list end to save RAM.  This is checked and valid. */
  pxList->uxNumberOfItems = ( UBaseType_t ) 0U;
  /* Write known values into the list if
  configUSE_LIST_DATA_INTEGRITY_CHECK_BYTES is set to 1. */
  listSET_LIST_INTEGRITY_CHECK_1_VALUE( pxList );
  listSET_LIST_INTEGRITY_CHECK_2_VALUE( pxList );
}
References listSET_LIST_INTEGRITY_CHECK_1_VALUE, listSET_LIST_INTEGRITY_CHECK_2_VALUE, portMAX_DELAY, xLIST::pxIndex, xMINI_LIST_ITEM::pxNext, xMINI_LIST_ITEM::pxPrevious, xLIST::uxNumberOfItems, xMINI_LIST_ITEM::xItemValue, and xLIST::xListEnd.
Referenced by prvInitialiseTaskLists(), and xQueueGenericReset().
vListInitialiseItem()
void vListInitialiseItem (ListItem_t *const pxItem)
Definition at line 62 of file list.c.
{
  /* Make sure the list item is not recorded as being on a list. */
  pxItem->pxContainer = NULL;
  /* Write known values into the list item if
  configUSE_LIST_DATA_INTEGRITY_CHECK_BYTES is set to 1. */
  listSET_FIRST_LIST_ITEM_INTEGRITY_CHECK_VALUE( pxItem );
  listSET_SECOND_LIST_ITEM_INTEGRITY_CHECK_VALUE( pxItem );
}
References listSET_FIRST_LIST_ITEM_INTEGRITY_CHECK_VALUE, listSET_SECOND_LIST_ITEM_INTEGRITY_CHECK_VALUE, and xLIST_ITEM::pxContainer.
vListInsert()
void vListInsert (List_t *const pxList, ListItem_t *const pxNewListItem)
Definition at line 103 of file list.c.
{
ListItem_t *pxIterator;
const TickType_t xValueOfInsertion = pxNewListItem->xItemValue;
  /* Only effective when configASSERT() is also defined, these tests may catch
  the list data structures being overwritten in memory.  They will not catch
  data errors caused by incorrect configuration or use of FreeRTOS. */
  listTEST_LIST_INTEGRITY( pxList );
  listTEST_LIST_ITEM_INTEGRITY( pxNewListItem );
  /* Insert the new list item into the list, sorted in xItemValue order.
  If the list already contains a list item with the same item value then the
  new list item should be placed after it.  This ensures that TCBs which are
  stored in ready lists (all of which have the same xItemValue value) get a
  share of the CPU.  However, if the xItemValue is the same as the back marker
  the iteration loop below will not end.  Therefore the value is checked
  first, and the algorithm slightly modified if necessary. */
  if( xValueOfInsertion == portMAX_DELAY )
  {
    pxIterator = pxList->xListEnd.pxPrevious;
  }
  else
  {
    /* *** NOTE ***********************************************************
    If you find your application is crashing here then likely causes are
    listed below.  In addition see https://www.freertos.org/FAQHelp.html for
    more tips, and ensure configASSERT() is defined!
    https://www.freertos.org/a00110.html#configASSERT
      1) Stack overflow -
         see https://www.freertos.org/Stacks-and-stack-overflow-checking.html
      2) Incorrect interrupt priority assignment, especially on Cortex-M
         parts where numerically high priority values denote low actual
         interrupt priorities, which can seem counter intuitive.  See
         https://www.freertos.org/RTOS-Cortex-M3-M4.html and the definition
         of configMAX_SYSCALL_INTERRUPT_PRIORITY on
         https://www.freertos.org/a00110.html
      3) Calling an API function from within a critical section or when
         the scheduler is suspended, or calling an API function that does
         not end in "FromISR" from an interrupt.
      4) Using a queue or semaphore before it has been initialised or
         before the scheduler has been started (are interrupts firing
         before vTaskStartScheduler() has been called?).
    **********************************************************************/
    for( pxIterator = ( ListItem_t * ) &( pxList->xListEnd ); pxIterator->pxNext->xItemValue <= xValueOfInsertion; pxIterator = pxIterator->pxNext ) /*lint !e826 !e740 !e9087 The mini list structure is used as the list end to save RAM.  This is checked and valid. *//*lint !e440 The iterator moves to a different value, not xValueOfInsertion. */
    {
      /* There is nothing to do here, just iterating to the wanted
      insertion position. */
    }
  }
  pxNewListItem->pxNext = pxIterator->pxNext;
  pxNewListItem->pxNext->pxPrevious = pxNewListItem;
  pxNewListItem->pxPrevious = pxIterator;
  pxIterator->pxNext = pxNewListItem;
  /* Remember which list the item is in.  This allows fast removal of the
  item later. */
  pxNewListItem->pxContainer = pxList;
  ( pxList->uxNumberOfItems )++;
}
References listTEST_LIST_INTEGRITY, listTEST_LIST_ITEM_INTEGRITY, portMAX_DELAY, xLIST_ITEM::pxContainer, xLIST_ITEM::pxNext, xLIST_ITEM::pxPrevious, xMINI_LIST_ITEM::pxPrevious, xLIST::uxNumberOfItems, xLIST_ITEM::xItemValue, and xLIST::xListEnd.
Referenced by prvAddCurrentTaskToDelayedList(), and vTaskPlaceOnEventList().
vListInsertEnd()
void vListInsertEnd (List_t *const pxList, ListItem_t *const pxNewListItem)
Definition at line 74 of file list.c.
{
ListItem_t * const pxIndex = pxList->pxIndex;
  /* Only effective when configASSERT() is also defined, these tests may catch
  the list data structures being overwritten in memory.  They will not catch
  data errors caused by incorrect configuration or use of FreeRTOS. */
  listTEST_LIST_INTEGRITY( pxList );
  listTEST_LIST_ITEM_INTEGRITY( pxNewListItem );
  /* Insert a new list item into pxList, but rather than sort the list,
  makes the new list item the last item to be removed by a call to
  listGET_OWNER_OF_NEXT_ENTRY(). */
  pxNewListItem->pxNext = pxIndex;
  pxNewListItem->pxPrevious = pxIndex->pxPrevious;
  /* Only used during decision coverage testing. */
  mtCOVERAGE_TEST_DELAY();
  pxIndex->pxPrevious->pxNext = pxNewListItem;
  pxIndex->pxPrevious = pxNewListItem;
  /* Remember which list the item is in. */
  pxNewListItem->pxContainer = pxList;
  ( pxList->uxNumberOfItems )++;
}
References listTEST_LIST_INTEGRITY, listTEST_LIST_ITEM_INTEGRITY, mtCOVERAGE_TEST_DELAY, xLIST_ITEM::pxContainer, xLIST::pxIndex, xLIST_ITEM::pxNext, xLIST_ITEM::pxPrevious, and xLIST::uxNumberOfItems.
Referenced by prvAddCurrentTaskToDelayedList(), vTaskPlaceOnUnorderedEventList(), and xTaskRemoveFromEventList().