NUCLEO-G0B1RE Examples: NUCLEO-G0B1RE/FreeRTOS_Queues/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0/port.c File Reference
port.c File Reference
#include "FreeRTOS.h"
#include "task.h"
Macros
#define portNVIC_SYSTICK_CTRL_REG (* ((volatile uint32_t *) 0xe000e010))
#define portNVIC_SYSTICK_LOAD_REG (* ((volatile uint32_t *) 0xe000e014))
#define portNVIC_SYSTICK_CURRENT_VALUE_REG (* ((volatile uint32_t *) 0xe000e018))
#define portNVIC_INT_CTRL_REG (* ((volatile uint32_t *) 0xe000ed04))
#define portNVIC_SYSPRI2_REG (* ((volatile uint32_t *) 0xe000ed20))
#define portNVIC_SYSTICK_CLK_BIT (1UL << 2UL)
#define portNVIC_SYSTICK_INT_BIT (1UL << 1UL)
#define portNVIC_SYSTICK_ENABLE_BIT (1UL << 0UL)
#define portNVIC_SYSTICK_COUNT_FLAG_BIT (1UL << 16UL)
#define portNVIC_PENDSVSET_BIT (1UL << 28UL)
#define portMIN_INTERRUPT_PRIORITY (255UL)
#define portNVIC_PENDSV_PRI (portMIN_INTERRUPT_PRIORITY << 16UL)
#define portNVIC_SYSTICK_PRI (portMIN_INTERRUPT_PRIORITY << 24UL)
#define portINITIAL_XPSR (0x01000000)
#define portMAX_24_BIT_NUMBER (0xffffffUL)
#define portMISSED_COUNTS_FACTOR (45UL)
#define portTASK_RETURN_ADDRESS prvTaskExitError
Functions
void vPortSetupTimerInterrupt (void)
void xPortPendSVHandler (void xPortSysTickHandler void)
static void prvTaskExitError (void)
void vPortSVCHandler (void)
void vPortStartFirstTask (void)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
void vPortYield (void)
void vPortEnterCritical (void)
void vPortExitCritical (void)
uint32_t ulSetInterruptMaskFromISR (void)
void vClearInterruptMaskFromISR (__attribute__((unused)) uint32_t ulMask)
void xPortPendSVHandler (void)
void xPortSysTickHandler (void)
__attribute__ ((weak))
Macro Definition Documentation
portINITIAL_XPSR
#define portINITIAL_XPSR (0x01000000)
Definition at line 52 of file port.c.
portMAX_24_BIT_NUMBER
#define portMAX_24_BIT_NUMBER (0xffffffUL)
Definition at line 55 of file port.c.
Referenced by __attribute__().
portMIN_INTERRUPT_PRIORITY
#define portMIN_INTERRUPT_PRIORITY (255UL)
Definition at line 47 of file port.c.
portMISSED_COUNTS_FACTOR
#define portMISSED_COUNTS_FACTOR (45UL)
Definition at line 61 of file port.c.
Referenced by __attribute__().
portNVIC_INT_CTRL_REG
#define portNVIC_INT_CTRL_REG (* ((volatile uint32_t *) 0xe000ed04))
Definition at line 40 of file port.c.
Referenced by vPortYield(), and xPortSysTickHandler().
portNVIC_PENDSV_PRI
#define portNVIC_PENDSV_PRI (portMIN_INTERRUPT_PRIORITY << 16UL)
Definition at line 48 of file port.c.
Referenced by xPortStartScheduler().
portNVIC_PENDSVSET_BIT
#define portNVIC_PENDSVSET_BIT (1UL << 28UL)
Definition at line 46 of file port.c.
Referenced by vPortYield(), and xPortSysTickHandler().
portNVIC_SYSPRI2_REG
#define portNVIC_SYSPRI2_REG (* ((volatile uint32_t *) 0xe000ed20))
Definition at line 41 of file port.c.
Referenced by xPortStartScheduler().
portNVIC_SYSTICK_CLK_BIT
#define portNVIC_SYSTICK_CLK_BIT (1UL << 2UL)
Definition at line 42 of file port.c.
Referenced by __attribute__().
portNVIC_SYSTICK_COUNT_FLAG_BIT
#define portNVIC_SYSTICK_COUNT_FLAG_BIT (1UL << 16UL)
Definition at line 45 of file port.c.
portNVIC_SYSTICK_CTRL_REG
#define portNVIC_SYSTICK_CTRL_REG (* ((volatile uint32_t *) 0xe000e010))
Definition at line 37 of file port.c.
Referenced by __attribute__().
portNVIC_SYSTICK_CURRENT_VALUE_REG
#define portNVIC_SYSTICK_CURRENT_VALUE_REG (* ((volatile uint32_t *) 0xe000e018))
Definition at line 39 of file port.c.
Referenced by __attribute__().
portNVIC_SYSTICK_ENABLE_BIT
#define portNVIC_SYSTICK_ENABLE_BIT (1UL << 0UL)
Definition at line 44 of file port.c.
Referenced by __attribute__().
portNVIC_SYSTICK_INT_BIT
#define portNVIC_SYSTICK_INT_BIT (1UL << 1UL)
Definition at line 43 of file port.c.
Referenced by __attribute__().
portNVIC_SYSTICK_LOAD_REG
#define portNVIC_SYSTICK_LOAD_REG (* ((volatile uint32_t *) 0xe000e014))
Definition at line 38 of file port.c.
Referenced by __attribute__().
portNVIC_SYSTICK_PRI
#define portNVIC_SYSTICK_PRI (portMIN_INTERRUPT_PRIORITY << 24UL)
Definition at line 49 of file port.c.
Referenced by xPortStartScheduler().
portTASK_RETURN_ADDRESS
#define portTASK_RETURN_ADDRESS prvTaskExitError
Definition at line 70 of file port.c.
Function Documentation
__attribute__()
__attribute__ ((weak))
Definition at line 375 of file port.c.
{
  /* Calculate the constants required to configure the tick interrupt. */
  #if( configUSE_TICKLESS_IDLE == 1 )
  {
    ulTimerCountsForOneTick = ( configCPU_CLOCK_HZ / configTICK_RATE_HZ );
    xMaximumPossibleSuppressedTicks = portMAX_24_BIT_NUMBER / ulTimerCountsForOneTick;
    ulStoppedTimerCompensation = portMISSED_COUNTS_FACTOR;
  }
  #endif /* configUSE_TICKLESS_IDLE */
  /* Stop and reset the SysTick. */
  portNVIC_SYSTICK_CTRL_REG = 0UL;
  portNVIC_SYSTICK_CURRENT_VALUE_REG = 0UL;
  /* Configure SysTick to interrupt at the requested rate. */
  portNVIC_SYSTICK_LOAD_REG = ( configCPU_CLOCK_HZ / configTICK_RATE_HZ ) - 1UL;
  portNVIC_SYSTICK_CTRL_REG = portNVIC_SYSTICK_CLK_BIT | portNVIC_SYSTICK_INT_BIT | portNVIC_SYSTICK_ENABLE_BIT;
}
References configCPU_CLOCK_HZ, configTICK_RATE_HZ, portMAX_24_BIT_NUMBER, portMISSED_COUNTS_FACTOR, portNVIC_SYSTICK_CLK_BIT, portNVIC_SYSTICK_CTRL_REG, portNVIC_SYSTICK_CURRENT_VALUE_REG, portNVIC_SYSTICK_ENABLE_BIT, portNVIC_SYSTICK_INT_BIT, and portNVIC_SYSTICK_LOAD_REG.
prvTaskExitError()
static void prvTaskExitError (void) static
Definition at line 151 of file port.c.
{
volatile uint32_t ulDummy = 0UL;
  /* A function that implements a task must not exit or attempt to return to
  its caller as there is nothing to return to.  If a task wants to exit it
  should instead call vTaskDelete( NULL ).
  Artificially force an assert() to be triggered if configASSERT() is
  defined, then stop here so application writers can catch the error. */
  configASSERT( uxCriticalNesting == ~0UL );
  portDISABLE_INTERRUPTS();
  while( ulDummy == 0 )
  {
    /* This file calls prvTaskExitError() after the scheduler has been
    started to remove a compiler warning about the function being defined
    but never called.  ulDummy is used purely to quieten other warnings
    about code appearing after this function is called - making ulDummy
    volatile makes the compiler think the function could return and
    therefore not output an 'unreachable code' warning for code that appears
    after it. */
  }
}
References configASSERT, and portDISABLE_INTERRUPTS.
Referenced by xPortStartScheduler().
ulSetInterruptMaskFromISR()
uint32_t ulSetInterruptMaskFromISR (void)
Definition at line 284 of file port.c.
{
  __asm volatile(
          " mrs r0, PRIMASK \n"
          " cpsid i     \n"
          " bx lr         "
          ::: "memory"
          );
}
vClearInterruptMaskFromISR()
void vClearInterruptMaskFromISR (__attribute__((unused)) uint32_t ulMask)
Definition at line 295 of file port.c.
{
  __asm volatile(
          " msr PRIMASK, r0 \n"
          " bx lr         "
          ::: "memory"
          );
}
vPortEndScheduler()
void vPortEndScheduler (void)
Definition at line 244 of file port.c.
{
  /* Not implemented in ports where there is nothing to return to.
  Artificially force an assert. */
  configASSERT( uxCriticalNesting == 1000UL );
}
References configASSERT.
Referenced by vTaskEndScheduler().
vPortEnterCritical()
void vPortEnterCritical (void)
Definition at line 264 of file port.c.
{
  portDISABLE_INTERRUPTS();
  uxCriticalNesting++;
  __asm volatile( "dsb" ::: "memory" );
  __asm volatile( "isb" );
}
References portDISABLE_INTERRUPTS.
vPortExitCritical()
void vPortExitCritical (void)
Definition at line 273 of file port.c.
{
  configASSERT( uxCriticalNesting );
  uxCriticalNesting--;
  if( uxCriticalNesting == 0 )
  {
    portENABLE_INTERRUPTS();
  }
}
References configASSERT, and portENABLE_INTERRUPTS.
vPortSetupTimerInterrupt()
void vPortSetupTimerInterrupt (void)
Referenced by xPortStartScheduler().
vPortStartFirstTask()
void vPortStartFirstTask (void)
Definition at line 183 of file port.c.
{
  /* The MSP stack is not reset as, unlike on M3/4 parts, there is no vector
  table offset register that can be used to locate the initial stack value.
  Not all M0 parts have the application vector table at address 0. */
  __asm volatile(
  " .syntax unified       \n"
  " ldr  r2, pxCurrentTCBConst2 \n" /* Obtain location of pxCurrentTCB. */
  " ldr  r3, [r2]       \n"
  " ldr  r0, [r3]       \n" /* The first item in pxCurrentTCB is the task top of stack. */
  " adds r0, #32          \n" /* Discard everything up to r0. */
  " msr  psp, r0          \n" /* This is now the new top of stack to use in the task. */
  " movs r0, #2         \n" /* Switch to the psp stack. */
  " msr  CONTROL, r0        \n"
  " isb             \n"
  " pop  {r0-r5}          \n" /* Pop the registers that are saved automatically. */
  " mov  lr, r5         \n" /* lr is now in r5. */
  " pop  {r3}         \n" /* Return address is now in r3. */
  " pop  {r2}         \n" /* Pop and discard XPSR. */
  " cpsie i           \n" /* The first task has its context and interrupts can be enabled. */
  " bx   r3           \n" /* Finally, jump to the user defined task code. */
  "               \n"
  " .align 4          \n"
  "pxCurrentTCBConst2: .word pxCurrentTCB   "
          );
}
Referenced by xPortStartScheduler().
vPortSVCHandler()
void vPortSVCHandler (void)
Definition at line 176 of file port.c.
{
  /* This function is no longer used, but retained for backward
  compatibility. */
}
vPortYield()
void vPortYield (void)
Definition at line 252 of file port.c.
{
  /* Set a PendSV to request a context switch. */
  portNVIC_INT_CTRL_REG = portNVIC_PENDSVSET_BIT;
  /* Barriers are normally not required but do ensure the code is completely
  within the specified behaviour for the architecture. */
  __asm volatile( "dsb" ::: "memory" );
  __asm volatile( "isb" );
}
References portNVIC_INT_CTRL_REG, and portNVIC_PENDSVSET_BIT.
xPortPendSVHandler() [1/2]
void xPortPendSVHandler (void xPortSysTickHandler void)
Definition at line 83 of file port.c.
{
  /* Simulate the stack frame as it would be created by a context switch
  interrupt. */
  pxTopOfStack--; /* Offset added to account for the way the MCU uses the stack on entry/exit of interrupts. */
  *pxTopOfStack = portINITIAL_XPSR; /* xPSR */
  pxTopOfStack--;
  *pxTopOfStack = ( StackType_t ) pxCode; /* PC */
  pxTopOfStack--;
  *pxTopOfStack = ( StackType_t ) portTASK_RETURN_ADDRESS;  /* LR */
  pxTopOfStack -= 5;  /* R12, R3, R2 and R1. */
  *pxTopOfStack = ( StackType_t ) pvParameters; /* R0 */
  pxTopOfStack -= 8; /* R11..R4. */
  return pxTopOfStack;
}
xPortPendSVHandler() [2/2]
void xPortPendSVHandler (void)
Definition at line 305 of file port.c.
{
  /* This is a naked function. */
  __asm volatile
  (
  " .syntax unified           \n"
  " mrs r0, psp             \n"
  "                   \n"
  " ldr r3, pxCurrentTCBConst     \n" /* Get the location of the current TCB. */
  " ldr r2, [r3]            \n"
  "                   \n"
  " subs r0, r0, #32          \n" /* Make space for the remaining low registers. */
  " str r0, [r2]            \n" /* Save the new top of stack. */
  " stmia r0!, {r4-r7}          \n" /* Store the low registers that are not saved automatically. */
  "   mov r4, r8              \n" /* Store the high registers. */
  "   mov r5, r9              \n"
  "   mov r6, r10             \n"
  "   mov r7, r11             \n"
  "   stmia r0!, {r4-r7}          \n"
  "                   \n"
  " push {r3, r14}            \n"
  " cpsid i               \n"
  " bl vTaskSwitchContext       \n"
  " cpsie i               \n"
  " pop {r2, r3}            \n" /* lr goes in r3. r2 now holds tcb pointer. */
  "                   \n"
  " ldr r1, [r2]            \n"
  " ldr r0, [r1]            \n" /* The first item in pxCurrentTCB is the task top of stack. */
  " adds r0, r0, #16          \n" /* Move to the high registers. */
  " ldmia r0!, {r4-r7}          \n" /* Pop the high registers. */
  "   mov r8, r4              \n"
  "   mov r9, r5              \n"
  "   mov r10, r6             \n"
  "   mov r11, r7             \n"
  "                   \n"
  " msr psp, r0             \n" /* Remember the new top of stack for the task. */
  "                   \n"
  " subs r0, r0, #32          \n" /* Go back for the low registers that are not automatically restored. */
  "   ldmia r0!, {r4-r7}          \n" /* Pop low registers.  */
  "                   \n"
  " bx r3               \n"
  "                   \n"
  " .align 4              \n"
  "pxCurrentTCBConst: .word pxCurrentTCB    "
  );
}
xPortStartScheduler()
BaseType_t xPortStartScheduler (void)
Definition at line 214 of file port.c.
{
  /* Make PendSV, CallSV and SysTick the same priority as the kernel. */
  portNVIC_SYSPRI2_REG |= portNVIC_PENDSV_PRI;
  portNVIC_SYSPRI2_REG |= portNVIC_SYSTICK_PRI;
  /* Start the timer that generates the tick ISR.  Interrupts are disabled
  here already. */
  vPortSetupTimerInterrupt();
  /* Initialise the critical nesting count ready for the first task. */
  uxCriticalNesting = 0;
  /* Start the first task. */
  vPortStartFirstTask();
  /* Should never get here as the tasks will now be executing!  Call the task
  exit error function to prevent compiler warnings about a static function
  not being called in the case that the application writer overrides this
  functionality by defining configTASK_RETURN_ADDRESS.  Call
  vTaskSwitchContext() so link time optimisation does not remove the
  symbol. */
  vTaskSwitchContext();
  prvTaskExitError();
  /* Should not get here! */
  return 0;
}
References portNVIC_PENDSV_PRI, portNVIC_SYSPRI2_REG, portNVIC_SYSTICK_PRI, prvTaskExitError(), vPortSetupTimerInterrupt(), vPortStartFirstTask(), and vTaskSwitchContext().
Referenced by vTaskStartScheduler().
xPortSysTickHandler()
void xPortSysTickHandler (void)
Definition at line 354 of file port.c.
{
uint32_t ulPreviousMask;
  ulPreviousMask = portSET_INTERRUPT_MASK_FROM_ISR();
  {
    /* Increment the RTOS tick. */
    if( xTaskIncrementTick() != pdFALSE )
    {
      /* Pend a context switch. */
      portNVIC_INT_CTRL_REG = portNVIC_PENDSVSET_BIT;
    }
  }
  portCLEAR_INTERRUPT_MASK_FROM_ISR( ulPreviousMask );
}
References pdFALSE, portCLEAR_INTERRUPT_MASK_FROM_ISR, portNVIC_INT_CTRL_REG, portNVIC_PENDSVSET_BIT, portSET_INTERRUPT_MASK_FROM_ISR, and xTaskIncrementTick().